import SemiBase.Statement
import SemiBase.Catalogue.Order6.Part042
import Order6FinalL5TransferV3.Part142
import Order6FinalL5TransferV3.Part143
import Order6FinalL5TransferV3.Part144
import Order6FinalL5TransferV3.Part145
import Order6FinalL5TransferV3.Part146
import SemigroupBasis.CoRoots.Order6Day10.S3_15.Rank048ClassEndpoints
import SemigroupBasis.CoRoots.Order6Day15.B33.B33Catalogue
import SemigroupBasis.CoRoots.Order6Day7.LeeZhang.S6_6183Completeness
import SemigroupBasis.CoRoots.Order6Day7.S2_4.SeedS5_240
import SemigroupBasis.CoRoots.Order6Day7.S2_4.SeedS5_245
import SemigroupBasis.CoRoots.Order6Day7.S3_15op.SeedS5_240
import SemigroupBasis.CoRoots.Order6Day7.S3_16.SeedS5_240
import SemigroupBasis.CoRoots.Order6Day9.S3_6.Rank014ClassEndpoints
import SemigroupBasis.CoRoots.Order6LeeLiP2G1Members
import SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_1029_Ad4b303415746_Part01
import SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_1029_Ad4b303415746_Part02
import SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_1231_Ad4b303415746_Part01
import SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_1242_Ad4b303415746_Part01
import SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_6173_Af54f91517da1_Part01
import SemigroupBasis.Generated.Order6DirectPowerAvailableV3Sources.S6_6196
import SemigroupBasis.Generated.Order6DirectPowerAvailableV3Sources.S6_6208
import SemigroupBasis.Generated.Order6DirectPowerAvailableV3Sources.S6_6241
import SemigroupBasis.Generated.Order6DivisorTransfersPart32
import SemigroupBasis.Generated.Order6EmbeddingTransfersPart06
import SemigroupBasis.Generated.Order6FactorIntersectionIdentification.Part01
import SemigroupBasis.Generated.Order6FactorIntersectionIdentification.Part02
import SemigroupBasis.Generated.Order6FactorPairS2_4S5_83DirectTargets
import SemigroupBasis.Generated.Order6FactorPairS3_16S5_83DirectTargets
import SemigroupBasis.Generated.Order6L3RootS4_23S4_90Targets
import SemigroupBasis.Generated.Order6OneLocalFordLastSigma5b78.S6_6246
import SemigroupBasis.Generated.Order6OneLocalFordLastSigma5b78.S6_6269
import SemigroupBasis.Generated.Order6OneLocalFordLastSigma5b78.S6_6282
import SemigroupBasis.Generated.Order6OneLocalFordLastSigma5b78.S6_6284
import SemigroupBasis.Generated.Order6RouteLocalRootAdapters
import research.formalization.order6.extension.order6_extension_2026_06_12_l5_extension_v1.Order6ExtensionTransfersPart06
import research.formalization.order6.extension.order6_extension_2026_06_12_l5_extension_v14.Order6ExtensionTransfersPart02
import research.formalization.order6.extension.order6_extension_2026_06_12_l5_extension_v2.Order6ExtensionTransfersPart02
import research.formalization.order6.extension.order6_extension_2026_06_12_l5_extension_v2.Order6ExtensionTransfersPart03
import research.formalization.order6.extension.order6_extension_2026_06_12_l5_extension_v3.Order6ExtensionTransfersPart02
import research.formalization.order6.extension.order6_extension_2026_06_12_l5_extension_v4.Order6ExtensionTransfersPart02
import research.formalization.order6.extension.order6_extension_2026_06_12_l5_extension_v5.Order6ExtensionTransfersPart02
import research.formalization.order6.extension.order6_extension_2026_06_12_l5_extension_v6.Order6ExtensionTransfersPart03
import research.formalization.order6.extension.order6_extension_2026_06_12_l5_extension_v7.Order6ExtensionTransfersPart02

/-!
# Census shard 042: classes `[6, 6151]` to `[6, 6300]`

For each class, the claim `Classified` from one endpoint theorem of the
development. The first alternative that checks is used: the endpoint for the
semigroup with the catalogue table, or for its opposite (the transposed table).
Generated by `scripts/generate_census.py`.
-/

set_option maxRecDepth 8192

namespace SemiBase.Census

theorem S6_6151 : Classified Catalogue.Order6.S6_6151 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6151.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6151.representative_basis)) (by decide +kernel)

theorem S6_6152 : Classified Catalogue.Order6.S6_6152 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6152.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6152.representative_basis)) (by decide +kernel)

theorem S6_6153 : Classified Catalogue.Order6.S6_6153 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6153.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6153.representative_basis)) (by decide +kernel)

theorem S6_6154 : Classified Catalogue.Order6.S6_6154 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6154.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6154.representative_basis)) (by decide +kernel)

theorem S6_6155 : Classified Catalogue.Order6.S6_6155 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6RouteLocalRootAdapters.S6_6155.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6RouteLocalRootAdapters.S6_6155.representative_basis)) (by decide +kernel)

theorem S6_6156 : Classified Catalogue.Order6.S6_6156 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6156.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6156.representative_basis)) (by decide +kernel)

theorem S6_6157 : Classified Catalogue.Order6.S6_6157 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6RouteLocalRootAdapters.S6_6157.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6RouteLocalRootAdapters.S6_6157.representative_basis)) (by decide +kernel)

theorem S6_6158 : Classified Catalogue.Order6.S6_6158 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6158.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6158.representative_basis)) (by decide +kernel)

theorem S6_6159 : Classified Catalogue.Order6.S6_6159 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6159.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6159.representative_basis)) (by decide +kernel)

theorem S6_6160 : Classified Catalogue.Order6.S6_6160 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6RouteLocalRootAdapters.S6_6160.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6RouteLocalRootAdapters.S6_6160.representative_basis)) (by decide +kernel)

theorem S6_6161 : Classified Catalogue.Order6.S6_6161 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FactorIntersectionIdentification.S6_6161.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FactorIntersectionIdentification.S6_6161.representative_basis)) (by decide +kernel)

theorem S6_6162 : Classified Catalogue.Order6.S6_6162 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6162.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6162.representative_basis)) (by decide +kernel)

theorem S6_6163 : Classified Catalogue.Order6.S6_6163 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FactorIntersectionIdentification.S6_6163.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FactorIntersectionIdentification.S6_6163.representative_basis)) (by decide +kernel)

theorem S6_6164 : Classified Catalogue.Order6.S6_6164 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6164.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6164.representative_basis)) (by decide +kernel)

theorem S6_6165 : Classified Catalogue.Order6.S6_6165 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day7.S2_4.Rank048.Seed.s6_6165_representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day7.S2_4.Rank048.Seed.s6_6165_representative_basis)) (by decide +kernel)

theorem S6_6166 : Classified Catalogue.Order6.S6_6166 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6166.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6166.representative_basis)) (by decide +kernel)

theorem S6_6167 : Classified Catalogue.Order6.S6_6167 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day10.S3_15.Rank048ClassEndpoints.S6_6167.basisFor) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day10.S3_15.Rank048ClassEndpoints.S6_6167.basisFor)) (by decide +kernel)

theorem S6_6168 : Classified Catalogue.Order6.S6_6168 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6168.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6168.representative_basis)) (by decide +kernel)

theorem S6_6169 : Classified Catalogue.Order6.S6_6169 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day7.S3_15op.SeedS5_240.representative_basis_S6_6169) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day7.S3_15op.SeedS5_240.representative_basis_S6_6169)) (by decide +kernel)

theorem S6_6170 : Classified Catalogue.Order6.S6_6170 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6170.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6170.representative_basis)) (by decide +kernel)

theorem S6_6171 : Classified Catalogue.Order6.S6_6171 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day7.S3_16.Rank087.Seed.s6_6171_representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day7.S3_16.Rank087.Seed.s6_6171_representative_basis)) (by decide +kernel)

theorem S6_6172 : Classified Catalogue.Order6.S6_6172 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6LeeLiP2G1.Members.S6_6172.basisFor) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6LeeLiP2G1.Members.S6_6172.basisFor)) (by decide +kernel)

theorem S6_6173 : Classified Catalogue.Order6.S6_6173 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6RouteLocalRootAdapters.S6_6173.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6RouteLocalRootAdapters.S6_6173.representative_basis)) (by decide +kernel)

theorem S6_6174 : Classified Catalogue.Order6.S6_6174 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FactorIntersectionIdentification.S6_6174.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FactorIntersectionIdentification.S6_6174.representative_basis)) (by decide +kernel)

theorem S6_6175 : Classified Catalogue.Order6.S6_6175 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FactorPairS2_4S5_83DirectTargets.S6_6175.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FactorPairS2_4S5_83DirectTargets.S6_6175.representative_basis)) (by decide +kernel)

theorem S6_6176 : Classified Catalogue.Order6.S6_6176 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FactorPairS2_4S5_83DirectTargets.S6_6176.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FactorPairS2_4S5_83DirectTargets.S6_6176.representative_basis)) (by decide +kernel)

theorem S6_6177 : Classified Catalogue.Order6.S6_6177 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FactorPairS3_16S5_83DirectTargets.S6_6177.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FactorPairS3_16S5_83DirectTargets.S6_6177.representative_basis)) (by decide +kernel)

theorem S6_6178 : Classified Catalogue.Order6.S6_6178 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_6173_Af54f91517da1_Part01.S6_6178.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_6173_Af54f91517da1_Part01.S6_6178.representative_basis)) (by decide +kernel)

theorem S6_6179 : Classified Catalogue.Order6.S6_6179 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6179.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6179.representative_basis)) (by decide +kernel)

theorem S6_6180 : Classified Catalogue.Order6.S6_6180 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6LeeLiP2G1.Members.S6_6180.basisFor) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6LeeLiP2G1.Members.S6_6180.basisFor)) (by decide +kernel)

theorem S6_6181 : Classified Catalogue.Order6.S6_6181 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6RouteLocalRootAdapters.S6_6181.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6RouteLocalRootAdapters.S6_6181.representative_basis)) (by decide +kernel)

theorem S6_6182 : Classified Catalogue.Order6.S6_6182 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV6.S6_6182.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV6.S6_6182.representative_basis)) (by decide +kernel)

theorem S6_6183 : Classified Catalogue.Order6.S6_6183 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day7.LeeZhang.S6_6183.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day7.LeeZhang.S6_6183.representative_basis)) (by decide +kernel)

theorem S6_6184 : Classified Catalogue.Order6.S6_6184 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6184.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6184.representative_basis)) (by decide +kernel)

theorem S6_6185 : Classified Catalogue.Order6.S6_6185 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6185.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6185.representative_basis)) (by decide +kernel)

theorem S6_6186 : Classified Catalogue.Order6.S6_6186 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6186.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6186.representative_basis)) (by decide +kernel)

theorem S6_6187 : Classified Catalogue.Order6.S6_6187 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6LeeLiP2G1.Members.S6_6187.basisFor) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6LeeLiP2G1.Members.S6_6187.basisFor)) (by decide +kernel)

theorem S6_6188 : Classified Catalogue.Order6.S6_6188 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6LeeLiP2G1.Members.S6_6188.basisFor) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6LeeLiP2G1.Members.S6_6188.basisFor)) (by decide +kernel)

theorem S6_6189 : Classified Catalogue.Order6.S6_6189 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6189.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6189.representative_basis)) (by decide +kernel)

theorem S6_6190 : Classified Catalogue.Order6.S6_6190 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6190.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6190.representative_basis)) (by decide +kernel)

theorem S6_6191 : Classified Catalogue.Order6.S6_6191 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6191.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6191.representative_basis)) (by decide +kernel)

theorem S6_6192 : Classified Catalogue.Order6.S6_6192 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_6192.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_6192.representative_basis)) (by decide +kernel)

theorem S6_6193 : Classified Catalogue.Order6.S6_6193 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_6193.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_6193.representative_basis)) (by decide +kernel)

theorem S6_6194 : Classified Catalogue.Order6.S6_6194 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6194.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6194.representative_basis)) (by decide +kernel)

theorem S6_6195 : Classified Catalogue.Order6.S6_6195 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6195.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6195.representative_basis)) (by decide +kernel)

theorem S6_6196 : Classified Catalogue.Order6.S6_6196 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3Sources.S6_6196.basis_complete) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3Sources.S6_6196.basis_complete)) (by decide +kernel)

theorem S6_6197 : Classified Catalogue.Order6.S6_6197 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6197.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6197.representative_basis)) (by decide +kernel)

theorem S6_6198 : Classified Catalogue.Order6.S6_6198 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6198.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6198.representative_basis)) (by decide +kernel)

theorem S6_6199 : Classified Catalogue.Order6.S6_6199 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_6199.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_6199.representative_basis)) (by decide +kernel)

theorem S6_6200 : Classified Catalogue.Order6.S6_6200 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV7.S6_6200.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV7.S6_6200.representative_basis)) (by decide +kernel)

theorem S6_6201 : Classified Catalogue.Order6.S6_6201 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV7.S6_6201.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV7.S6_6201.representative_basis)) (by decide +kernel)

theorem S6_6202 : Classified Catalogue.Order6.S6_6202 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_6202.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_6202.representative_basis)) (by decide +kernel)

theorem S6_6203 : Classified Catalogue.Order6.S6_6203 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_6203.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_6203.representative_basis)) (by decide +kernel)

theorem S6_6204 : Classified Catalogue.Order6.S6_6204 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV5.S6_6204.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV5.S6_6204.representative_basis)) (by decide +kernel)

theorem S6_6205 : Classified Catalogue.Order6.S6_6205 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_6205.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_6205.representative_basis)) (by decide +kernel)

theorem S6_6206 : Classified Catalogue.Order6.S6_6206 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6206.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6206.representative_basis)) (by decide +kernel)

theorem S6_6207 : Classified Catalogue.Order6.S6_6207 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_1231_Ad4b303415746_Part01.S6_6207.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_1231_Ad4b303415746_Part01.S6_6207.representative_basis)) (by decide +kernel)

theorem S6_6208 : Classified Catalogue.Order6.S6_6208 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3Sources.S6_6208.basis_complete) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3Sources.S6_6208.basis_complete)) (by decide +kernel)

theorem S6_6209 : Classified Catalogue.Order6.S6_6209 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6209.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6209.representative_basis)) (by decide +kernel)

theorem S6_6210 : Classified Catalogue.Order6.S6_6210 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6210.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6210.representative_basis)) (by decide +kernel)

theorem S6_6211 : Classified Catalogue.Order6.S6_6211 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6211.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6211.representative_basis)) (by decide +kernel)

theorem S6_6212 : Classified Catalogue.Order6.S6_6212 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV14.S6_6212.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV14.S6_6212.representative_basis)) (by decide +kernel)

theorem S6_6213 : Classified Catalogue.Order6.S6_6213 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6213.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6213.representative_basis)) (by decide +kernel)

theorem S6_6214 : Classified Catalogue.Order6.S6_6214 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6214.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6214.representative_basis)) (by decide +kernel)

theorem S6_6215 : Classified Catalogue.Order6.S6_6215 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6215.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6215.representative_basis)) (by decide +kernel)

theorem S6_6216 : Classified Catalogue.Order6.S6_6216 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV14.S6_6216.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV14.S6_6216.representative_basis)) (by decide +kernel)

theorem S6_6217 : Classified Catalogue.Order6.S6_6217 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV14.S6_6217.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV14.S6_6217.representative_basis)) (by decide +kernel)

theorem S6_6218 : Classified Catalogue.Order6.S6_6218 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6218.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6218.representative_basis)) (by decide +kernel)

theorem S6_6219 : Classified Catalogue.Order6.S6_6219 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6219.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6219.representative_basis)) (by decide +kernel)

theorem S6_6220 : Classified Catalogue.Order6.S6_6220 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6220.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6220.representative_basis)) (by decide +kernel)

theorem S6_6221 : Classified Catalogue.Order6.S6_6221 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6221.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6221.representative_basis)) (by decide +kernel)

theorem S6_6222 : Classified Catalogue.Order6.S6_6222 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day7.S2_4.Rank049.Seed.s6_6222_representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day7.S2_4.Rank049.Seed.s6_6222_representative_basis)) (by decide +kernel)

theorem S6_6223 : Classified Catalogue.Order6.S6_6223 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6223.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6223.representative_basis)) (by decide +kernel)

theorem S6_6224 : Classified Catalogue.Order6.S6_6224 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6224.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6224.representative_basis)) (by decide +kernel)

theorem S6_6225 : Classified Catalogue.Order6.S6_6225 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day15.B33.Catalogue.basisFor6225) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day15.B33.Catalogue.basisFor6225)) (by decide +kernel)

theorem S6_6226 : Classified Catalogue.Order6.S6_6226 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV6.S6_6226.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV6.S6_6226.representative_basis)) (by decide +kernel)

theorem S6_6227 : Classified Catalogue.Order6.S6_6227 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6227.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6227.representative_basis)) (by decide +kernel)

theorem S6_6228 : Classified Catalogue.Order6.S6_6228 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV6.S6_6228.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV6.S6_6228.representative_basis)) (by decide +kernel)

theorem S6_6229 : Classified Catalogue.Order6.S6_6229 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV5.S6_6229.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV5.S6_6229.representative_basis)) (by decide +kernel)

theorem S6_6230 : Classified Catalogue.Order6.S6_6230 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV6.S6_6230.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV6.S6_6230.representative_basis)) (by decide +kernel)

theorem S6_6231 : Classified Catalogue.Order6.S6_6231 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV5.S6_6231.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV5.S6_6231.representative_basis)) (by decide +kernel)

theorem S6_6232 : Classified Catalogue.Order6.S6_6232 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6232.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6232.representative_basis)) (by decide +kernel)

theorem S6_6233 : Classified Catalogue.Order6.S6_6233 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6233.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6233.representative_basis)) (by decide +kernel)

theorem S6_6234 : Classified Catalogue.Order6.S6_6234 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6L3RootS4_23S4_90Targets.S6_6234.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6L3RootS4_23S4_90Targets.S6_6234.representative_basis)) (by decide +kernel)

theorem S6_6235 : Classified Catalogue.Order6.S6_6235 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6235.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6235.representative_basis)) (by decide +kernel)

theorem S6_6236 : Classified Catalogue.Order6.S6_6236 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6236.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6236.representative_basis)) (by decide +kernel)

theorem S6_6237 : Classified Catalogue.Order6.S6_6237 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6237.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6237.representative_basis)) (by decide +kernel)

theorem S6_6238 : Classified Catalogue.Order6.S6_6238 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6238.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6238.representative_basis)) (by decide +kernel)

theorem S6_6239 : Classified Catalogue.Order6.S6_6239 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day9.S3_6.Rank014ClassEndpoints.S6_6239.basisFor) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day9.S3_6.Rank014ClassEndpoints.S6_6239.basisFor)) (by decide +kernel)

theorem S6_6240 : Classified Catalogue.Order6.S6_6240 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV3.S6_6240.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV3.S6_6240.representative_basis)) (by decide +kernel)

theorem S6_6241 : Classified Catalogue.Order6.S6_6241 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3Sources.S6_6241.basis_complete) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3Sources.S6_6241.basis_complete)) (by decide +kernel)

theorem S6_6242 : Classified Catalogue.Order6.S6_6242 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6242.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6242.representative_basis)) (by decide +kernel)

theorem S6_6243 : Classified Catalogue.Order6.S6_6243 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6243.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6243.representative_basis)) (by decide +kernel)

theorem S6_6244 : Classified Catalogue.Order6.S6_6244 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6244.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6244.representative_basis)) (by decide +kernel)

theorem S6_6245 : Classified Catalogue.Order6.S6_6245 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6245.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6245.representative_basis)) (by decide +kernel)

theorem S6_6246 : Classified Catalogue.Order6.S6_6246 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6OneLocalFordLastSigma5b78.S6_6246.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6OneLocalFordLastSigma5b78.S6_6246.representative_basis)) (by decide +kernel)

theorem S6_6247 : Classified Catalogue.Order6.S6_6247 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_6247.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_6247.representative_basis)) (by decide +kernel)

theorem S6_6248 : Classified Catalogue.Order6.S6_6248 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV7.S6_6248.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV7.S6_6248.representative_basis)) (by decide +kernel)

theorem S6_6249 : Classified Catalogue.Order6.S6_6249 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_6249.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_6249.representative_basis)) (by decide +kernel)

theorem S6_6250 : Classified Catalogue.Order6.S6_6250 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV6.S6_6250.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV6.S6_6250.representative_basis)) (by decide +kernel)

theorem S6_6251 : Classified Catalogue.Order6.S6_6251 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV6.S6_6251.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV6.S6_6251.representative_basis)) (by decide +kernel)

theorem S6_6252 : Classified Catalogue.Order6.S6_6252 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_6252.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_6252.representative_basis)) (by decide +kernel)

theorem S6_6253 : Classified Catalogue.Order6.S6_6253 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_1029_Ad4b303415746_Part01.S6_6253.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_1029_Ad4b303415746_Part01.S6_6253.representative_basis)) (by decide +kernel)

theorem S6_6254 : Classified Catalogue.Order6.S6_6254 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV6.S6_6254.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV6.S6_6254.representative_basis)) (by decide +kernel)

theorem S6_6255 : Classified Catalogue.Order6.S6_6255 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_6255.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_6255.representative_basis)) (by decide +kernel)

theorem S6_6256 : Classified Catalogue.Order6.S6_6256 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6256.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6256.representative_basis)) (by decide +kernel)

theorem S6_6257 : Classified Catalogue.Order6.S6_6257 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_1231_Ad4b303415746_Part01.S6_6257.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_1231_Ad4b303415746_Part01.S6_6257.representative_basis)) (by decide +kernel)

theorem S6_6258 : Classified Catalogue.Order6.S6_6258 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6258.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6258.representative_basis)) (by decide +kernel)

theorem S6_6259 : Classified Catalogue.Order6.S6_6259 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV14.S6_6259.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV14.S6_6259.representative_basis)) (by decide +kernel)

theorem S6_6260 : Classified Catalogue.Order6.S6_6260 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV14.S6_6260.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV14.S6_6260.representative_basis)) (by decide +kernel)

theorem S6_6261 : Classified Catalogue.Order6.S6_6261 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6261.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6261.representative_basis)) (by decide +kernel)

theorem S6_6262 : Classified Catalogue.Order6.S6_6262 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6262.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6262.representative_basis)) (by decide +kernel)

theorem S6_6263 : Classified Catalogue.Order6.S6_6263 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6263.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6263.representative_basis)) (by decide +kernel)

theorem S6_6264 : Classified Catalogue.Order6.S6_6264 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_1029_Ad4b303415746_Part01.S6_6264.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_1029_Ad4b303415746_Part01.S6_6264.representative_basis)) (by decide +kernel)

theorem S6_6265 : Classified Catalogue.Order6.S6_6265 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6265.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6265.representative_basis)) (by decide +kernel)

theorem S6_6266 : Classified Catalogue.Order6.S6_6266 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6266.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6266.representative_basis)) (by decide +kernel)

theorem S6_6267 : Classified Catalogue.Order6.S6_6267 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV14.S6_6267.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV14.S6_6267.representative_basis)) (by decide +kernel)

theorem S6_6268 : Classified Catalogue.Order6.S6_6268 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6268.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6268.representative_basis)) (by decide +kernel)

theorem S6_6269 : Classified Catalogue.Order6.S6_6269 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6OneLocalFordLastSigma5b78.S6_6269.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6OneLocalFordLastSigma5b78.S6_6269.representative_basis)) (by decide +kernel)

theorem S6_6270 : Classified Catalogue.Order6.S6_6270 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6270.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6270.representative_basis)) (by decide +kernel)

theorem S6_6271 : Classified Catalogue.Order6.S6_6271 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV6.S6_6271.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV6.S6_6271.representative_basis)) (by decide +kernel)

theorem S6_6272 : Classified Catalogue.Order6.S6_6272 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV6.S6_6272.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV6.S6_6272.representative_basis)) (by decide +kernel)

theorem S6_6273 : Classified Catalogue.Order6.S6_6273 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6273.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6273.representative_basis)) (by decide +kernel)

theorem S6_6274 : Classified Catalogue.Order6.S6_6274 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_1029_Ad4b303415746_Part02.S6_6274.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_1029_Ad4b303415746_Part02.S6_6274.representative_basis)) (by decide +kernel)

theorem S6_6275 : Classified Catalogue.Order6.S6_6275 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV6.S6_6275.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV6.S6_6275.representative_basis)) (by decide +kernel)

theorem S6_6276 : Classified Catalogue.Order6.S6_6276 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6276.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6276.representative_basis)) (by decide +kernel)

theorem S6_6277 : Classified Catalogue.Order6.S6_6277 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV6.S6_6277.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV6.S6_6277.representative_basis)) (by decide +kernel)

theorem S6_6278 : Classified Catalogue.Order6.S6_6278 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6278.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6278.representative_basis)) (by decide +kernel)

theorem S6_6279 : Classified Catalogue.Order6.S6_6279 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_6279.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_6279.representative_basis)) (by decide +kernel)

theorem S6_6280 : Classified Catalogue.Order6.S6_6280 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV6.S6_6280.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV6.S6_6280.representative_basis)) (by decide +kernel)

theorem S6_6281 : Classified Catalogue.Order6.S6_6281 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6281.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6281.representative_basis)) (by decide +kernel)

theorem S6_6282 : Classified Catalogue.Order6.S6_6282 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6OneLocalFordLastSigma5b78.S6_6282.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6OneLocalFordLastSigma5b78.S6_6282.representative_basis)) (by decide +kernel)

theorem S6_6283 : Classified Catalogue.Order6.S6_6283 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6283.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6283.representative_basis)) (by decide +kernel)

theorem S6_6284 : Classified Catalogue.Order6.S6_6284 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6OneLocalFordLastSigma5b78.S6_6284.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6OneLocalFordLastSigma5b78.S6_6284.representative_basis)) (by decide +kernel)

theorem S6_6285 : Classified Catalogue.Order6.S6_6285 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6285.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6285.representative_basis)) (by decide +kernel)

theorem S6_6286 : Classified Catalogue.Order6.S6_6286 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6286.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6286.representative_basis)) (by decide +kernel)

theorem S6_6287 : Classified Catalogue.Order6.S6_6287 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_6287.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_6287.representative_basis)) (by decide +kernel)

theorem S6_6288 : Classified Catalogue.Order6.S6_6288 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6288.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6288.representative_basis)) (by decide +kernel)

theorem S6_6289 : Classified Catalogue.Order6.S6_6289 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_6289.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_6289.representative_basis)) (by decide +kernel)

theorem S6_6290 : Classified Catalogue.Order6.S6_6290 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6290.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6290.representative_basis)) (by decide +kernel)

theorem S6_6291 : Classified Catalogue.Order6.S6_6291 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6291.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6291.representative_basis)) (by decide +kernel)

theorem S6_6292 : Classified Catalogue.Order6.S6_6292 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_6292.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_6292.representative_basis)) (by decide +kernel)

theorem S6_6293 : Classified Catalogue.Order6.S6_6293 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV6.S6_6293.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV6.S6_6293.representative_basis)) (by decide +kernel)

theorem S6_6294 : Classified Catalogue.Order6.S6_6294 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6294.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6294.representative_basis)) (by decide +kernel)

theorem S6_6295 : Classified Catalogue.Order6.S6_6295 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV6.S6_6295.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV6.S6_6295.representative_basis)) (by decide +kernel)

theorem S6_6296 : Classified Catalogue.Order6.S6_6296 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_6296.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_6296.representative_basis)) (by decide +kernel)

theorem S6_6297 : Classified Catalogue.Order6.S6_6297 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6297.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6297.representative_basis)) (by decide +kernel)

theorem S6_6298 : Classified Catalogue.Order6.S6_6298 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV6.S6_6298.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV6.S6_6298.representative_basis)) (by decide +kernel)

theorem S6_6299 : Classified Catalogue.Order6.S6_6299 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV4.S6_6299.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV4.S6_6299.representative_basis)) (by decide +kernel)

theorem S6_6300 : Classified Catalogue.Order6.S6_6300 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_1242_Ad4b303415746_Part01.S6_6300.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_1242_Ad4b303415746_Part01.S6_6300.representative_basis)) (by decide +kernel)

/-- Every class of part 042 of the catalogue is classified. -/
theorem shard042 : AllClassified Catalogue.Order6.part042 :=
  AllClassified.cons S6_6151 <|
  AllClassified.cons S6_6152 <|
  AllClassified.cons S6_6153 <|
  AllClassified.cons S6_6154 <|
  AllClassified.cons S6_6155 <|
  AllClassified.cons S6_6156 <|
  AllClassified.cons S6_6157 <|
  AllClassified.cons S6_6158 <|
  AllClassified.cons S6_6159 <|
  AllClassified.cons S6_6160 <|
  AllClassified.cons S6_6161 <|
  AllClassified.cons S6_6162 <|
  AllClassified.cons S6_6163 <|
  AllClassified.cons S6_6164 <|
  AllClassified.cons S6_6165 <|
  AllClassified.cons S6_6166 <|
  AllClassified.cons S6_6167 <|
  AllClassified.cons S6_6168 <|
  AllClassified.cons S6_6169 <|
  AllClassified.cons S6_6170 <|
  AllClassified.cons S6_6171 <|
  AllClassified.cons S6_6172 <|
  AllClassified.cons S6_6173 <|
  AllClassified.cons S6_6174 <|
  AllClassified.cons S6_6175 <|
  AllClassified.cons S6_6176 <|
  AllClassified.cons S6_6177 <|
  AllClassified.cons S6_6178 <|
  AllClassified.cons S6_6179 <|
  AllClassified.cons S6_6180 <|
  AllClassified.cons S6_6181 <|
  AllClassified.cons S6_6182 <|
  AllClassified.cons S6_6183 <|
  AllClassified.cons S6_6184 <|
  AllClassified.cons S6_6185 <|
  AllClassified.cons S6_6186 <|
  AllClassified.cons S6_6187 <|
  AllClassified.cons S6_6188 <|
  AllClassified.cons S6_6189 <|
  AllClassified.cons S6_6190 <|
  AllClassified.cons S6_6191 <|
  AllClassified.cons S6_6192 <|
  AllClassified.cons S6_6193 <|
  AllClassified.cons S6_6194 <|
  AllClassified.cons S6_6195 <|
  AllClassified.cons S6_6196 <|
  AllClassified.cons S6_6197 <|
  AllClassified.cons S6_6198 <|
  AllClassified.cons S6_6199 <|
  AllClassified.cons S6_6200 <|
  AllClassified.cons S6_6201 <|
  AllClassified.cons S6_6202 <|
  AllClassified.cons S6_6203 <|
  AllClassified.cons S6_6204 <|
  AllClassified.cons S6_6205 <|
  AllClassified.cons S6_6206 <|
  AllClassified.cons S6_6207 <|
  AllClassified.cons S6_6208 <|
  AllClassified.cons S6_6209 <|
  AllClassified.cons S6_6210 <|
  AllClassified.cons S6_6211 <|
  AllClassified.cons S6_6212 <|
  AllClassified.cons S6_6213 <|
  AllClassified.cons S6_6214 <|
  AllClassified.cons S6_6215 <|
  AllClassified.cons S6_6216 <|
  AllClassified.cons S6_6217 <|
  AllClassified.cons S6_6218 <|
  AllClassified.cons S6_6219 <|
  AllClassified.cons S6_6220 <|
  AllClassified.cons S6_6221 <|
  AllClassified.cons S6_6222 <|
  AllClassified.cons S6_6223 <|
  AllClassified.cons S6_6224 <|
  AllClassified.cons S6_6225 <|
  AllClassified.cons S6_6226 <|
  AllClassified.cons S6_6227 <|
  AllClassified.cons S6_6228 <|
  AllClassified.cons S6_6229 <|
  AllClassified.cons S6_6230 <|
  AllClassified.cons S6_6231 <|
  AllClassified.cons S6_6232 <|
  AllClassified.cons S6_6233 <|
  AllClassified.cons S6_6234 <|
  AllClassified.cons S6_6235 <|
  AllClassified.cons S6_6236 <|
  AllClassified.cons S6_6237 <|
  AllClassified.cons S6_6238 <|
  AllClassified.cons S6_6239 <|
  AllClassified.cons S6_6240 <|
  AllClassified.cons S6_6241 <|
  AllClassified.cons S6_6242 <|
  AllClassified.cons S6_6243 <|
  AllClassified.cons S6_6244 <|
  AllClassified.cons S6_6245 <|
  AllClassified.cons S6_6246 <|
  AllClassified.cons S6_6247 <|
  AllClassified.cons S6_6248 <|
  AllClassified.cons S6_6249 <|
  AllClassified.cons S6_6250 <|
  AllClassified.cons S6_6251 <|
  AllClassified.cons S6_6252 <|
  AllClassified.cons S6_6253 <|
  AllClassified.cons S6_6254 <|
  AllClassified.cons S6_6255 <|
  AllClassified.cons S6_6256 <|
  AllClassified.cons S6_6257 <|
  AllClassified.cons S6_6258 <|
  AllClassified.cons S6_6259 <|
  AllClassified.cons S6_6260 <|
  AllClassified.cons S6_6261 <|
  AllClassified.cons S6_6262 <|
  AllClassified.cons S6_6263 <|
  AllClassified.cons S6_6264 <|
  AllClassified.cons S6_6265 <|
  AllClassified.cons S6_6266 <|
  AllClassified.cons S6_6267 <|
  AllClassified.cons S6_6268 <|
  AllClassified.cons S6_6269 <|
  AllClassified.cons S6_6270 <|
  AllClassified.cons S6_6271 <|
  AllClassified.cons S6_6272 <|
  AllClassified.cons S6_6273 <|
  AllClassified.cons S6_6274 <|
  AllClassified.cons S6_6275 <|
  AllClassified.cons S6_6276 <|
  AllClassified.cons S6_6277 <|
  AllClassified.cons S6_6278 <|
  AllClassified.cons S6_6279 <|
  AllClassified.cons S6_6280 <|
  AllClassified.cons S6_6281 <|
  AllClassified.cons S6_6282 <|
  AllClassified.cons S6_6283 <|
  AllClassified.cons S6_6284 <|
  AllClassified.cons S6_6285 <|
  AllClassified.cons S6_6286 <|
  AllClassified.cons S6_6287 <|
  AllClassified.cons S6_6288 <|
  AllClassified.cons S6_6289 <|
  AllClassified.cons S6_6290 <|
  AllClassified.cons S6_6291 <|
  AllClassified.cons S6_6292 <|
  AllClassified.cons S6_6293 <|
  AllClassified.cons S6_6294 <|
  AllClassified.cons S6_6295 <|
  AllClassified.cons S6_6296 <|
  AllClassified.cons S6_6297 <|
  AllClassified.cons S6_6298 <|
  AllClassified.cons S6_6299 <|
  AllClassified.cons S6_6300 <|
  AllClassified.nil

end SemiBase.Census
