import SemiBase.Statement
import SemiBase.Catalogue.Order6.Part107
import Order6FinalL5TransferV3.Part356
import Order6FinalL5TransferV3.Part357
import Order6FinalL5TransferV3.Part358
import Order6FinalL5TransferV3.Part359
import SemigroupBasis.CoRoots.Order6Day14.S15931.S15931Completeness
import SemigroupBasis.CoRoots.Order6Day7.S2_4.SeedS3_18
import SemigroupBasis.CoRoots.Order6Day9.S3_18.Rank005ClassEndpoints
import SemigroupBasis.CoRoots.Order6Day9.S3_18.Rank006ClassEndpoints
import SemigroupBasis.CoRoots.Order6GenericCASMonoidPower
import SemigroupBasis.Generated.Order6CASExplicitSourceRouteTailV3.S6_15942
import SemigroupBasis.Generated.Order6CASExplicitSourceRouteTailV3.S6_15944
import SemigroupBasis.Generated.Order6CASExplicitSourceRouteTailV3.S6_15952
import SemigroupBasis.Generated.Order6FactorPairS3_18S4_20Targets
import SemigroupBasis.Generated.Order6FinalL5UnlockedWrappersV3.S6_15912
import SemigroupBasis.Generated.Order6GenericCASRootWrappers.S6_15954
import SemigroupBasis.Generated.Order6GenericCASRootWrappers.S6_15955
import SemigroupBasis.Generated.Order6GenericCASRootWrappers.S6_15956
import SemigroupBasis.Generated.Order6GenericCASRootWrappers.S6_15961
import SemigroupBasis.Generated.Order6GenericCASRootWrappers.S6_15965
import SemigroupBasis.Generated.Order6GenericInflationV3.Family03
import SemigroupBasis.Generated.Order6GenericInflationV3.Family04
import SemigroupBasis.Generated.Order6HeadSortedFactorTargets
import SemigroupBasis.Generated.Order6L3RootS3_18TargetsS4_2
import SemigroupBasis.Generated.Order6L3RootS3_18TargetsS4_9
import SemigroupBasis.Generated.Order6OverlookedExisting63FanoutV1.S6_15951
import SemigroupBasis.Generated.Order6RouteLocalRootAdapters

/-!
# Census shard 107: classes `[6, 15901]` to `[6, 15973]`

For each class, the claim `Classified` from one endpoint theorem of the
development. The first alternative that checks is used: the endpoint for the
semigroup with the catalogue table, or for its opposite (the transposed table).
Generated by `scripts/generate_census.py`.
-/

set_option maxRecDepth 8192

namespace SemiBase.Census

theorem S6_15901 : Classified Catalogue.Order6.S6_15901 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15901.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15901.representative_basis)) (by decide +kernel)

theorem S6_15902 : Classified Catalogue.Order6.S6_15902 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15902.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15902.representative_basis)) (by decide +kernel)

theorem S6_15903 : Classified Catalogue.Order6.S6_15903 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6RouteLocalRootAdapters.S6_15903.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6RouteLocalRootAdapters.S6_15903.representative_basis)) (by decide +kernel)

theorem S6_15904 : Classified Catalogue.Order6.S6_15904 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15904.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15904.representative_basis)) (by decide +kernel)

theorem S6_15905 : Classified Catalogue.Order6.S6_15905 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15905.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15905.representative_basis)) (by decide +kernel)

theorem S6_15906 : Classified Catalogue.Order6.S6_15906 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15906.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15906.representative_basis)) (by decide +kernel)

theorem S6_15907 : Classified Catalogue.Order6.S6_15907 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15907.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15907.representative_basis)) (by decide +kernel)

theorem S6_15908 : Classified Catalogue.Order6.S6_15908 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15908.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15908.representative_basis)) (by decide +kernel)

theorem S6_15909 : Classified Catalogue.Order6.S6_15909 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15909.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15909.representative_basis)) (by decide +kernel)

theorem S6_15910 : Classified Catalogue.Order6.S6_15910 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15910.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15910.representative_basis)) (by decide +kernel)

theorem S6_15911 : Classified Catalogue.Order6.S6_15911 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15911.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15911.representative_basis)) (by decide +kernel)

theorem S6_15912 : Classified Catalogue.Order6.S6_15912 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5UnlockedWrappersV3.S6_15912.opposite_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5UnlockedWrappersV3.S6_15912.opposite_basis)) (by decide +kernel)

theorem S6_15913 : Classified Catalogue.Order6.S6_15913 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15913.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15913.representative_basis)) (by decide +kernel)

theorem S6_15914 : Classified Catalogue.Order6.S6_15914 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15914.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15914.representative_basis)) (by decide +kernel)

theorem S6_15915 : Classified Catalogue.Order6.S6_15915 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6GenericInflationV3.Family04.S6_15915.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6GenericInflationV3.Family04.S6_15915.representative_basis)) (by decide +kernel)

theorem S6_15916 : Classified Catalogue.Order6.S6_15916 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15916.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15916.representative_basis)) (by decide +kernel)

theorem S6_15917 : Classified Catalogue.Order6.S6_15917 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15917.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15917.representative_basis)) (by decide +kernel)

theorem S6_15918 : Classified Catalogue.Order6.S6_15918 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15918.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15918.representative_basis)) (by decide +kernel)

theorem S6_15919 : Classified Catalogue.Order6.S6_15919 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15919.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15919.representative_basis)) (by decide +kernel)

theorem S6_15920 : Classified Catalogue.Order6.S6_15920 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6GenericInflationV3.Family03.S6_15920.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6GenericInflationV3.Family03.S6_15920.representative_basis)) (by decide +kernel)

theorem S6_15921 : Classified Catalogue.Order6.S6_15921 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15921.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15921.representative_basis)) (by decide +kernel)

theorem S6_15922 : Classified Catalogue.Order6.S6_15922 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15922.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15922.representative_basis)) (by decide +kernel)

theorem S6_15923 : Classified Catalogue.Order6.S6_15923 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15923.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15923.representative_basis)) (by decide +kernel)

theorem S6_15924 : Classified Catalogue.Order6.S6_15924 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day9.S3_18.Rank006ClassEndpoints.S6_15924.basisFor) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day9.S3_18.Rank006ClassEndpoints.S6_15924.basisFor)) (by decide +kernel)

theorem S6_15925 : Classified Catalogue.Order6.S6_15925 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15925.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15925.representative_basis)) (by decide +kernel)

theorem S6_15926 : Classified Catalogue.Order6.S6_15926 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15926.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15926.representative_basis)) (by decide +kernel)

theorem S6_15927 : Classified Catalogue.Order6.S6_15927 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15927.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15927.representative_basis)) (by decide +kernel)

theorem S6_15928 : Classified Catalogue.Order6.S6_15928 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15928.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15928.representative_basis)) (by decide +kernel)

theorem S6_15929 : Classified Catalogue.Order6.S6_15929 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6RouteLocalRootAdapters.S6_15929.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6RouteLocalRootAdapters.S6_15929.representative_basis)) (by decide +kernel)

theorem S6_15930 : Classified Catalogue.Order6.S6_15930 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6GenericInflationV3.Family04.S6_15930.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6GenericInflationV3.Family04.S6_15930.representative_basis)) (by decide +kernel)

theorem S6_15931 : Classified Catalogue.Order6.S6_15931 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day14.S15931.isBasisFor_15931_direct) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day14.S15931.isBasisFor_15931_direct)) (by decide +kernel)

theorem S6_15932 : Classified Catalogue.Order6.S6_15932 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15932.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15932.representative_basis)) (by decide +kernel)

theorem S6_15933 : Classified Catalogue.Order6.S6_15933 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day9.S3_18.Rank005ClassEndpoints.S6_15933.basisFor) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day9.S3_18.Rank005ClassEndpoints.S6_15933.basisFor)) (by decide +kernel)

theorem S6_15934 : Classified Catalogue.Order6.S6_15934 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6HeadSortedFactorTargets.S6_15934.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6HeadSortedFactorTargets.S6_15934.representative_basis)) (by decide +kernel)

theorem S6_15935 : Classified Catalogue.Order6.S6_15935 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15935.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15935.representative_basis)) (by decide +kernel)

theorem S6_15936 : Classified Catalogue.Order6.S6_15936 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15936.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15936.representative_basis)) (by decide +kernel)

theorem S6_15937 : Classified Catalogue.Order6.S6_15937 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15937.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15937.representative_basis)) (by decide +kernel)

theorem S6_15938 : Classified Catalogue.Order6.S6_15938 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15938.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15938.representative_basis)) (by decide +kernel)

theorem S6_15939 : Classified Catalogue.Order6.S6_15939 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15939.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15939.representative_basis)) (by decide +kernel)

theorem S6_15940 : Classified Catalogue.Order6.S6_15940 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15940.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15940.representative_basis)) (by decide +kernel)

theorem S6_15941 : Classified Catalogue.Order6.S6_15941 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FactorPairS3_18S4_20Targets.S6_15941.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FactorPairS3_18S4_20Targets.S6_15941.representative_basis)) (by decide +kernel)

theorem S6_15942 : Classified Catalogue.Order6.S6_15942 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6CASExplicitSourceRouteTailV3.S6_15942.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6CASExplicitSourceRouteTailV3.S6_15942.representative_basis)) (by decide +kernel)

theorem S6_15943 : Classified Catalogue.Order6.S6_15943 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15943.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15943.representative_basis)) (by decide +kernel)

theorem S6_15944 : Classified Catalogue.Order6.S6_15944 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6CASExplicitSourceRouteTailV3.S6_15944.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6CASExplicitSourceRouteTailV3.S6_15944.representative_basis)) (by decide +kernel)

theorem S6_15945 : Classified Catalogue.Order6.S6_15945 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15945.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15945.representative_basis)) (by decide +kernel)

theorem S6_15946 : Classified Catalogue.Order6.S6_15946 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15946.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15946.representative_basis)) (by decide +kernel)

theorem S6_15947 : Classified Catalogue.Order6.S6_15947 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15947.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15947.representative_basis)) (by decide +kernel)

theorem S6_15948 : Classified Catalogue.Order6.S6_15948 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15948.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15948.representative_basis)) (by decide +kernel)

theorem S6_15949 : Classified Catalogue.Order6.S6_15949 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15949.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15949.representative_basis)) (by decide +kernel)

theorem S6_15950 : Classified Catalogue.Order6.S6_15950 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15950.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15950.representative_basis)) (by decide +kernel)

theorem S6_15951 : Classified Catalogue.Order6.S6_15951 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6OverlookedExisting63FanoutV1.S6_15951.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6OverlookedExisting63FanoutV1.S6_15951.representative_basis)) (by decide +kernel)

theorem S6_15952 : Classified Catalogue.Order6.S6_15952 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6CASExplicitSourceRouteTailV3.S6_15952.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6CASExplicitSourceRouteTailV3.S6_15952.representative_basis)) (by decide +kernel)

theorem S6_15953 : Classified Catalogue.Order6.S6_15953 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15953.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15953.representative_basis)) (by decide +kernel)

theorem S6_15954 : Classified Catalogue.Order6.S6_15954 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6GenericCASRootWrappers.S6_15954.opposite_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6GenericCASRootWrappers.S6_15954.opposite_basis)) (by decide +kernel)

theorem S6_15955 : Classified Catalogue.Order6.S6_15955 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6GenericCASRootWrappers.S6_15955.opposite_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6GenericCASRootWrappers.S6_15955.opposite_basis)) (by decide +kernel)

theorem S6_15956 : Classified Catalogue.Order6.S6_15956 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6GenericCASRootWrappers.S6_15956.opposite_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6GenericCASRootWrappers.S6_15956.opposite_basis)) (by decide +kernel)

theorem S6_15957 : Classified Catalogue.Order6.S6_15957 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15957.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15957.representative_basis)) (by decide +kernel)

theorem S6_15958 : Classified Catalogue.Order6.S6_15958 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15958.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15958.representative_basis)) (by decide +kernel)

theorem S6_15959 : Classified Catalogue.Order6.S6_15959 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day7.S2_4.Rank070.Seed.s6_15959_representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day7.S2_4.Rank070.Seed.s6_15959_representative_basis)) (by decide +kernel)

theorem S6_15960 : Classified Catalogue.Order6.S6_15960 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6GenericCASMonoidPower.S6_15960_oppositeBasisFor) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6GenericCASMonoidPower.S6_15960_oppositeBasisFor)) (by decide +kernel)

theorem S6_15961 : Classified Catalogue.Order6.S6_15961 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6GenericCASRootWrappers.S6_15961.opposite_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6GenericCASRootWrappers.S6_15961.opposite_basis)) (by decide +kernel)

theorem S6_15962 : Classified Catalogue.Order6.S6_15962 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15962.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15962.representative_basis)) (by decide +kernel)

theorem S6_15963 : Classified Catalogue.Order6.S6_15963 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15963.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15963.representative_basis)) (by decide +kernel)

theorem S6_15964 : Classified Catalogue.Order6.S6_15964 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6L3RootS3_18TargetsS4_2.S6_15964.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6L3RootS3_18TargetsS4_2.S6_15964.representative_basis)) (by decide +kernel)

theorem S6_15965 : Classified Catalogue.Order6.S6_15965 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6GenericCASRootWrappers.S6_15965.opposite_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6GenericCASRootWrappers.S6_15965.opposite_basis)) (by decide +kernel)

theorem S6_15966 : Classified Catalogue.Order6.S6_15966 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15966.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15966.representative_basis)) (by decide +kernel)

theorem S6_15967 : Classified Catalogue.Order6.S6_15967 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15967.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15967.representative_basis)) (by decide +kernel)

theorem S6_15968 : Classified Catalogue.Order6.S6_15968 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6L3RootS3_18TargetsS4_9.S6_15968.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6L3RootS3_18TargetsS4_9.S6_15968.representative_basis)) (by decide +kernel)

theorem S6_15969 : Classified Catalogue.Order6.S6_15969 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15969.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15969.representative_basis)) (by decide +kernel)

theorem S6_15970 : Classified Catalogue.Order6.S6_15970 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15970.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15970.representative_basis)) (by decide +kernel)

theorem S6_15971 : Classified Catalogue.Order6.S6_15971 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6L3RootS3_18TargetsS4_9.S6_15971.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6L3RootS3_18TargetsS4_9.S6_15971.representative_basis)) (by decide +kernel)

theorem S6_15972 : Classified Catalogue.Order6.S6_15972 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15972.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_15972.representative_basis)) (by decide +kernel)

theorem S6_15973 : Classified Catalogue.Order6.S6_15973 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6RouteLocalRootAdapters.S6_15973.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6RouteLocalRootAdapters.S6_15973.representative_basis)) (by decide +kernel)

/-- Every class of part 107 of the catalogue is classified. -/
theorem shard107 : AllClassified Catalogue.Order6.part107 :=
  AllClassified.cons S6_15901 <|
  AllClassified.cons S6_15902 <|
  AllClassified.cons S6_15903 <|
  AllClassified.cons S6_15904 <|
  AllClassified.cons S6_15905 <|
  AllClassified.cons S6_15906 <|
  AllClassified.cons S6_15907 <|
  AllClassified.cons S6_15908 <|
  AllClassified.cons S6_15909 <|
  AllClassified.cons S6_15910 <|
  AllClassified.cons S6_15911 <|
  AllClassified.cons S6_15912 <|
  AllClassified.cons S6_15913 <|
  AllClassified.cons S6_15914 <|
  AllClassified.cons S6_15915 <|
  AllClassified.cons S6_15916 <|
  AllClassified.cons S6_15917 <|
  AllClassified.cons S6_15918 <|
  AllClassified.cons S6_15919 <|
  AllClassified.cons S6_15920 <|
  AllClassified.cons S6_15921 <|
  AllClassified.cons S6_15922 <|
  AllClassified.cons S6_15923 <|
  AllClassified.cons S6_15924 <|
  AllClassified.cons S6_15925 <|
  AllClassified.cons S6_15926 <|
  AllClassified.cons S6_15927 <|
  AllClassified.cons S6_15928 <|
  AllClassified.cons S6_15929 <|
  AllClassified.cons S6_15930 <|
  AllClassified.cons S6_15931 <|
  AllClassified.cons S6_15932 <|
  AllClassified.cons S6_15933 <|
  AllClassified.cons S6_15934 <|
  AllClassified.cons S6_15935 <|
  AllClassified.cons S6_15936 <|
  AllClassified.cons S6_15937 <|
  AllClassified.cons S6_15938 <|
  AllClassified.cons S6_15939 <|
  AllClassified.cons S6_15940 <|
  AllClassified.cons S6_15941 <|
  AllClassified.cons S6_15942 <|
  AllClassified.cons S6_15943 <|
  AllClassified.cons S6_15944 <|
  AllClassified.cons S6_15945 <|
  AllClassified.cons S6_15946 <|
  AllClassified.cons S6_15947 <|
  AllClassified.cons S6_15948 <|
  AllClassified.cons S6_15949 <|
  AllClassified.cons S6_15950 <|
  AllClassified.cons S6_15951 <|
  AllClassified.cons S6_15952 <|
  AllClassified.cons S6_15953 <|
  AllClassified.cons S6_15954 <|
  AllClassified.cons S6_15955 <|
  AllClassified.cons S6_15956 <|
  AllClassified.cons S6_15957 <|
  AllClassified.cons S6_15958 <|
  AllClassified.cons S6_15959 <|
  AllClassified.cons S6_15960 <|
  AllClassified.cons S6_15961 <|
  AllClassified.cons S6_15962 <|
  AllClassified.cons S6_15963 <|
  AllClassified.cons S6_15964 <|
  AllClassified.cons S6_15965 <|
  AllClassified.cons S6_15966 <|
  AllClassified.cons S6_15967 <|
  AllClassified.cons S6_15968 <|
  AllClassified.cons S6_15969 <|
  AllClassified.cons S6_15970 <|
  AllClassified.cons S6_15971 <|
  AllClassified.cons S6_15972 <|
  AllClassified.cons S6_15973 <|
  AllClassified.nil

end SemiBase.Census
