import SemiBase.Statement
import SemiBase.Catalogue.Order6.Part075
import Order6FinalL5TransferV3.Part265
import Order6FinalL5TransferV3.Part266
import Order6FinalL5TransferV3.Part267
import Order6FinalL5TransferV3.Part268
import SemigroupBasis.CoRoots.Order6Day10.SharedLevel3Section03.Section03ClassEndpoints
import SemigroupBasis.CoRoots.Order6Day11.FordLordProfile121415.Profile121415Completeness
import SemigroupBasis.CoRoots.Order6Day12.FordLast2.T16Completeness
import SemigroupBasis.CoRoots.Order6Day7.S3_11.Rank058ParityConnectedCutComplete
import SemigroupBasis.CoRoots.Order6Day7.S3_11.SeedS5_796Opposite
import SemigroupBasis.CoRoots.Order6Day7.S3_11.SeedS5_798Opposite
import SemigroupBasis.CoRoots.Order6Hull23_1PhaseParityB23Endpoints
import SemigroupBasis.CoRoots.Order6LeeLiP2G2Members
import SemigroupBasis.CoRoots.Order6LeeLiP2G3Members
import SemigroupBasis.CoRoots.Order6LeeLiP2G4Members
import SemigroupBasis.CoRoots.Order6Sunday.Msg0534SingletonParityCompleteness
import SemigroupBasis.Generated.Order6Condition8ThreeLawTargets
import SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_3541_Ad4b303415746_Part02
import SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_4055_Ad4b303415746_Part01
import SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_6196_Ad4b303415746_Part01
import SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_6197_Ad4b303415746_Part01
import SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_6208_Ad4b303415746_Part01
import SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_6211_Ad4b303415746_Part01
import SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_6241_Ad4b303415746_Part01
import SemigroupBasis.Generated.Order6DivisorTransfersPart37
import SemigroupBasis.Generated.Order6EmbeddingTransfersPart12
import SemigroupBasis.Generated.Order6FactorPairS3_11Targets
import SemigroupBasis.Generated.Order6Level2TierBHashE2c5e460.S6_11232
import SemigroupBasis.Generated.Order6OneLocalFordLastSigmaCdd7.S6_11236
import SemigroupBasis.Order6.S6_11234FromS6_8874
import research.formalization.order6.extension.order6_extension_2026_06_12_l5_extension_v1.Order6ExtensionTransfersPart11
import research.formalization.order6.extension.order6_extension_2026_06_12_l5_extension_v2.Order6ExtensionTransfersPart09
import research.formalization.order6.extension.order6_extension_2026_06_12_l5_extension_v2.Order6ExtensionTransfersPart10
import research.formalization.order6.extension.order6_extension_2026_06_12_l5_extension_v3.Order6ExtensionTransfersPart03
import research.formalization.order6.extension.order6_extension_2026_06_12_l5_extension_v4.Order6ExtensionTransfersPart03
import research.formalization.order6.extension.order6_extension_2026_06_12_l5_extension_v5.Order6ExtensionTransfersPart05
import research.formalization.order6.extension.order6_extension_2026_06_12_l5_extension_v6.Order6ExtensionTransfersPart05

/-!
# Census shard 075: classes `[6, 11101]` to `[6, 11250]`

For each class, the claim `Classified` from one endpoint theorem of the
development. The first alternative that checks is used: the endpoint for the
semigroup with the catalogue table, or for its opposite (the transposed table).
Generated by `scripts/generate_census.py`.
-/

set_option maxRecDepth 8192

namespace SemiBase.Census

theorem S6_11101 : Classified Catalogue.Order6.S6_11101 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_11101.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_11101.representative_basis)) (by decide +kernel)

theorem S6_11102 : Classified Catalogue.Order6.S6_11102 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11102.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11102.representative_basis)) (by decide +kernel)

theorem S6_11103 : Classified Catalogue.Order6.S6_11103 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11103.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11103.representative_basis)) (by decide +kernel)

theorem S6_11104 : Classified Catalogue.Order6.S6_11104 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11104.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11104.representative_basis)) (by decide +kernel)

theorem S6_11105 : Classified Catalogue.Order6.S6_11105 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11105.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11105.representative_basis)) (by decide +kernel)

theorem S6_11106 : Classified Catalogue.Order6.S6_11106 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11106.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11106.representative_basis)) (by decide +kernel)

theorem S6_11107 : Classified Catalogue.Order6.S6_11107 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11107.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11107.representative_basis)) (by decide +kernel)

theorem S6_11108 : Classified Catalogue.Order6.S6_11108 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_11108.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_11108.representative_basis)) (by decide +kernel)

theorem S6_11109 : Classified Catalogue.Order6.S6_11109 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_11109.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_11109.representative_basis)) (by decide +kernel)

theorem S6_11110 : Classified Catalogue.Order6.S6_11110 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_11110.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_11110.representative_basis)) (by decide +kernel)

theorem S6_11111 : Classified Catalogue.Order6.S6_11111 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_11111.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_11111.representative_basis)) (by decide +kernel)

theorem S6_11112 : Classified Catalogue.Order6.S6_11112 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_11112.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_11112.representative_basis)) (by decide +kernel)

theorem S6_11113 : Classified Catalogue.Order6.S6_11113 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11113.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11113.representative_basis)) (by decide +kernel)

theorem S6_11114 : Classified Catalogue.Order6.S6_11114 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_11114.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_11114.representative_basis)) (by decide +kernel)

theorem S6_11115 : Classified Catalogue.Order6.S6_11115 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_11115.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_11115.representative_basis)) (by decide +kernel)

theorem S6_11116 : Classified Catalogue.Order6.S6_11116 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_11116.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_11116.representative_basis)) (by decide +kernel)

theorem S6_11117 : Classified Catalogue.Order6.S6_11117 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6LeeLiP2G2.Members.S6_11117.basisFor) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6LeeLiP2G2.Members.S6_11117.basisFor)) (by decide +kernel)

theorem S6_11118 : Classified Catalogue.Order6.S6_11118 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day10.SharedLevel3Section03.Section03ClassEndpoints.S6_11118.basisFor) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day10.SharedLevel3Section03.Section03ClassEndpoints.S6_11118.basisFor)) (by decide +kernel)

theorem S6_11119 : Classified Catalogue.Order6.S6_11119 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day10.SharedLevel3Section03.Section03ClassEndpoints.S6_11119.basisFor) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day10.SharedLevel3Section03.Section03ClassEndpoints.S6_11119.basisFor)) (by decide +kernel)

theorem S6_11120 : Classified Catalogue.Order6.S6_11120 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6LeeLiP2G2.Members.S6_11120.basisFor) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6LeeLiP2G2.Members.S6_11120.basisFor)) (by decide +kernel)

theorem S6_11121 : Classified Catalogue.Order6.S6_11121 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11121.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11121.representative_basis)) (by decide +kernel)

theorem S6_11122 : Classified Catalogue.Order6.S6_11122 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11122.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11122.representative_basis)) (by decide +kernel)

theorem S6_11123 : Classified Catalogue.Order6.S6_11123 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11123.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11123.representative_basis)) (by decide +kernel)

theorem S6_11124 : Classified Catalogue.Order6.S6_11124 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6LeeLiP2G4.Members.S6_11124.basisFor) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6LeeLiP2G4.Members.S6_11124.basisFor)) (by decide +kernel)

theorem S6_11125 : Classified Catalogue.Order6.S6_11125 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11125.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11125.representative_basis)) (by decide +kernel)

theorem S6_11126 : Classified Catalogue.Order6.S6_11126 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6LeeLiP2G4.Members.S6_11126.basisFor) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6LeeLiP2G4.Members.S6_11126.basisFor)) (by decide +kernel)

theorem S6_11127 : Classified Catalogue.Order6.S6_11127 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6LeeLiP2G2.Members.S6_11127.basisFor) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6LeeLiP2G2.Members.S6_11127.basisFor)) (by decide +kernel)

theorem S6_11128 : Classified Catalogue.Order6.S6_11128 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6LeeLiP2G3.Members.S6_11128.basisFor) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6LeeLiP2G3.Members.S6_11128.basisFor)) (by decide +kernel)

theorem S6_11129 : Classified Catalogue.Order6.S6_11129 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_11129.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_11129.representative_basis)) (by decide +kernel)

theorem S6_11130 : Classified Catalogue.Order6.S6_11130 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11130.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11130.representative_basis)) (by decide +kernel)

theorem S6_11131 : Classified Catalogue.Order6.S6_11131 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_11131.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_11131.representative_basis)) (by decide +kernel)

theorem S6_11132 : Classified Catalogue.Order6.S6_11132 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11132.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11132.representative_basis)) (by decide +kernel)

theorem S6_11133 : Classified Catalogue.Order6.S6_11133 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV3.S6_11133.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV3.S6_11133.representative_basis)) (by decide +kernel)

theorem S6_11134 : Classified Catalogue.Order6.S6_11134 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11134.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11134.representative_basis)) (by decide +kernel)

theorem S6_11135 : Classified Catalogue.Order6.S6_11135 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_11135.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_11135.representative_basis)) (by decide +kernel)

theorem S6_11136 : Classified Catalogue.Order6.S6_11136 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_11136.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_11136.representative_basis)) (by decide +kernel)

theorem S6_11137 : Classified Catalogue.Order6.S6_11137 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_11137.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_11137.representative_basis)) (by decide +kernel)

theorem S6_11138 : Classified Catalogue.Order6.S6_11138 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_11138.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_11138.representative_basis)) (by decide +kernel)

theorem S6_11139 : Classified Catalogue.Order6.S6_11139 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_11139.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_11139.representative_basis)) (by decide +kernel)

theorem S6_11140 : Classified Catalogue.Order6.S6_11140 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_11140.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_11140.representative_basis)) (by decide +kernel)

theorem S6_11141 : Classified Catalogue.Order6.S6_11141 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_11141.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_11141.representative_basis)) (by decide +kernel)

theorem S6_11142 : Classified Catalogue.Order6.S6_11142 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_11142.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_11142.representative_basis)) (by decide +kernel)

theorem S6_11143 : Classified Catalogue.Order6.S6_11143 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_11143.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_11143.representative_basis)) (by decide +kernel)

theorem S6_11144 : Classified Catalogue.Order6.S6_11144 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_11144.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_11144.representative_basis)) (by decide +kernel)

theorem S6_11145 : Classified Catalogue.Order6.S6_11145 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV3.S6_11145.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV3.S6_11145.representative_basis)) (by decide +kernel)

theorem S6_11146 : Classified Catalogue.Order6.S6_11146 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_6197_Ad4b303415746_Part01.S6_11146.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_6197_Ad4b303415746_Part01.S6_11146.representative_basis)) (by decide +kernel)

theorem S6_11147 : Classified Catalogue.Order6.S6_11147 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_6211_Ad4b303415746_Part01.S6_11147.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_6211_Ad4b303415746_Part01.S6_11147.representative_basis)) (by decide +kernel)

theorem S6_11148 : Classified Catalogue.Order6.S6_11148 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_6241_Ad4b303415746_Part01.S6_11148.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_6241_Ad4b303415746_Part01.S6_11148.representative_basis)) (by decide +kernel)

theorem S6_11149 : Classified Catalogue.Order6.S6_11149 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_6196_Ad4b303415746_Part01.S6_11149.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_6196_Ad4b303415746_Part01.S6_11149.representative_basis)) (by decide +kernel)

theorem S6_11150 : Classified Catalogue.Order6.S6_11150 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_6197_Ad4b303415746_Part01.S6_11150.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_6197_Ad4b303415746_Part01.S6_11150.representative_basis)) (by decide +kernel)

theorem S6_11151 : Classified Catalogue.Order6.S6_11151 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_6208_Ad4b303415746_Part01.S6_11151.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_6208_Ad4b303415746_Part01.S6_11151.representative_basis)) (by decide +kernel)

theorem S6_11152 : Classified Catalogue.Order6.S6_11152 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_6211_Ad4b303415746_Part01.S6_11152.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_6211_Ad4b303415746_Part01.S6_11152.representative_basis)) (by decide +kernel)

theorem S6_11153 : Classified Catalogue.Order6.S6_11153 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_6241_Ad4b303415746_Part01.S6_11153.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_6241_Ad4b303415746_Part01.S6_11153.representative_basis)) (by decide +kernel)

theorem S6_11154 : Classified Catalogue.Order6.S6_11154 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11154.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11154.representative_basis)) (by decide +kernel)

theorem S6_11155 : Classified Catalogue.Order6.S6_11155 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11155.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11155.representative_basis)) (by decide +kernel)

theorem S6_11156 : Classified Catalogue.Order6.S6_11156 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11156.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11156.representative_basis)) (by decide +kernel)

theorem S6_11157 : Classified Catalogue.Order6.S6_11157 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11157.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11157.representative_basis)) (by decide +kernel)

theorem S6_11158 : Classified Catalogue.Order6.S6_11158 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11158.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11158.representative_basis)) (by decide +kernel)

theorem S6_11159 : Classified Catalogue.Order6.S6_11159 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11159.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11159.representative_basis)) (by decide +kernel)

theorem S6_11160 : Classified Catalogue.Order6.S6_11160 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11160.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11160.representative_basis)) (by decide +kernel)

theorem S6_11161 : Classified Catalogue.Order6.S6_11161 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11161.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11161.representative_basis)) (by decide +kernel)

theorem S6_11162 : Classified Catalogue.Order6.S6_11162 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6Condition8ThreeLawTargets.S6_11162.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6Condition8ThreeLawTargets.S6_11162.representative_basis)) (by decide +kernel)

theorem S6_11163 : Classified Catalogue.Order6.S6_11163 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11163.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11163.representative_basis)) (by decide +kernel)

theorem S6_11164 : Classified Catalogue.Order6.S6_11164 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11164.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11164.representative_basis)) (by decide +kernel)

theorem S6_11165 : Classified Catalogue.Order6.S6_11165 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Hull23_1PhaseParityB23Endpoints.S6_11165_basisFor) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Hull23_1PhaseParityB23Endpoints.S6_11165_basisFor)) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_transport (perm6 [0, 1, 4, 2, 3, 5]) (perm6 [0, 1, 3, 4, 2, 5]) (by decide +kernel) (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Hull23_1PhaseParityB23Endpoints.S6_11165_basisFor)) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_transport (perm6 [0, 1, 4, 2, 3, 5]) (perm6 [0, 1, 3, 4, 2, 5]) (by decide +kernel) (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Hull23_1PhaseParityB23Endpoints.S6_11165_basisFor))) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_transport (perm6 [0, 1, 3, 4, 2, 5]) (perm6 [0, 1, 4, 2, 3, 5]) (by decide +kernel) (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Hull23_1PhaseParityB23Endpoints.S6_11165_basisFor)) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_transport (perm6 [0, 1, 3, 4, 2, 5]) (perm6 [0, 1, 4, 2, 3, 5]) (by decide +kernel) (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Hull23_1PhaseParityB23Endpoints.S6_11165_basisFor))) (by decide +kernel)

theorem S6_11166 : Classified Catalogue.Order6.S6_11166 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Hull23_1PhaseParityB23Endpoints.S6_11166_basisFor) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Hull23_1PhaseParityB23Endpoints.S6_11166_basisFor)) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_transport (perm6 [0, 1, 4, 2, 3, 5]) (perm6 [0, 1, 3, 4, 2, 5]) (by decide +kernel) (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Hull23_1PhaseParityB23Endpoints.S6_11166_basisFor)) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_transport (perm6 [0, 1, 4, 2, 3, 5]) (perm6 [0, 1, 3, 4, 2, 5]) (by decide +kernel) (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Hull23_1PhaseParityB23Endpoints.S6_11166_basisFor))) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_transport (perm6 [0, 1, 3, 4, 2, 5]) (perm6 [0, 1, 4, 2, 3, 5]) (by decide +kernel) (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Hull23_1PhaseParityB23Endpoints.S6_11166_basisFor)) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_transport (perm6 [0, 1, 3, 4, 2, 5]) (perm6 [0, 1, 4, 2, 3, 5]) (by decide +kernel) (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Hull23_1PhaseParityB23Endpoints.S6_11166_basisFor))) (by decide +kernel)

theorem S6_11167 : Classified Catalogue.Order6.S6_11167 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11167.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11167.representative_basis)) (by decide +kernel)

theorem S6_11168 : Classified Catalogue.Order6.S6_11168 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11168.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11168.representative_basis)) (by decide +kernel)

theorem S6_11169 : Classified Catalogue.Order6.S6_11169 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11169.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11169.representative_basis)) (by decide +kernel)

theorem S6_11170 : Classified Catalogue.Order6.S6_11170 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6Condition8ThreeLawTargets.S6_11170.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6Condition8ThreeLawTargets.S6_11170.representative_basis)) (by decide +kernel)

theorem S6_11171 : Classified Catalogue.Order6.S6_11171 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_11171.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_11171.representative_basis)) (by decide +kernel)

theorem S6_11172 : Classified Catalogue.Order6.S6_11172 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_11172.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_11172.representative_basis)) (by decide +kernel)

theorem S6_11173 : Classified Catalogue.Order6.S6_11173 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_11173.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_11173.representative_basis)) (by decide +kernel)

theorem S6_11174 : Classified Catalogue.Order6.S6_11174 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_11174.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_11174.representative_basis)) (by decide +kernel)

theorem S6_11175 : Classified Catalogue.Order6.S6_11175 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_11175.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_11175.representative_basis)) (by decide +kernel)

theorem S6_11176 : Classified Catalogue.Order6.S6_11176 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV6.S6_11176.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV6.S6_11176.representative_basis)) (by decide +kernel)

theorem S6_11177 : Classified Catalogue.Order6.S6_11177 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_11177.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_11177.representative_basis)) (by decide +kernel)

theorem S6_11178 : Classified Catalogue.Order6.S6_11178 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_11178.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_11178.representative_basis)) (by decide +kernel)

theorem S6_11179 : Classified Catalogue.Order6.S6_11179 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_11179.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_11179.representative_basis)) (by decide +kernel)

theorem S6_11180 : Classified Catalogue.Order6.S6_11180 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_11180.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_11180.representative_basis)) (by decide +kernel)

theorem S6_11181 : Classified Catalogue.Order6.S6_11181 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV6.S6_11181.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV6.S6_11181.representative_basis)) (by decide +kernel)

theorem S6_11182 : Classified Catalogue.Order6.S6_11182 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV6.S6_11182.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV6.S6_11182.representative_basis)) (by decide +kernel)

theorem S6_11183 : Classified Catalogue.Order6.S6_11183 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11183.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11183.representative_basis)) (by decide +kernel)

theorem S6_11184 : Classified Catalogue.Order6.S6_11184 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_11184.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_11184.representative_basis)) (by decide +kernel)

theorem S6_11185 : Classified Catalogue.Order6.S6_11185 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_11185.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_11185.representative_basis)) (by decide +kernel)

theorem S6_11186 : Classified Catalogue.Order6.S6_11186 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV5.S6_11186.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV5.S6_11186.representative_basis)) (by decide +kernel)

theorem S6_11187 : Classified Catalogue.Order6.S6_11187 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_11187.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_11187.representative_basis)) (by decide +kernel)

theorem S6_11188 : Classified Catalogue.Order6.S6_11188 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_11188.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_11188.representative_basis)) (by decide +kernel)

theorem S6_11189 : Classified Catalogue.Order6.S6_11189 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV4.S6_11189.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV4.S6_11189.representative_basis)) (by decide +kernel)

theorem S6_11190 : Classified Catalogue.Order6.S6_11190 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_4055_Ad4b303415746_Part01.S6_11190.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_4055_Ad4b303415746_Part01.S6_11190.representative_basis)) (by decide +kernel)

theorem S6_11191 : Classified Catalogue.Order6.S6_11191 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV4.S6_11191.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV4.S6_11191.representative_basis)) (by decide +kernel)

theorem S6_11192 : Classified Catalogue.Order6.S6_11192 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV4.S6_11192.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV4.S6_11192.representative_basis)) (by decide +kernel)

theorem S6_11193 : Classified Catalogue.Order6.S6_11193 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_4055_Ad4b303415746_Part01.S6_11193.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_4055_Ad4b303415746_Part01.S6_11193.representative_basis)) (by decide +kernel)

theorem S6_11194 : Classified Catalogue.Order6.S6_11194 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11194.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11194.representative_basis)) (by decide +kernel)

theorem S6_11195 : Classified Catalogue.Order6.S6_11195 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11195.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11195.representative_basis)) (by decide +kernel)

theorem S6_11196 : Classified Catalogue.Order6.S6_11196 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11196.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11196.representative_basis)) (by decide +kernel)

theorem S6_11197 : Classified Catalogue.Order6.S6_11197 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11197.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11197.representative_basis)) (by decide +kernel)

theorem S6_11198 : Classified Catalogue.Order6.S6_11198 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11198.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11198.representative_basis)) (by decide +kernel)

theorem S6_11199 : Classified Catalogue.Order6.S6_11199 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11199.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11199.representative_basis)) (by decide +kernel)

theorem S6_11200 : Classified Catalogue.Order6.S6_11200 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11200.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11200.representative_basis)) (by decide +kernel)

theorem S6_11201 : Classified Catalogue.Order6.S6_11201 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11201.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11201.representative_basis)) (by decide +kernel)

theorem S6_11202 : Classified Catalogue.Order6.S6_11202 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11202.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11202.representative_basis)) (by decide +kernel)

theorem S6_11203 : Classified Catalogue.Order6.S6_11203 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11203.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11203.representative_basis)) (by decide +kernel)

theorem S6_11204 : Classified Catalogue.Order6.S6_11204 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11204.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11204.representative_basis)) (by decide +kernel)

theorem S6_11205 : Classified Catalogue.Order6.S6_11205 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11205.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11205.representative_basis)) (by decide +kernel)

theorem S6_11206 : Classified Catalogue.Order6.S6_11206 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11206.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11206.representative_basis)) (by decide +kernel)

theorem S6_11207 : Classified Catalogue.Order6.S6_11207 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11207.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11207.representative_basis)) (by decide +kernel)

theorem S6_11208 : Classified Catalogue.Order6.S6_11208 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11208.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11208.representative_basis)) (by decide +kernel)

theorem S6_11209 : Classified Catalogue.Order6.S6_11209 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV5.S6_11209.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV5.S6_11209.representative_basis)) (by decide +kernel)

theorem S6_11210 : Classified Catalogue.Order6.S6_11210 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11210.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11210.representative_basis)) (by decide +kernel)

theorem S6_11211 : Classified Catalogue.Order6.S6_11211 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV5.S6_11211.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV5.S6_11211.representative_basis)) (by decide +kernel)

theorem S6_11212 : Classified Catalogue.Order6.S6_11212 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11212.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11212.representative_basis)) (by decide +kernel)

theorem S6_11213 : Classified Catalogue.Order6.S6_11213 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV5.S6_11213.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV5.S6_11213.representative_basis)) (by decide +kernel)

theorem S6_11214 : Classified Catalogue.Order6.S6_11214 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11214.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11214.representative_basis)) (by decide +kernel)

theorem S6_11215 : Classified Catalogue.Order6.S6_11215 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11215.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11215.representative_basis)) (by decide +kernel)

theorem S6_11216 : Classified Catalogue.Order6.S6_11216 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11216.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11216.representative_basis)) (by decide +kernel)

theorem S6_11217 : Classified Catalogue.Order6.S6_11217 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV5.S6_11217.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV5.S6_11217.representative_basis)) (by decide +kernel)

theorem S6_11218 : Classified Catalogue.Order6.S6_11218 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV5.S6_11218.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV5.S6_11218.representative_basis)) (by decide +kernel)

theorem S6_11219 : Classified Catalogue.Order6.S6_11219 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11219.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11219.representative_basis)) (by decide +kernel)

theorem S6_11220 : Classified Catalogue.Order6.S6_11220 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11220.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11220.representative_basis)) (by decide +kernel)

theorem S6_11221 : Classified Catalogue.Order6.S6_11221 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_3541_Ad4b303415746_Part02.S6_11221.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_3541_Ad4b303415746_Part02.S6_11221.representative_basis)) (by decide +kernel)

theorem S6_11222 : Classified Catalogue.Order6.S6_11222 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day12.FordLast2.S6_11222.basisFor) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day12.FordLast2.S6_11222.basisFor)) (by decide +kernel)

theorem S6_11223 : Classified Catalogue.Order6.S6_11223 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV5.S6_11223.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV5.S6_11223.representative_basis)) (by decide +kernel)

theorem S6_11224 : Classified Catalogue.Order6.S6_11224 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11224.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11224.representative_basis)) (by decide +kernel)

theorem S6_11225 : Classified Catalogue.Order6.S6_11225 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11225.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11225.representative_basis)) (by decide +kernel)

theorem S6_11226 : Classified Catalogue.Order6.S6_11226 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11226.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11226.representative_basis)) (by decide +kernel)

theorem S6_11227 : Classified Catalogue.Order6.S6_11227 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day11.FordLordProfile121415.S6_11227.basisFor) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day11.FordLordProfile121415.S6_11227.basisFor)) (by decide +kernel)

theorem S6_11228 : Classified Catalogue.Order6.S6_11228 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day7.S3_11.SeedS5_796Opposite.representative_basis_S6_11228) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day7.S3_11.SeedS5_796Opposite.representative_basis_S6_11228)) (by decide +kernel)

theorem S6_11229 : Classified Catalogue.Order6.S6_11229 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day7.S3_11.Rank058.ParityConnectedCutComplete.s6_11229_representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day7.S3_11.Rank058.ParityConnectedCutComplete.s6_11229_representative_basis)) (by decide +kernel)

theorem S6_11230 : Classified Catalogue.Order6.S6_11230 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FactorPairS3_11Targets.S6_11230.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FactorPairS3_11Targets.S6_11230.representative_basis)) (by decide +kernel)

theorem S6_11231 : Classified Catalogue.Order6.S6_11231 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11231.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11231.representative_basis)) (by decide +kernel)

theorem S6_11232 : Classified Catalogue.Order6.S6_11232 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6Level2TierBHashE2c5e460.S6_11232.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6Level2TierBHashE2c5e460.S6_11232.representative_basis)) (by decide +kernel)

theorem S6_11233 : Classified Catalogue.Order6.S6_11233 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day7.S3_11.SeedS5_798Opposite.representative_basis_S6_11233) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day7.S3_11.SeedS5_798Opposite.representative_basis_S6_11233)) (by decide +kernel)

theorem S6_11234 : Classified Catalogue.Order6.S6_11234 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Order6.S6_11234.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Order6.S6_11234.representative_basis)) (by decide +kernel)

theorem S6_11235 : Classified Catalogue.Order6.S6_11235 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11235.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11235.representative_basis)) (by decide +kernel)

theorem S6_11236 : Classified Catalogue.Order6.S6_11236 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6OneLocalFordLastSigmaCdd7.S6_11236.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6OneLocalFordLastSigmaCdd7.S6_11236.representative_basis)) (by decide +kernel)

theorem S6_11237 : Classified Catalogue.Order6.S6_11237 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Sunday.Msg0534SingletonParityCompleteness.S6_11237.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Sunday.Msg0534SingletonParityCompleteness.S6_11237.representative_basis)) (by decide +kernel)

theorem S6_11238 : Classified Catalogue.Order6.S6_11238 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_11238.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_11238.representative_basis)) (by decide +kernel)

theorem S6_11239 : Classified Catalogue.Order6.S6_11239 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_11239.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_11239.representative_basis)) (by decide +kernel)

theorem S6_11240 : Classified Catalogue.Order6.S6_11240 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_11240.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_11240.representative_basis)) (by decide +kernel)

theorem S6_11241 : Classified Catalogue.Order6.S6_11241 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_11241.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_11241.representative_basis)) (by decide +kernel)

theorem S6_11242 : Classified Catalogue.Order6.S6_11242 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11242.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11242.representative_basis)) (by decide +kernel)

theorem S6_11243 : Classified Catalogue.Order6.S6_11243 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11243.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11243.representative_basis)) (by decide +kernel)

theorem S6_11244 : Classified Catalogue.Order6.S6_11244 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_11244.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_11244.representative_basis)) (by decide +kernel)

theorem S6_11245 : Classified Catalogue.Order6.S6_11245 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_11245.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_11245.representative_basis)) (by decide +kernel)

theorem S6_11246 : Classified Catalogue.Order6.S6_11246 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_11246.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_11246.representative_basis)) (by decide +kernel)

theorem S6_11247 : Classified Catalogue.Order6.S6_11247 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11247.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_11247.representative_basis)) (by decide +kernel)

theorem S6_11248 : Classified Catalogue.Order6.S6_11248 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_11248.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_11248.representative_basis)) (by decide +kernel)

theorem S6_11249 : Classified Catalogue.Order6.S6_11249 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_11249.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_11249.representative_basis)) (by decide +kernel)

theorem S6_11250 : Classified Catalogue.Order6.S6_11250 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_11250.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_11250.representative_basis)) (by decide +kernel)

/-- Every class of part 075 of the catalogue is classified. -/
theorem shard075 : AllClassified Catalogue.Order6.part075 :=
  AllClassified.cons S6_11101 <|
  AllClassified.cons S6_11102 <|
  AllClassified.cons S6_11103 <|
  AllClassified.cons S6_11104 <|
  AllClassified.cons S6_11105 <|
  AllClassified.cons S6_11106 <|
  AllClassified.cons S6_11107 <|
  AllClassified.cons S6_11108 <|
  AllClassified.cons S6_11109 <|
  AllClassified.cons S6_11110 <|
  AllClassified.cons S6_11111 <|
  AllClassified.cons S6_11112 <|
  AllClassified.cons S6_11113 <|
  AllClassified.cons S6_11114 <|
  AllClassified.cons S6_11115 <|
  AllClassified.cons S6_11116 <|
  AllClassified.cons S6_11117 <|
  AllClassified.cons S6_11118 <|
  AllClassified.cons S6_11119 <|
  AllClassified.cons S6_11120 <|
  AllClassified.cons S6_11121 <|
  AllClassified.cons S6_11122 <|
  AllClassified.cons S6_11123 <|
  AllClassified.cons S6_11124 <|
  AllClassified.cons S6_11125 <|
  AllClassified.cons S6_11126 <|
  AllClassified.cons S6_11127 <|
  AllClassified.cons S6_11128 <|
  AllClassified.cons S6_11129 <|
  AllClassified.cons S6_11130 <|
  AllClassified.cons S6_11131 <|
  AllClassified.cons S6_11132 <|
  AllClassified.cons S6_11133 <|
  AllClassified.cons S6_11134 <|
  AllClassified.cons S6_11135 <|
  AllClassified.cons S6_11136 <|
  AllClassified.cons S6_11137 <|
  AllClassified.cons S6_11138 <|
  AllClassified.cons S6_11139 <|
  AllClassified.cons S6_11140 <|
  AllClassified.cons S6_11141 <|
  AllClassified.cons S6_11142 <|
  AllClassified.cons S6_11143 <|
  AllClassified.cons S6_11144 <|
  AllClassified.cons S6_11145 <|
  AllClassified.cons S6_11146 <|
  AllClassified.cons S6_11147 <|
  AllClassified.cons S6_11148 <|
  AllClassified.cons S6_11149 <|
  AllClassified.cons S6_11150 <|
  AllClassified.cons S6_11151 <|
  AllClassified.cons S6_11152 <|
  AllClassified.cons S6_11153 <|
  AllClassified.cons S6_11154 <|
  AllClassified.cons S6_11155 <|
  AllClassified.cons S6_11156 <|
  AllClassified.cons S6_11157 <|
  AllClassified.cons S6_11158 <|
  AllClassified.cons S6_11159 <|
  AllClassified.cons S6_11160 <|
  AllClassified.cons S6_11161 <|
  AllClassified.cons S6_11162 <|
  AllClassified.cons S6_11163 <|
  AllClassified.cons S6_11164 <|
  AllClassified.cons S6_11165 <|
  AllClassified.cons S6_11166 <|
  AllClassified.cons S6_11167 <|
  AllClassified.cons S6_11168 <|
  AllClassified.cons S6_11169 <|
  AllClassified.cons S6_11170 <|
  AllClassified.cons S6_11171 <|
  AllClassified.cons S6_11172 <|
  AllClassified.cons S6_11173 <|
  AllClassified.cons S6_11174 <|
  AllClassified.cons S6_11175 <|
  AllClassified.cons S6_11176 <|
  AllClassified.cons S6_11177 <|
  AllClassified.cons S6_11178 <|
  AllClassified.cons S6_11179 <|
  AllClassified.cons S6_11180 <|
  AllClassified.cons S6_11181 <|
  AllClassified.cons S6_11182 <|
  AllClassified.cons S6_11183 <|
  AllClassified.cons S6_11184 <|
  AllClassified.cons S6_11185 <|
  AllClassified.cons S6_11186 <|
  AllClassified.cons S6_11187 <|
  AllClassified.cons S6_11188 <|
  AllClassified.cons S6_11189 <|
  AllClassified.cons S6_11190 <|
  AllClassified.cons S6_11191 <|
  AllClassified.cons S6_11192 <|
  AllClassified.cons S6_11193 <|
  AllClassified.cons S6_11194 <|
  AllClassified.cons S6_11195 <|
  AllClassified.cons S6_11196 <|
  AllClassified.cons S6_11197 <|
  AllClassified.cons S6_11198 <|
  AllClassified.cons S6_11199 <|
  AllClassified.cons S6_11200 <|
  AllClassified.cons S6_11201 <|
  AllClassified.cons S6_11202 <|
  AllClassified.cons S6_11203 <|
  AllClassified.cons S6_11204 <|
  AllClassified.cons S6_11205 <|
  AllClassified.cons S6_11206 <|
  AllClassified.cons S6_11207 <|
  AllClassified.cons S6_11208 <|
  AllClassified.cons S6_11209 <|
  AllClassified.cons S6_11210 <|
  AllClassified.cons S6_11211 <|
  AllClassified.cons S6_11212 <|
  AllClassified.cons S6_11213 <|
  AllClassified.cons S6_11214 <|
  AllClassified.cons S6_11215 <|
  AllClassified.cons S6_11216 <|
  AllClassified.cons S6_11217 <|
  AllClassified.cons S6_11218 <|
  AllClassified.cons S6_11219 <|
  AllClassified.cons S6_11220 <|
  AllClassified.cons S6_11221 <|
  AllClassified.cons S6_11222 <|
  AllClassified.cons S6_11223 <|
  AllClassified.cons S6_11224 <|
  AllClassified.cons S6_11225 <|
  AllClassified.cons S6_11226 <|
  AllClassified.cons S6_11227 <|
  AllClassified.cons S6_11228 <|
  AllClassified.cons S6_11229 <|
  AllClassified.cons S6_11230 <|
  AllClassified.cons S6_11231 <|
  AllClassified.cons S6_11232 <|
  AllClassified.cons S6_11233 <|
  AllClassified.cons S6_11234 <|
  AllClassified.cons S6_11235 <|
  AllClassified.cons S6_11236 <|
  AllClassified.cons S6_11237 <|
  AllClassified.cons S6_11238 <|
  AllClassified.cons S6_11239 <|
  AllClassified.cons S6_11240 <|
  AllClassified.cons S6_11241 <|
  AllClassified.cons S6_11242 <|
  AllClassified.cons S6_11243 <|
  AllClassified.cons S6_11244 <|
  AllClassified.cons S6_11245 <|
  AllClassified.cons S6_11246 <|
  AllClassified.cons S6_11247 <|
  AllClassified.cons S6_11248 <|
  AllClassified.cons S6_11249 <|
  AllClassified.cons S6_11250 <|
  AllClassified.nil

end SemiBase.Census
