import SemiBase.Statement
import SemiBase.Catalogue.Order6.Part019
import Order6FinalL5TransferV3.Part050
import Order6FinalL5TransferV3.Part051
import Order6FinalL5TransferV3.Part052
import Order6FinalL5TransferV3.Part053
import Order6FinalL5TransferV3.Part054
import Order6FinalL5TransferV3.Part055
import SemigroupBasis.CoRoots.Order6Day7.LeeZhang.Msg0430PairCompleteness
import SemigroupBasis.CoRoots.Order6Day7.LeeZhang.Msg0442CyclicCompleteness
import SemigroupBasis.CoRoots.Order6Day7.LeeZhang.S6_2708Sigma12Completeness
import SemigroupBasis.CoRoots.Order6Day7.LeeZhang.Sigma14AbsorbCompleteness
import SemigroupBasis.CoRoots.Order6Day7.LeeZhang.Sigma14SwapCompleteness
import SemigroupBasis.CoRoots.Order6FinalMarkerM2OppositeLeftRoots
import SemigroupBasis.CoRoots.Order6FinalMarkerM2Roots
import SemigroupBasis.CoRoots.Order6GenericCASSubdirectS6_2802
import SemigroupBasis.CoRoots.Order6GenericCASSubdirectS6_2850
import SemigroupBasis.CoRoots.Order6LongSupportThresholdRoots
import SemigroupBasis.CoRoots.Order6SporadicSection17C5Endpoints
import SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_2599_Ad4b303415746_Part01
import SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_2758_Ad4b303415746_Part01
import SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_2763_Ad4b303415746_Part01
import SemigroupBasis.Generated.Order6DirectPowerAvailableV3Sources.S6_2758
import SemigroupBasis.Generated.Order6DirectPowerAvailableV3Sources.S6_2763
import SemigroupBasis.Generated.Order6FactorIntersection.PositiveParityLongShort.S6_2849
import SemigroupBasis.Generated.Order6FactorPairResidualV3.S6_2847_A47f45831945d_Part01
import SemigroupBasis.Generated.Order6FactorPairS2S5196Targets
import SemigroupBasis.Generated.Order6FactorPairS3_6opS5_209Corrected.S6_2737
import SemigroupBasis.Generated.Order6FactorPairS3_6opS5_209Corrected.S6_2738
import SemigroupBasis.Generated.Order6FactorPairS3_6opS5_209Transport.S6_2750
import SemigroupBasis.Generated.Order6FactorPairSharedFamilies
import SemigroupBasis.Generated.Order6GenericCASRootWrappers.S6_2803
import SemigroupBasis.Generated.Order6RouteLocalRootAdapters
import SemigroupBasis.Order6ResidualReleaseV3.DirectPowerUnlocked25.S6_2844
import research.formalization.order6.extension.order6_extension_2026_06_12_l5_extension_v2.Order6ExtensionTransfersPart01
import research.formalization.order6.extension.order6_extension_2026_06_12_l5_extension_v4.Order6ExtensionTransfersPart01

/-!
# Census shard 019: classes `[6, 2701]` to `[6, 2850]`

For each class, the claim `Classified` from one endpoint theorem of the
development. The first alternative that checks is used: the endpoint for the
semigroup with the catalogue table, or for its opposite (the transposed table).
Generated by `scripts/generate_census.py`.
-/

set_option maxRecDepth 8192

namespace SemiBase.Census

theorem S6_2701 : Classified Catalogue.Order6.S6_2701 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2701.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2701.representative_basis)) (by decide +kernel)

theorem S6_2702 : Classified Catalogue.Order6.S6_2702 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day7.LeeZhang.Sigma14.Absorb.representative_basis2702) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day7.LeeZhang.Sigma14.Absorb.representative_basis2702)) (by decide +kernel)

theorem S6_2703 : Classified Catalogue.Order6.S6_2703 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2703.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2703.representative_basis)) (by decide +kernel)

theorem S6_2704 : Classified Catalogue.Order6.S6_2704 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2704.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2704.representative_basis)) (by decide +kernel)

theorem S6_2705 : Classified Catalogue.Order6.S6_2705 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day7.LeeZhang.Sigma14.Swap.representative_basis2705) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day7.LeeZhang.Sigma14.Swap.representative_basis2705)) (by decide +kernel)

theorem S6_2706 : Classified Catalogue.Order6.S6_2706 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day7.LeeZhang.Msg0430.pair2706_representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day7.LeeZhang.Msg0430.pair2706_representative_basis)) (by decide +kernel)

theorem S6_2707 : Classified Catalogue.Order6.S6_2707 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2707.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2707.representative_basis)) (by decide +kernel)

theorem S6_2708 : Classified Catalogue.Order6.S6_2708 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day7.LeeZhang.S6_2708.Sigma12.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day7.LeeZhang.S6_2708.Sigma12.representative_basis)) (by decide +kernel)

theorem S6_2709 : Classified Catalogue.Order6.S6_2709 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_2709.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_2709.representative_basis)) (by decide +kernel)

theorem S6_2710 : Classified Catalogue.Order6.S6_2710 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2710.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2710.representative_basis)) (by decide +kernel)

theorem S6_2711 : Classified Catalogue.Order6.S6_2711 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2711.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2711.representative_basis)) (by decide +kernel)

theorem S6_2712 : Classified Catalogue.Order6.S6_2712 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2712.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2712.representative_basis)) (by decide +kernel)

theorem S6_2713 : Classified Catalogue.Order6.S6_2713 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2713.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2713.representative_basis)) (by decide +kernel)

theorem S6_2714 : Classified Catalogue.Order6.S6_2714 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2714.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2714.representative_basis)) (by decide +kernel)

theorem S6_2715 : Classified Catalogue.Order6.S6_2715 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2715.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2715.representative_basis)) (by decide +kernel)

theorem S6_2716 : Classified Catalogue.Order6.S6_2716 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_2716.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_2716.representative_basis)) (by decide +kernel)

theorem S6_2717 : Classified Catalogue.Order6.S6_2717 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2717.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2717.representative_basis)) (by decide +kernel)

theorem S6_2718 : Classified Catalogue.Order6.S6_2718 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2718.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2718.representative_basis)) (by decide +kernel)

theorem S6_2719 : Classified Catalogue.Order6.S6_2719 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2719.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2719.representative_basis)) (by decide +kernel)

theorem S6_2720 : Classified Catalogue.Order6.S6_2720 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2720.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2720.representative_basis)) (by decide +kernel)

theorem S6_2721 : Classified Catalogue.Order6.S6_2721 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2721.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2721.representative_basis)) (by decide +kernel)

theorem S6_2722 : Classified Catalogue.Order6.S6_2722 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2722.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2722.representative_basis)) (by decide +kernel)

theorem S6_2723 : Classified Catalogue.Order6.S6_2723 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2723.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2723.representative_basis)) (by decide +kernel)

theorem S6_2724 : Classified Catalogue.Order6.S6_2724 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_2724.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_2724.representative_basis)) (by decide +kernel)

theorem S6_2725 : Classified Catalogue.Order6.S6_2725 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2725.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2725.representative_basis)) (by decide +kernel)

theorem S6_2726 : Classified Catalogue.Order6.S6_2726 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV4.S6_2726.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV4.S6_2726.representative_basis)) (by decide +kernel)

theorem S6_2727 : Classified Catalogue.Order6.S6_2727 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2727.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2727.representative_basis)) (by decide +kernel)

theorem S6_2728 : Classified Catalogue.Order6.S6_2728 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2728.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2728.representative_basis)) (by decide +kernel)

theorem S6_2729 : Classified Catalogue.Order6.S6_2729 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2729.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2729.representative_basis)) (by decide +kernel)

theorem S6_2730 : Classified Catalogue.Order6.S6_2730 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2730.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2730.representative_basis)) (by decide +kernel)

theorem S6_2731 : Classified Catalogue.Order6.S6_2731 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV4.S6_2731.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV4.S6_2731.representative_basis)) (by decide +kernel)

theorem S6_2732 : Classified Catalogue.Order6.S6_2732 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2732.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2732.representative_basis)) (by decide +kernel)

theorem S6_2733 : Classified Catalogue.Order6.S6_2733 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2733.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2733.representative_basis)) (by decide +kernel)

theorem S6_2734 : Classified Catalogue.Order6.S6_2734 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2734.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2734.representative_basis)) (by decide +kernel)

theorem S6_2735 : Classified Catalogue.Order6.S6_2735 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2735.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2735.representative_basis)) (by decide +kernel)

theorem S6_2736 : Classified Catalogue.Order6.S6_2736 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV4.S6_2736.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV4.S6_2736.representative_basis)) (by decide +kernel)

theorem S6_2737 : Classified Catalogue.Order6.S6_2737 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FactorPairS3_6opS5_209Corrected.S6_2737.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FactorPairS3_6opS5_209Corrected.S6_2737.representative_basis)) (by decide +kernel)

theorem S6_2738 : Classified Catalogue.Order6.S6_2738 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FactorPairS3_6opS5_209Corrected.S6_2738.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FactorPairS3_6opS5_209Corrected.S6_2738.representative_basis)) (by decide +kernel)

theorem S6_2739 : Classified Catalogue.Order6.S6_2739 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2739.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2739.representative_basis)) (by decide +kernel)

theorem S6_2740 : Classified Catalogue.Order6.S6_2740 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2740.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2740.representative_basis)) (by decide +kernel)

theorem S6_2741 : Classified Catalogue.Order6.S6_2741 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6FinalMarkerM2Roots.S6_2741.basis_complete) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6FinalMarkerM2Roots.S6_2741.basis_complete)) (by decide +kernel)

theorem S6_2742 : Classified Catalogue.Order6.S6_2742 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6FinalMarkerM2Roots.S6_2742.basis_complete) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6FinalMarkerM2Roots.S6_2742.basis_complete)) (by decide +kernel)

theorem S6_2743 : Classified Catalogue.Order6.S6_2743 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV4.S6_2743.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV4.S6_2743.representative_basis)) (by decide +kernel)

theorem S6_2744 : Classified Catalogue.Order6.S6_2744 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2744.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2744.representative_basis)) (by decide +kernel)

theorem S6_2745 : Classified Catalogue.Order6.S6_2745 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV4.S6_2745.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV4.S6_2745.representative_basis)) (by decide +kernel)

theorem S6_2746 : Classified Catalogue.Order6.S6_2746 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2746.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2746.representative_basis)) (by decide +kernel)

theorem S6_2747 : Classified Catalogue.Order6.S6_2747 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2747.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2747.representative_basis)) (by decide +kernel)

theorem S6_2748 : Classified Catalogue.Order6.S6_2748 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2748.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2748.representative_basis)) (by decide +kernel)

theorem S6_2749 : Classified Catalogue.Order6.S6_2749 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV4.S6_2749.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV4.S6_2749.representative_basis)) (by decide +kernel)

theorem S6_2750 : Classified Catalogue.Order6.S6_2750 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FactorPairS3_6opS5_209Transport.S6_2750.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FactorPairS3_6opS5_209Transport.S6_2750.representative_basis)) (by decide +kernel)

theorem S6_2751 : Classified Catalogue.Order6.S6_2751 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2751.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2751.representative_basis)) (by decide +kernel)

theorem S6_2752 : Classified Catalogue.Order6.S6_2752 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2752.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2752.representative_basis)) (by decide +kernel)

theorem S6_2753 : Classified Catalogue.Order6.S6_2753 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6FinalMarkerM2Roots.S6_2753.basis_complete) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6FinalMarkerM2Roots.S6_2753.basis_complete)) (by decide +kernel)

theorem S6_2754 : Classified Catalogue.Order6.S6_2754 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6FinalMarkerM2Roots.S6_2754.basis_complete) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6FinalMarkerM2Roots.S6_2754.basis_complete)) (by decide +kernel)

theorem S6_2755 : Classified Catalogue.Order6.S6_2755 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV4.S6_2755.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV4.S6_2755.representative_basis)) (by decide +kernel)

theorem S6_2756 : Classified Catalogue.Order6.S6_2756 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2756.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2756.representative_basis)) (by decide +kernel)

theorem S6_2757 : Classified Catalogue.Order6.S6_2757 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV4.S6_2757.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV4.S6_2757.representative_basis)) (by decide +kernel)

theorem S6_2758 : Classified Catalogue.Order6.S6_2758 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3Sources.S6_2758.basis_complete) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3Sources.S6_2758.basis_complete)) (by decide +kernel)

theorem S6_2759 : Classified Catalogue.Order6.S6_2759 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2759.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2759.representative_basis)) (by decide +kernel)

theorem S6_2760 : Classified Catalogue.Order6.S6_2760 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6FinalMarkerM2Roots.S6_2760.basis_complete) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6FinalMarkerM2Roots.S6_2760.basis_complete)) (by decide +kernel)

theorem S6_2761 : Classified Catalogue.Order6.S6_2761 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV4.S6_2761.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV4.S6_2761.representative_basis)) (by decide +kernel)

theorem S6_2762 : Classified Catalogue.Order6.S6_2762 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2762.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2762.representative_basis)) (by decide +kernel)

theorem S6_2763 : Classified Catalogue.Order6.S6_2763 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3Sources.S6_2763.basis_complete) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3Sources.S6_2763.basis_complete)) (by decide +kernel)

theorem S6_2764 : Classified Catalogue.Order6.S6_2764 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6FinalMarkerM2OppositeLeftRoots.S6_2764.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6FinalMarkerM2OppositeLeftRoots.S6_2764.representative_basis)) (by decide +kernel)

theorem S6_2765 : Classified Catalogue.Order6.S6_2765 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2765.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2765.representative_basis)) (by decide +kernel)

theorem S6_2766 : Classified Catalogue.Order6.S6_2766 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV4.S6_2766.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV4.S6_2766.representative_basis)) (by decide +kernel)

theorem S6_2767 : Classified Catalogue.Order6.S6_2767 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2767.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2767.representative_basis)) (by decide +kernel)

theorem S6_2768 : Classified Catalogue.Order6.S6_2768 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2768.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2768.representative_basis)) (by decide +kernel)

theorem S6_2769 : Classified Catalogue.Order6.S6_2769 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2769.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2769.representative_basis)) (by decide +kernel)

theorem S6_2770 : Classified Catalogue.Order6.S6_2770 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV4.S6_2770.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV4.S6_2770.representative_basis)) (by decide +kernel)

theorem S6_2771 : Classified Catalogue.Order6.S6_2771 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6RouteLocalRootAdapters.S6_2771.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6RouteLocalRootAdapters.S6_2771.representative_basis)) (by decide +kernel)

theorem S6_2772 : Classified Catalogue.Order6.S6_2772 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6RouteLocalRootAdapters.S6_2772.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6RouteLocalRootAdapters.S6_2772.representative_basis)) (by decide +kernel)

theorem S6_2773 : Classified Catalogue.Order6.S6_2773 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6RouteLocalRootAdapters.S6_2773.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6RouteLocalRootAdapters.S6_2773.representative_basis)) (by decide +kernel)

theorem S6_2774 : Classified Catalogue.Order6.S6_2774 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_2763_Ad4b303415746_Part01.S6_2774.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_2763_Ad4b303415746_Part01.S6_2774.representative_basis)) (by decide +kernel)

theorem S6_2775 : Classified Catalogue.Order6.S6_2775 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2775.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2775.representative_basis)) (by decide +kernel)

theorem S6_2776 : Classified Catalogue.Order6.S6_2776 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2776.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2776.representative_basis)) (by decide +kernel)

theorem S6_2777 : Classified Catalogue.Order6.S6_2777 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2777.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2777.representative_basis)) (by decide +kernel)

theorem S6_2778 : Classified Catalogue.Order6.S6_2778 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6SporadicSection17.C5C6.S6_2778.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6SporadicSection17.C5C6.S6_2778.representative_basis)) (by decide +kernel)

theorem S6_2779 : Classified Catalogue.Order6.S6_2779 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6SporadicSection17.C5C6.S6_2779.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6SporadicSection17.C5C6.S6_2779.representative_basis)) (by decide +kernel)

theorem S6_2780 : Classified Catalogue.Order6.S6_2780 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_2763_Ad4b303415746_Part01.S6_2780.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_2763_Ad4b303415746_Part01.S6_2780.representative_basis)) (by decide +kernel)

theorem S6_2781 : Classified Catalogue.Order6.S6_2781 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2781.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2781.representative_basis)) (by decide +kernel)

theorem S6_2782 : Classified Catalogue.Order6.S6_2782 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2782.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2782.representative_basis)) (by decide +kernel)

theorem S6_2783 : Classified Catalogue.Order6.S6_2783 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV4.S6_2783.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV4.S6_2783.representative_basis)) (by decide +kernel)

theorem S6_2784 : Classified Catalogue.Order6.S6_2784 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_2758_Ad4b303415746_Part01.S6_2784.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_2758_Ad4b303415746_Part01.S6_2784.representative_basis)) (by decide +kernel)

theorem S6_2785 : Classified Catalogue.Order6.S6_2785 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV4.S6_2785.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV4.S6_2785.representative_basis)) (by decide +kernel)

theorem S6_2786 : Classified Catalogue.Order6.S6_2786 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2786.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2786.representative_basis)) (by decide +kernel)

theorem S6_2787 : Classified Catalogue.Order6.S6_2787 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2787.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2787.representative_basis)) (by decide +kernel)

theorem S6_2788 : Classified Catalogue.Order6.S6_2788 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_2763_Ad4b303415746_Part01.S6_2788.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_2763_Ad4b303415746_Part01.S6_2788.representative_basis)) (by decide +kernel)

theorem S6_2789 : Classified Catalogue.Order6.S6_2789 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV4.S6_2789.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV4.S6_2789.representative_basis)) (by decide +kernel)

theorem S6_2790 : Classified Catalogue.Order6.S6_2790 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2790.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2790.representative_basis)) (by decide +kernel)

theorem S6_2791 : Classified Catalogue.Order6.S6_2791 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2791.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2791.representative_basis)) (by decide +kernel)

theorem S6_2792 : Classified Catalogue.Order6.S6_2792 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV4.S6_2792.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV4.S6_2792.representative_basis)) (by decide +kernel)

theorem S6_2793 : Classified Catalogue.Order6.S6_2793 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2793.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2793.representative_basis)) (by decide +kernel)

theorem S6_2794 : Classified Catalogue.Order6.S6_2794 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2794.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2794.representative_basis)) (by decide +kernel)

theorem S6_2795 : Classified Catalogue.Order6.S6_2795 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV4.S6_2795.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV4.S6_2795.representative_basis)) (by decide +kernel)

theorem S6_2796 : Classified Catalogue.Order6.S6_2796 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2796.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2796.representative_basis)) (by decide +kernel)

theorem S6_2797 : Classified Catalogue.Order6.S6_2797 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day7.LeeZhang.Msg0442Cyclic.pair2797_representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day7.LeeZhang.Msg0442Cyclic.pair2797_representative_basis)) (by decide +kernel)

theorem S6_2798 : Classified Catalogue.Order6.S6_2798 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day7.LeeZhang.Msg0442Cyclic.pair2798_representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day7.LeeZhang.Msg0442Cyclic.pair2798_representative_basis)) (by decide +kernel)

theorem S6_2799 : Classified Catalogue.Order6.S6_2799 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2799.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2799.representative_basis)) (by decide +kernel)

theorem S6_2800 : Classified Catalogue.Order6.S6_2800 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6LongSupportThresholdRoots.S6_2800.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6LongSupportThresholdRoots.S6_2800.representative_basis)) (by decide +kernel)

theorem S6_2801 : Classified Catalogue.Order6.S6_2801 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2801.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2801.representative_basis)) (by decide +kernel)

theorem S6_2802 : Classified Catalogue.Order6.S6_2802 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6GenericCASSubdirectS6_2802.basisFor) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6GenericCASSubdirectS6_2802.basisFor)) (by decide +kernel)

theorem S6_2803 : Classified Catalogue.Order6.S6_2803 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6GenericCASRootWrappers.S6_2803.opposite_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6GenericCASRootWrappers.S6_2803.opposite_basis)) (by decide +kernel)

theorem S6_2804 : Classified Catalogue.Order6.S6_2804 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2804.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2804.representative_basis)) (by decide +kernel)

theorem S6_2805 : Classified Catalogue.Order6.S6_2805 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2805.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2805.representative_basis)) (by decide +kernel)

theorem S6_2806 : Classified Catalogue.Order6.S6_2806 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2806.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2806.representative_basis)) (by decide +kernel)

theorem S6_2807 : Classified Catalogue.Order6.S6_2807 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2807.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2807.representative_basis)) (by decide +kernel)

theorem S6_2808 : Classified Catalogue.Order6.S6_2808 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FactorPairSharedFamilies.S6_2808.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FactorPairSharedFamilies.S6_2808.representative_basis)) (by decide +kernel)

theorem S6_2809 : Classified Catalogue.Order6.S6_2809 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2809.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2809.representative_basis)) (by decide +kernel)

theorem S6_2810 : Classified Catalogue.Order6.S6_2810 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FactorPairSharedFamilies.S6_2810.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FactorPairSharedFamilies.S6_2810.representative_basis)) (by decide +kernel)

theorem S6_2811 : Classified Catalogue.Order6.S6_2811 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2811.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2811.representative_basis)) (by decide +kernel)

theorem S6_2812 : Classified Catalogue.Order6.S6_2812 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6RouteLocalRootAdapters.S6_2812.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6RouteLocalRootAdapters.S6_2812.representative_basis)) (by decide +kernel)

theorem S6_2813 : Classified Catalogue.Order6.S6_2813 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2813.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2813.representative_basis)) (by decide +kernel)

theorem S6_2814 : Classified Catalogue.Order6.S6_2814 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FactorPairSharedFamilies.S6_2814.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FactorPairSharedFamilies.S6_2814.representative_basis)) (by decide +kernel)

theorem S6_2815 : Classified Catalogue.Order6.S6_2815 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2815.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2815.representative_basis)) (by decide +kernel)

theorem S6_2816 : Classified Catalogue.Order6.S6_2816 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_2816.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_2816.representative_basis)) (by decide +kernel)

theorem S6_2817 : Classified Catalogue.Order6.S6_2817 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2817.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2817.representative_basis)) (by decide +kernel)

theorem S6_2818 : Classified Catalogue.Order6.S6_2818 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2818.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2818.representative_basis)) (by decide +kernel)

theorem S6_2819 : Classified Catalogue.Order6.S6_2819 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2819.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2819.representative_basis)) (by decide +kernel)

theorem S6_2820 : Classified Catalogue.Order6.S6_2820 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_2820.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_2820.representative_basis)) (by decide +kernel)

theorem S6_2821 : Classified Catalogue.Order6.S6_2821 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2821.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2821.representative_basis)) (by decide +kernel)

theorem S6_2822 : Classified Catalogue.Order6.S6_2822 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2822.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2822.representative_basis)) (by decide +kernel)

theorem S6_2823 : Classified Catalogue.Order6.S6_2823 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2823.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2823.representative_basis)) (by decide +kernel)

theorem S6_2824 : Classified Catalogue.Order6.S6_2824 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_2824.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_2824.representative_basis)) (by decide +kernel)

theorem S6_2825 : Classified Catalogue.Order6.S6_2825 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_2599_Ad4b303415746_Part01.S6_2825.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_2599_Ad4b303415746_Part01.S6_2825.representative_basis)) (by decide +kernel)

theorem S6_2826 : Classified Catalogue.Order6.S6_2826 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2826.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2826.representative_basis)) (by decide +kernel)

theorem S6_2827 : Classified Catalogue.Order6.S6_2827 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2827.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2827.representative_basis)) (by decide +kernel)

theorem S6_2828 : Classified Catalogue.Order6.S6_2828 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2828.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2828.representative_basis)) (by decide +kernel)

theorem S6_2829 : Classified Catalogue.Order6.S6_2829 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_2599_Ad4b303415746_Part01.S6_2829.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_2599_Ad4b303415746_Part01.S6_2829.representative_basis)) (by decide +kernel)

theorem S6_2830 : Classified Catalogue.Order6.S6_2830 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2830.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2830.representative_basis)) (by decide +kernel)

theorem S6_2831 : Classified Catalogue.Order6.S6_2831 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2831.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2831.representative_basis)) (by decide +kernel)

theorem S6_2832 : Classified Catalogue.Order6.S6_2832 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_2832.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_2832.representative_basis)) (by decide +kernel)

theorem S6_2833 : Classified Catalogue.Order6.S6_2833 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2833.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2833.representative_basis)) (by decide +kernel)

theorem S6_2834 : Classified Catalogue.Order6.S6_2834 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2834.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2834.representative_basis)) (by decide +kernel)

theorem S6_2835 : Classified Catalogue.Order6.S6_2835 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_2599_Ad4b303415746_Part01.S6_2835.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_2599_Ad4b303415746_Part01.S6_2835.representative_basis)) (by decide +kernel)

theorem S6_2836 : Classified Catalogue.Order6.S6_2836 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_2836.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_2836.representative_basis)) (by decide +kernel)

theorem S6_2837 : Classified Catalogue.Order6.S6_2837 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2837.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2837.representative_basis)) (by decide +kernel)

theorem S6_2838 : Classified Catalogue.Order6.S6_2838 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2838.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2838.representative_basis)) (by decide +kernel)

theorem S6_2839 : Classified Catalogue.Order6.S6_2839 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_2839.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_2839.representative_basis)) (by decide +kernel)

theorem S6_2840 : Classified Catalogue.Order6.S6_2840 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2840.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2840.representative_basis)) (by decide +kernel)

theorem S6_2841 : Classified Catalogue.Order6.S6_2841 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2841.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2841.representative_basis)) (by decide +kernel)

theorem S6_2842 : Classified Catalogue.Order6.S6_2842 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_2842.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_2842.representative_basis)) (by decide +kernel)

theorem S6_2843 : Classified Catalogue.Order6.S6_2843 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2843.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2843.representative_basis)) (by decide +kernel)

theorem S6_2844 : Classified Catalogue.Order6.S6_2844 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Order6ResidualReleaseV3.DirectPowerUnlocked25.S6_2844.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Order6ResidualReleaseV3.DirectPowerUnlocked25.S6_2844.representative_basis)) (by decide +kernel)

theorem S6_2845 : Classified Catalogue.Order6.S6_2845 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2845.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2845.representative_basis)) (by decide +kernel)

theorem S6_2846 : Classified Catalogue.Order6.S6_2846 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2846.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2846.representative_basis)) (by decide +kernel)

theorem S6_2847 : Classified Catalogue.Order6.S6_2847 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FactorPairS2S5196Targets.S6_2847.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FactorPairS2S5196Targets.S6_2847.representative_basis)) (by decide +kernel)

theorem S6_2848 : Classified Catalogue.Order6.S6_2848 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FactorPairResidualV3.S6_2847_A47f45831945d_Part01.S6_2848.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FactorPairResidualV3.S6_2847_A47f45831945d_Part01.S6_2848.representative_basis)) (by decide +kernel)

theorem S6_2849 : Classified Catalogue.Order6.S6_2849 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FactorIntersection.PositiveParityLongShort.S6_2849.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FactorIntersection.PositiveParityLongShort.S6_2849.representative_basis)) (by decide +kernel)

theorem S6_2850 : Classified Catalogue.Order6.S6_2850 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6GenericCASSubdirectS6_2850.basisFor) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6GenericCASSubdirectS6_2850.basisFor)) (by decide +kernel)

/-- Every class of part 019 of the catalogue is classified. -/
theorem shard019 : AllClassified Catalogue.Order6.part019 :=
  AllClassified.cons S6_2701 <|
  AllClassified.cons S6_2702 <|
  AllClassified.cons S6_2703 <|
  AllClassified.cons S6_2704 <|
  AllClassified.cons S6_2705 <|
  AllClassified.cons S6_2706 <|
  AllClassified.cons S6_2707 <|
  AllClassified.cons S6_2708 <|
  AllClassified.cons S6_2709 <|
  AllClassified.cons S6_2710 <|
  AllClassified.cons S6_2711 <|
  AllClassified.cons S6_2712 <|
  AllClassified.cons S6_2713 <|
  AllClassified.cons S6_2714 <|
  AllClassified.cons S6_2715 <|
  AllClassified.cons S6_2716 <|
  AllClassified.cons S6_2717 <|
  AllClassified.cons S6_2718 <|
  AllClassified.cons S6_2719 <|
  AllClassified.cons S6_2720 <|
  AllClassified.cons S6_2721 <|
  AllClassified.cons S6_2722 <|
  AllClassified.cons S6_2723 <|
  AllClassified.cons S6_2724 <|
  AllClassified.cons S6_2725 <|
  AllClassified.cons S6_2726 <|
  AllClassified.cons S6_2727 <|
  AllClassified.cons S6_2728 <|
  AllClassified.cons S6_2729 <|
  AllClassified.cons S6_2730 <|
  AllClassified.cons S6_2731 <|
  AllClassified.cons S6_2732 <|
  AllClassified.cons S6_2733 <|
  AllClassified.cons S6_2734 <|
  AllClassified.cons S6_2735 <|
  AllClassified.cons S6_2736 <|
  AllClassified.cons S6_2737 <|
  AllClassified.cons S6_2738 <|
  AllClassified.cons S6_2739 <|
  AllClassified.cons S6_2740 <|
  AllClassified.cons S6_2741 <|
  AllClassified.cons S6_2742 <|
  AllClassified.cons S6_2743 <|
  AllClassified.cons S6_2744 <|
  AllClassified.cons S6_2745 <|
  AllClassified.cons S6_2746 <|
  AllClassified.cons S6_2747 <|
  AllClassified.cons S6_2748 <|
  AllClassified.cons S6_2749 <|
  AllClassified.cons S6_2750 <|
  AllClassified.cons S6_2751 <|
  AllClassified.cons S6_2752 <|
  AllClassified.cons S6_2753 <|
  AllClassified.cons S6_2754 <|
  AllClassified.cons S6_2755 <|
  AllClassified.cons S6_2756 <|
  AllClassified.cons S6_2757 <|
  AllClassified.cons S6_2758 <|
  AllClassified.cons S6_2759 <|
  AllClassified.cons S6_2760 <|
  AllClassified.cons S6_2761 <|
  AllClassified.cons S6_2762 <|
  AllClassified.cons S6_2763 <|
  AllClassified.cons S6_2764 <|
  AllClassified.cons S6_2765 <|
  AllClassified.cons S6_2766 <|
  AllClassified.cons S6_2767 <|
  AllClassified.cons S6_2768 <|
  AllClassified.cons S6_2769 <|
  AllClassified.cons S6_2770 <|
  AllClassified.cons S6_2771 <|
  AllClassified.cons S6_2772 <|
  AllClassified.cons S6_2773 <|
  AllClassified.cons S6_2774 <|
  AllClassified.cons S6_2775 <|
  AllClassified.cons S6_2776 <|
  AllClassified.cons S6_2777 <|
  AllClassified.cons S6_2778 <|
  AllClassified.cons S6_2779 <|
  AllClassified.cons S6_2780 <|
  AllClassified.cons S6_2781 <|
  AllClassified.cons S6_2782 <|
  AllClassified.cons S6_2783 <|
  AllClassified.cons S6_2784 <|
  AllClassified.cons S6_2785 <|
  AllClassified.cons S6_2786 <|
  AllClassified.cons S6_2787 <|
  AllClassified.cons S6_2788 <|
  AllClassified.cons S6_2789 <|
  AllClassified.cons S6_2790 <|
  AllClassified.cons S6_2791 <|
  AllClassified.cons S6_2792 <|
  AllClassified.cons S6_2793 <|
  AllClassified.cons S6_2794 <|
  AllClassified.cons S6_2795 <|
  AllClassified.cons S6_2796 <|
  AllClassified.cons S6_2797 <|
  AllClassified.cons S6_2798 <|
  AllClassified.cons S6_2799 <|
  AllClassified.cons S6_2800 <|
  AllClassified.cons S6_2801 <|
  AllClassified.cons S6_2802 <|
  AllClassified.cons S6_2803 <|
  AllClassified.cons S6_2804 <|
  AllClassified.cons S6_2805 <|
  AllClassified.cons S6_2806 <|
  AllClassified.cons S6_2807 <|
  AllClassified.cons S6_2808 <|
  AllClassified.cons S6_2809 <|
  AllClassified.cons S6_2810 <|
  AllClassified.cons S6_2811 <|
  AllClassified.cons S6_2812 <|
  AllClassified.cons S6_2813 <|
  AllClassified.cons S6_2814 <|
  AllClassified.cons S6_2815 <|
  AllClassified.cons S6_2816 <|
  AllClassified.cons S6_2817 <|
  AllClassified.cons S6_2818 <|
  AllClassified.cons S6_2819 <|
  AllClassified.cons S6_2820 <|
  AllClassified.cons S6_2821 <|
  AllClassified.cons S6_2822 <|
  AllClassified.cons S6_2823 <|
  AllClassified.cons S6_2824 <|
  AllClassified.cons S6_2825 <|
  AllClassified.cons S6_2826 <|
  AllClassified.cons S6_2827 <|
  AllClassified.cons S6_2828 <|
  AllClassified.cons S6_2829 <|
  AllClassified.cons S6_2830 <|
  AllClassified.cons S6_2831 <|
  AllClassified.cons S6_2832 <|
  AllClassified.cons S6_2833 <|
  AllClassified.cons S6_2834 <|
  AllClassified.cons S6_2835 <|
  AllClassified.cons S6_2836 <|
  AllClassified.cons S6_2837 <|
  AllClassified.cons S6_2838 <|
  AllClassified.cons S6_2839 <|
  AllClassified.cons S6_2840 <|
  AllClassified.cons S6_2841 <|
  AllClassified.cons S6_2842 <|
  AllClassified.cons S6_2843 <|
  AllClassified.cons S6_2844 <|
  AllClassified.cons S6_2845 <|
  AllClassified.cons S6_2846 <|
  AllClassified.cons S6_2847 <|
  AllClassified.cons S6_2848 <|
  AllClassified.cons S6_2849 <|
  AllClassified.cons S6_2850 <|
  AllClassified.nil

end SemiBase.Census
