import SemiBase.Statement
import SemiBase.Catalogue.Order6.Part048
import Order6FinalL5TransferV3.Part162
import Order6FinalL5TransferV3.Part163
import Order6FinalL5TransferV3.Part164
import SemigroupBasis.CoRoots.Order6Day7.S2_4.SeedS5_303
import SemigroupBasis.Generated.Order6DirectPowerAvailableV3Sources.S6_7120
import SemigroupBasis.Generated.Order6DirectPowerAvailableV3Sources.S6_7157
import SemigroupBasis.Generated.Order6DirectPowerAvailableV3Sources.S6_7167
import SemigroupBasis.Generated.Order6DivisorTransfersPart32
import SemigroupBasis.Generated.Order6EmbeddingTransfersPart07
import SemigroupBasis.Generated.Order6EmbeddingTransfersPart08
import research.formalization.order6.extension.order6_extension_2026_06_12_l5_extension_v1.Order6ExtensionTransfersPart06
import research.formalization.order6.extension.order6_extension_2026_06_12_l5_extension_v13.Order6ExtensionTransfersPart01
import research.formalization.order6.extension.order6_extension_2026_06_12_l5_extension_v2.Order6ExtensionTransfersPart03
import research.formalization.order6.extension.order6_extension_2026_06_12_l5_extension_v2.Order6ExtensionTransfersPart04
import research.formalization.order6.extension.order6_extension_2026_06_12_l5_extension_v8.Order6ExtensionTransfersPart01

/-!
# Census shard 048: classes `[6, 7051]` to `[6, 7200]`

For each class, the claim `Classified` from one endpoint theorem of the
development. The first alternative that checks is used: the endpoint for the
semigroup with the catalogue table, or for its opposite (the transposed table).
Generated by `scripts/generate_census.py`.
-/

set_option maxRecDepth 8192

namespace SemiBase.Census

theorem S6_7051 : Classified Catalogue.Order6.S6_7051 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_7051.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_7051.representative_basis)) (by decide +kernel)

theorem S6_7052 : Classified Catalogue.Order6.S6_7052 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV13.S6_7052.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV13.S6_7052.representative_basis)) (by decide +kernel)

theorem S6_7053 : Classified Catalogue.Order6.S6_7053 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_7053.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_7053.representative_basis)) (by decide +kernel)

theorem S6_7054 : Classified Catalogue.Order6.S6_7054 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_7054.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_7054.representative_basis)) (by decide +kernel)

theorem S6_7055 : Classified Catalogue.Order6.S6_7055 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7055.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7055.representative_basis)) (by decide +kernel)

theorem S6_7056 : Classified Catalogue.Order6.S6_7056 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7056.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7056.representative_basis)) (by decide +kernel)

theorem S6_7057 : Classified Catalogue.Order6.S6_7057 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7057.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7057.representative_basis)) (by decide +kernel)

theorem S6_7058 : Classified Catalogue.Order6.S6_7058 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7058.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7058.representative_basis)) (by decide +kernel)

theorem S6_7059 : Classified Catalogue.Order6.S6_7059 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_7059.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_7059.representative_basis)) (by decide +kernel)

theorem S6_7060 : Classified Catalogue.Order6.S6_7060 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7060.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7060.representative_basis)) (by decide +kernel)

theorem S6_7061 : Classified Catalogue.Order6.S6_7061 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_7061.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_7061.representative_basis)) (by decide +kernel)

theorem S6_7062 : Classified Catalogue.Order6.S6_7062 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7062.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7062.representative_basis)) (by decide +kernel)

theorem S6_7063 : Classified Catalogue.Order6.S6_7063 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7063.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7063.representative_basis)) (by decide +kernel)

theorem S6_7064 : Classified Catalogue.Order6.S6_7064 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7064.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7064.representative_basis)) (by decide +kernel)

theorem S6_7065 : Classified Catalogue.Order6.S6_7065 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_7065.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_7065.representative_basis)) (by decide +kernel)

theorem S6_7066 : Classified Catalogue.Order6.S6_7066 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7066.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7066.representative_basis)) (by decide +kernel)

theorem S6_7067 : Classified Catalogue.Order6.S6_7067 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV8.S6_7067.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV8.S6_7067.representative_basis)) (by decide +kernel)

theorem S6_7068 : Classified Catalogue.Order6.S6_7068 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7068.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7068.representative_basis)) (by decide +kernel)

theorem S6_7069 : Classified Catalogue.Order6.S6_7069 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_7069.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_7069.representative_basis)) (by decide +kernel)

theorem S6_7070 : Classified Catalogue.Order6.S6_7070 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7070.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7070.representative_basis)) (by decide +kernel)

theorem S6_7071 : Classified Catalogue.Order6.S6_7071 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_7071.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_7071.representative_basis)) (by decide +kernel)

theorem S6_7072 : Classified Catalogue.Order6.S6_7072 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_7072.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_7072.representative_basis)) (by decide +kernel)

theorem S6_7073 : Classified Catalogue.Order6.S6_7073 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_7073.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_7073.representative_basis)) (by decide +kernel)

theorem S6_7074 : Classified Catalogue.Order6.S6_7074 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV8.S6_7074.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV8.S6_7074.representative_basis)) (by decide +kernel)

theorem S6_7075 : Classified Catalogue.Order6.S6_7075 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7075.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7075.representative_basis)) (by decide +kernel)

theorem S6_7076 : Classified Catalogue.Order6.S6_7076 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_7076.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_7076.representative_basis)) (by decide +kernel)

theorem S6_7077 : Classified Catalogue.Order6.S6_7077 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7077.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7077.representative_basis)) (by decide +kernel)

theorem S6_7078 : Classified Catalogue.Order6.S6_7078 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_7078.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_7078.representative_basis)) (by decide +kernel)

theorem S6_7079 : Classified Catalogue.Order6.S6_7079 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_7079.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_7079.representative_basis)) (by decide +kernel)

theorem S6_7080 : Classified Catalogue.Order6.S6_7080 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_7080.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_7080.representative_basis)) (by decide +kernel)

theorem S6_7081 : Classified Catalogue.Order6.S6_7081 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV8.S6_7081.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV8.S6_7081.representative_basis)) (by decide +kernel)

theorem S6_7082 : Classified Catalogue.Order6.S6_7082 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7082.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7082.representative_basis)) (by decide +kernel)

theorem S6_7083 : Classified Catalogue.Order6.S6_7083 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_7083.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_7083.representative_basis)) (by decide +kernel)

theorem S6_7084 : Classified Catalogue.Order6.S6_7084 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_7084.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_7084.representative_basis)) (by decide +kernel)

theorem S6_7085 : Classified Catalogue.Order6.S6_7085 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_7085.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_7085.representative_basis)) (by decide +kernel)

theorem S6_7086 : Classified Catalogue.Order6.S6_7086 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_7086.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_7086.representative_basis)) (by decide +kernel)

theorem S6_7087 : Classified Catalogue.Order6.S6_7087 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_7087.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_7087.representative_basis)) (by decide +kernel)

theorem S6_7088 : Classified Catalogue.Order6.S6_7088 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7088.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7088.representative_basis)) (by decide +kernel)

theorem S6_7089 : Classified Catalogue.Order6.S6_7089 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7089.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7089.representative_basis)) (by decide +kernel)

theorem S6_7090 : Classified Catalogue.Order6.S6_7090 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7090.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7090.representative_basis)) (by decide +kernel)

theorem S6_7091 : Classified Catalogue.Order6.S6_7091 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7091.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7091.representative_basis)) (by decide +kernel)

theorem S6_7092 : Classified Catalogue.Order6.S6_7092 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7092.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7092.representative_basis)) (by decide +kernel)

theorem S6_7093 : Classified Catalogue.Order6.S6_7093 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV8.S6_7093.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV8.S6_7093.representative_basis)) (by decide +kernel)

theorem S6_7094 : Classified Catalogue.Order6.S6_7094 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7094.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7094.representative_basis)) (by decide +kernel)

theorem S6_7095 : Classified Catalogue.Order6.S6_7095 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7095.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7095.representative_basis)) (by decide +kernel)

theorem S6_7096 : Classified Catalogue.Order6.S6_7096 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7096.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7096.representative_basis)) (by decide +kernel)

theorem S6_7097 : Classified Catalogue.Order6.S6_7097 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7097.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7097.representative_basis)) (by decide +kernel)

theorem S6_7098 : Classified Catalogue.Order6.S6_7098 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV8.S6_7098.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV8.S6_7098.representative_basis)) (by decide +kernel)

theorem S6_7099 : Classified Catalogue.Order6.S6_7099 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7099.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7099.representative_basis)) (by decide +kernel)

theorem S6_7100 : Classified Catalogue.Order6.S6_7100 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7100.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7100.representative_basis)) (by decide +kernel)

theorem S6_7101 : Classified Catalogue.Order6.S6_7101 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7101.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7101.representative_basis)) (by decide +kernel)

theorem S6_7102 : Classified Catalogue.Order6.S6_7102 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV8.S6_7102.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV8.S6_7102.representative_basis)) (by decide +kernel)

theorem S6_7103 : Classified Catalogue.Order6.S6_7103 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7103.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7103.representative_basis)) (by decide +kernel)

theorem S6_7104 : Classified Catalogue.Order6.S6_7104 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_7104.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_7104.representative_basis)) (by decide +kernel)

theorem S6_7105 : Classified Catalogue.Order6.S6_7105 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_7105.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_7105.representative_basis)) (by decide +kernel)

theorem S6_7106 : Classified Catalogue.Order6.S6_7106 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_7106.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_7106.representative_basis)) (by decide +kernel)

theorem S6_7107 : Classified Catalogue.Order6.S6_7107 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV8.S6_7107.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV8.S6_7107.representative_basis)) (by decide +kernel)

theorem S6_7108 : Classified Catalogue.Order6.S6_7108 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_7108.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_7108.representative_basis)) (by decide +kernel)

theorem S6_7109 : Classified Catalogue.Order6.S6_7109 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV8.S6_7109.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV8.S6_7109.representative_basis)) (by decide +kernel)

theorem S6_7110 : Classified Catalogue.Order6.S6_7110 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_7110.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_7110.representative_basis)) (by decide +kernel)

theorem S6_7111 : Classified Catalogue.Order6.S6_7111 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV8.S6_7111.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV8.S6_7111.representative_basis)) (by decide +kernel)

theorem S6_7112 : Classified Catalogue.Order6.S6_7112 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_7112.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_7112.representative_basis)) (by decide +kernel)

theorem S6_7113 : Classified Catalogue.Order6.S6_7113 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_7113.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_7113.representative_basis)) (by decide +kernel)

theorem S6_7114 : Classified Catalogue.Order6.S6_7114 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_7114.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_7114.representative_basis)) (by decide +kernel)

theorem S6_7115 : Classified Catalogue.Order6.S6_7115 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_7115.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_7115.representative_basis)) (by decide +kernel)

theorem S6_7116 : Classified Catalogue.Order6.S6_7116 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_7116.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_7116.representative_basis)) (by decide +kernel)

theorem S6_7117 : Classified Catalogue.Order6.S6_7117 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_7117.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_7117.representative_basis)) (by decide +kernel)

theorem S6_7118 : Classified Catalogue.Order6.S6_7118 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_7118.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_7118.representative_basis)) (by decide +kernel)

theorem S6_7119 : Classified Catalogue.Order6.S6_7119 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_7119.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_7119.representative_basis)) (by decide +kernel)

theorem S6_7120 : Classified Catalogue.Order6.S6_7120 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3Sources.S6_7120.basis_complete) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3Sources.S6_7120.basis_complete)) (by decide +kernel)

theorem S6_7121 : Classified Catalogue.Order6.S6_7121 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_7121.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_7121.representative_basis)) (by decide +kernel)

theorem S6_7122 : Classified Catalogue.Order6.S6_7122 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7122.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7122.representative_basis)) (by decide +kernel)

theorem S6_7123 : Classified Catalogue.Order6.S6_7123 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_7123.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_7123.representative_basis)) (by decide +kernel)

theorem S6_7124 : Classified Catalogue.Order6.S6_7124 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7124.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7124.representative_basis)) (by decide +kernel)

theorem S6_7125 : Classified Catalogue.Order6.S6_7125 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7125.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7125.representative_basis)) (by decide +kernel)

theorem S6_7126 : Classified Catalogue.Order6.S6_7126 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7126.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7126.representative_basis)) (by decide +kernel)

theorem S6_7127 : Classified Catalogue.Order6.S6_7127 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7127.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7127.representative_basis)) (by decide +kernel)

theorem S6_7128 : Classified Catalogue.Order6.S6_7128 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_7128.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_7128.representative_basis)) (by decide +kernel)

theorem S6_7129 : Classified Catalogue.Order6.S6_7129 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7129.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7129.representative_basis)) (by decide +kernel)

theorem S6_7130 : Classified Catalogue.Order6.S6_7130 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7130.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7130.representative_basis)) (by decide +kernel)

theorem S6_7131 : Classified Catalogue.Order6.S6_7131 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7131.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7131.representative_basis)) (by decide +kernel)

theorem S6_7132 : Classified Catalogue.Order6.S6_7132 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_7132.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_7132.representative_basis)) (by decide +kernel)

theorem S6_7133 : Classified Catalogue.Order6.S6_7133 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_7133.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_7133.representative_basis)) (by decide +kernel)

theorem S6_7134 : Classified Catalogue.Order6.S6_7134 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV8.S6_7134.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV8.S6_7134.representative_basis)) (by decide +kernel)

theorem S6_7135 : Classified Catalogue.Order6.S6_7135 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_7135.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_7135.representative_basis)) (by decide +kernel)

theorem S6_7136 : Classified Catalogue.Order6.S6_7136 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV8.S6_7136.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV8.S6_7136.representative_basis)) (by decide +kernel)

theorem S6_7137 : Classified Catalogue.Order6.S6_7137 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_7137.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_7137.representative_basis)) (by decide +kernel)

theorem S6_7138 : Classified Catalogue.Order6.S6_7138 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV8.S6_7138.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV8.S6_7138.representative_basis)) (by decide +kernel)

theorem S6_7139 : Classified Catalogue.Order6.S6_7139 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_7139.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_7139.representative_basis)) (by decide +kernel)

theorem S6_7140 : Classified Catalogue.Order6.S6_7140 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7140.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7140.representative_basis)) (by decide +kernel)

theorem S6_7141 : Classified Catalogue.Order6.S6_7141 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7141.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7141.representative_basis)) (by decide +kernel)

theorem S6_7142 : Classified Catalogue.Order6.S6_7142 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_7142.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_7142.representative_basis)) (by decide +kernel)

theorem S6_7143 : Classified Catalogue.Order6.S6_7143 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7143.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7143.representative_basis)) (by decide +kernel)

theorem S6_7144 : Classified Catalogue.Order6.S6_7144 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_7144.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_7144.representative_basis)) (by decide +kernel)

theorem S6_7145 : Classified Catalogue.Order6.S6_7145 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_7145.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_7145.representative_basis)) (by decide +kernel)

theorem S6_7146 : Classified Catalogue.Order6.S6_7146 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7146.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7146.representative_basis)) (by decide +kernel)

theorem S6_7147 : Classified Catalogue.Order6.S6_7147 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_7147.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_7147.representative_basis)) (by decide +kernel)

theorem S6_7148 : Classified Catalogue.Order6.S6_7148 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7148.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7148.representative_basis)) (by decide +kernel)

theorem S6_7149 : Classified Catalogue.Order6.S6_7149 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_7149.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_7149.representative_basis)) (by decide +kernel)

theorem S6_7150 : Classified Catalogue.Order6.S6_7150 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_7150.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_7150.representative_basis)) (by decide +kernel)

theorem S6_7151 : Classified Catalogue.Order6.S6_7151 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7151.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7151.representative_basis)) (by decide +kernel)

theorem S6_7152 : Classified Catalogue.Order6.S6_7152 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_7152.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_7152.representative_basis)) (by decide +kernel)

theorem S6_7153 : Classified Catalogue.Order6.S6_7153 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_7153.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_7153.representative_basis)) (by decide +kernel)

theorem S6_7154 : Classified Catalogue.Order6.S6_7154 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_7154.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_7154.representative_basis)) (by decide +kernel)

theorem S6_7155 : Classified Catalogue.Order6.S6_7155 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_7155.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_7155.representative_basis)) (by decide +kernel)

theorem S6_7156 : Classified Catalogue.Order6.S6_7156 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_7156.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_7156.representative_basis)) (by decide +kernel)

theorem S6_7157 : Classified Catalogue.Order6.S6_7157 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3Sources.S6_7157.basis_complete) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3Sources.S6_7157.basis_complete)) (by decide +kernel)

theorem S6_7158 : Classified Catalogue.Order6.S6_7158 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_7158.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_7158.representative_basis)) (by decide +kernel)

theorem S6_7159 : Classified Catalogue.Order6.S6_7159 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_7159.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_7159.representative_basis)) (by decide +kernel)

theorem S6_7160 : Classified Catalogue.Order6.S6_7160 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_7160.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_7160.representative_basis)) (by decide +kernel)

theorem S6_7161 : Classified Catalogue.Order6.S6_7161 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_7161.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_7161.representative_basis)) (by decide +kernel)

theorem S6_7162 : Classified Catalogue.Order6.S6_7162 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_7162.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_7162.representative_basis)) (by decide +kernel)

theorem S6_7163 : Classified Catalogue.Order6.S6_7163 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_7163.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_7163.representative_basis)) (by decide +kernel)

theorem S6_7164 : Classified Catalogue.Order6.S6_7164 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_7164.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_7164.representative_basis)) (by decide +kernel)

theorem S6_7165 : Classified Catalogue.Order6.S6_7165 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_7165.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_7165.representative_basis)) (by decide +kernel)

theorem S6_7166 : Classified Catalogue.Order6.S6_7166 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_7166.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_7166.representative_basis)) (by decide +kernel)

theorem S6_7167 : Classified Catalogue.Order6.S6_7167 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3Sources.S6_7167.basis_complete) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3Sources.S6_7167.basis_complete)) (by decide +kernel)

theorem S6_7168 : Classified Catalogue.Order6.S6_7168 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_7168.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_7168.representative_basis)) (by decide +kernel)

theorem S6_7169 : Classified Catalogue.Order6.S6_7169 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_7169.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_7169.representative_basis)) (by decide +kernel)

theorem S6_7170 : Classified Catalogue.Order6.S6_7170 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV8.S6_7170.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV8.S6_7170.representative_basis)) (by decide +kernel)

theorem S6_7171 : Classified Catalogue.Order6.S6_7171 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7171.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7171.representative_basis)) (by decide +kernel)

theorem S6_7172 : Classified Catalogue.Order6.S6_7172 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV8.S6_7172.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV8.S6_7172.representative_basis)) (by decide +kernel)

theorem S6_7173 : Classified Catalogue.Order6.S6_7173 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_7173.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_7173.representative_basis)) (by decide +kernel)

theorem S6_7174 : Classified Catalogue.Order6.S6_7174 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_7174.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_7174.representative_basis)) (by decide +kernel)

theorem S6_7175 : Classified Catalogue.Order6.S6_7175 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV8.S6_7175.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV8.S6_7175.representative_basis)) (by decide +kernel)

theorem S6_7176 : Classified Catalogue.Order6.S6_7176 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV8.S6_7176.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV8.S6_7176.representative_basis)) (by decide +kernel)

theorem S6_7177 : Classified Catalogue.Order6.S6_7177 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7177.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7177.representative_basis)) (by decide +kernel)

theorem S6_7178 : Classified Catalogue.Order6.S6_7178 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV8.S6_7178.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV8.S6_7178.representative_basis)) (by decide +kernel)

theorem S6_7179 : Classified Catalogue.Order6.S6_7179 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_7179.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_7179.representative_basis)) (by decide +kernel)

theorem S6_7180 : Classified Catalogue.Order6.S6_7180 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV8.S6_7180.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV8.S6_7180.representative_basis)) (by decide +kernel)

theorem S6_7181 : Classified Catalogue.Order6.S6_7181 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV8.S6_7181.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV8.S6_7181.representative_basis)) (by decide +kernel)

theorem S6_7182 : Classified Catalogue.Order6.S6_7182 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_7182.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_7182.representative_basis)) (by decide +kernel)

theorem S6_7183 : Classified Catalogue.Order6.S6_7183 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_7183.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_7183.representative_basis)) (by decide +kernel)

theorem S6_7184 : Classified Catalogue.Order6.S6_7184 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day7.S2_4.Rank016.Seed.s6_7184_representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day7.S2_4.Rank016.Seed.s6_7184_representative_basis)) (by decide +kernel)

theorem S6_7185 : Classified Catalogue.Order6.S6_7185 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_7185.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_7185.representative_basis)) (by decide +kernel)

theorem S6_7186 : Classified Catalogue.Order6.S6_7186 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7186.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7186.representative_basis)) (by decide +kernel)

theorem S6_7187 : Classified Catalogue.Order6.S6_7187 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_7187.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_7187.representative_basis)) (by decide +kernel)

theorem S6_7188 : Classified Catalogue.Order6.S6_7188 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7188.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7188.representative_basis)) (by decide +kernel)

theorem S6_7189 : Classified Catalogue.Order6.S6_7189 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7189.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7189.representative_basis)) (by decide +kernel)

theorem S6_7190 : Classified Catalogue.Order6.S6_7190 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_7190.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_7190.representative_basis)) (by decide +kernel)

theorem S6_7191 : Classified Catalogue.Order6.S6_7191 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7191.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7191.representative_basis)) (by decide +kernel)

theorem S6_7192 : Classified Catalogue.Order6.S6_7192 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_7192.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_7192.representative_basis)) (by decide +kernel)

theorem S6_7193 : Classified Catalogue.Order6.S6_7193 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_7193.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_7193.representative_basis)) (by decide +kernel)

theorem S6_7194 : Classified Catalogue.Order6.S6_7194 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_7194.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_7194.representative_basis)) (by decide +kernel)

theorem S6_7195 : Classified Catalogue.Order6.S6_7195 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV8.S6_7195.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV8.S6_7195.representative_basis)) (by decide +kernel)

theorem S6_7196 : Classified Catalogue.Order6.S6_7196 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_7196.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_7196.representative_basis)) (by decide +kernel)

theorem S6_7197 : Classified Catalogue.Order6.S6_7197 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7197.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_7197.representative_basis)) (by decide +kernel)

theorem S6_7198 : Classified Catalogue.Order6.S6_7198 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_7198.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_7198.representative_basis)) (by decide +kernel)

theorem S6_7199 : Classified Catalogue.Order6.S6_7199 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_7199.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_7199.representative_basis)) (by decide +kernel)

theorem S6_7200 : Classified Catalogue.Order6.S6_7200 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_7200.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_7200.representative_basis)) (by decide +kernel)

/-- Every class of part 048 of the catalogue is classified. -/
theorem shard048 : AllClassified Catalogue.Order6.part048 :=
  AllClassified.cons S6_7051 <|
  AllClassified.cons S6_7052 <|
  AllClassified.cons S6_7053 <|
  AllClassified.cons S6_7054 <|
  AllClassified.cons S6_7055 <|
  AllClassified.cons S6_7056 <|
  AllClassified.cons S6_7057 <|
  AllClassified.cons S6_7058 <|
  AllClassified.cons S6_7059 <|
  AllClassified.cons S6_7060 <|
  AllClassified.cons S6_7061 <|
  AllClassified.cons S6_7062 <|
  AllClassified.cons S6_7063 <|
  AllClassified.cons S6_7064 <|
  AllClassified.cons S6_7065 <|
  AllClassified.cons S6_7066 <|
  AllClassified.cons S6_7067 <|
  AllClassified.cons S6_7068 <|
  AllClassified.cons S6_7069 <|
  AllClassified.cons S6_7070 <|
  AllClassified.cons S6_7071 <|
  AllClassified.cons S6_7072 <|
  AllClassified.cons S6_7073 <|
  AllClassified.cons S6_7074 <|
  AllClassified.cons S6_7075 <|
  AllClassified.cons S6_7076 <|
  AllClassified.cons S6_7077 <|
  AllClassified.cons S6_7078 <|
  AllClassified.cons S6_7079 <|
  AllClassified.cons S6_7080 <|
  AllClassified.cons S6_7081 <|
  AllClassified.cons S6_7082 <|
  AllClassified.cons S6_7083 <|
  AllClassified.cons S6_7084 <|
  AllClassified.cons S6_7085 <|
  AllClassified.cons S6_7086 <|
  AllClassified.cons S6_7087 <|
  AllClassified.cons S6_7088 <|
  AllClassified.cons S6_7089 <|
  AllClassified.cons S6_7090 <|
  AllClassified.cons S6_7091 <|
  AllClassified.cons S6_7092 <|
  AllClassified.cons S6_7093 <|
  AllClassified.cons S6_7094 <|
  AllClassified.cons S6_7095 <|
  AllClassified.cons S6_7096 <|
  AllClassified.cons S6_7097 <|
  AllClassified.cons S6_7098 <|
  AllClassified.cons S6_7099 <|
  AllClassified.cons S6_7100 <|
  AllClassified.cons S6_7101 <|
  AllClassified.cons S6_7102 <|
  AllClassified.cons S6_7103 <|
  AllClassified.cons S6_7104 <|
  AllClassified.cons S6_7105 <|
  AllClassified.cons S6_7106 <|
  AllClassified.cons S6_7107 <|
  AllClassified.cons S6_7108 <|
  AllClassified.cons S6_7109 <|
  AllClassified.cons S6_7110 <|
  AllClassified.cons S6_7111 <|
  AllClassified.cons S6_7112 <|
  AllClassified.cons S6_7113 <|
  AllClassified.cons S6_7114 <|
  AllClassified.cons S6_7115 <|
  AllClassified.cons S6_7116 <|
  AllClassified.cons S6_7117 <|
  AllClassified.cons S6_7118 <|
  AllClassified.cons S6_7119 <|
  AllClassified.cons S6_7120 <|
  AllClassified.cons S6_7121 <|
  AllClassified.cons S6_7122 <|
  AllClassified.cons S6_7123 <|
  AllClassified.cons S6_7124 <|
  AllClassified.cons S6_7125 <|
  AllClassified.cons S6_7126 <|
  AllClassified.cons S6_7127 <|
  AllClassified.cons S6_7128 <|
  AllClassified.cons S6_7129 <|
  AllClassified.cons S6_7130 <|
  AllClassified.cons S6_7131 <|
  AllClassified.cons S6_7132 <|
  AllClassified.cons S6_7133 <|
  AllClassified.cons S6_7134 <|
  AllClassified.cons S6_7135 <|
  AllClassified.cons S6_7136 <|
  AllClassified.cons S6_7137 <|
  AllClassified.cons S6_7138 <|
  AllClassified.cons S6_7139 <|
  AllClassified.cons S6_7140 <|
  AllClassified.cons S6_7141 <|
  AllClassified.cons S6_7142 <|
  AllClassified.cons S6_7143 <|
  AllClassified.cons S6_7144 <|
  AllClassified.cons S6_7145 <|
  AllClassified.cons S6_7146 <|
  AllClassified.cons S6_7147 <|
  AllClassified.cons S6_7148 <|
  AllClassified.cons S6_7149 <|
  AllClassified.cons S6_7150 <|
  AllClassified.cons S6_7151 <|
  AllClassified.cons S6_7152 <|
  AllClassified.cons S6_7153 <|
  AllClassified.cons S6_7154 <|
  AllClassified.cons S6_7155 <|
  AllClassified.cons S6_7156 <|
  AllClassified.cons S6_7157 <|
  AllClassified.cons S6_7158 <|
  AllClassified.cons S6_7159 <|
  AllClassified.cons S6_7160 <|
  AllClassified.cons S6_7161 <|
  AllClassified.cons S6_7162 <|
  AllClassified.cons S6_7163 <|
  AllClassified.cons S6_7164 <|
  AllClassified.cons S6_7165 <|
  AllClassified.cons S6_7166 <|
  AllClassified.cons S6_7167 <|
  AllClassified.cons S6_7168 <|
  AllClassified.cons S6_7169 <|
  AllClassified.cons S6_7170 <|
  AllClassified.cons S6_7171 <|
  AllClassified.cons S6_7172 <|
  AllClassified.cons S6_7173 <|
  AllClassified.cons S6_7174 <|
  AllClassified.cons S6_7175 <|
  AllClassified.cons S6_7176 <|
  AllClassified.cons S6_7177 <|
  AllClassified.cons S6_7178 <|
  AllClassified.cons S6_7179 <|
  AllClassified.cons S6_7180 <|
  AllClassified.cons S6_7181 <|
  AllClassified.cons S6_7182 <|
  AllClassified.cons S6_7183 <|
  AllClassified.cons S6_7184 <|
  AllClassified.cons S6_7185 <|
  AllClassified.cons S6_7186 <|
  AllClassified.cons S6_7187 <|
  AllClassified.cons S6_7188 <|
  AllClassified.cons S6_7189 <|
  AllClassified.cons S6_7190 <|
  AllClassified.cons S6_7191 <|
  AllClassified.cons S6_7192 <|
  AllClassified.cons S6_7193 <|
  AllClassified.cons S6_7194 <|
  AllClassified.cons S6_7195 <|
  AllClassified.cons S6_7196 <|
  AllClassified.cons S6_7197 <|
  AllClassified.cons S6_7198 <|
  AllClassified.cons S6_7199 <|
  AllClassified.cons S6_7200 <|
  AllClassified.nil

end SemiBase.Census
