import SemiBase.Statement
import SemiBase.Catalogue.Order6.Part020
import Order6FinalL5TransferV3.Part055
import Order6FinalL5TransferV3.Part056
import Order6FinalL5TransferV3.Part057
import Order6FinalL5TransferV3.Part058
import Order6FinalL5TransferV3.Part059
import Order6FinalL5TransferV3.Part060
import SemigroupBasis.CoRoots.Order6Day10.S3_6op.Rank071SigmaPlusClassEndpoints
import SemigroupBasis.CoRoots.Order6Day7.S2_2.Rank008CyclicRecordedSplice
import SemigroupBasis.CoRoots.Order6Day7.S2_2.Rank009CyclicRecordedSplice
import SemigroupBasis.CoRoots.Order6GenericCASMonoidPower
import SemigroupBasis.CoRoots.Order6GenericCASSubdirectS6_2862
import SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_1236_Ace8e9bf02c46_Part01
import SemigroupBasis.Generated.Order6DirectPowerAvailableV3Sources.S6_2855
import SemigroupBasis.Generated.Order6DirectPowerUnlockedV3.S6_2980_A6d23d4993dd8_Part01
import SemigroupBasis.Generated.Order6DirectPowerUnlockedV3Sources.S6_2980
import SemigroupBasis.Generated.Order6EmbeddingTransfersPart03
import SemigroupBasis.Generated.Order6FactorIntersection.LongCommutativeCap.S6_2938
import SemigroupBasis.Generated.Order6FactorIntersectionIdentification.Part00
import SemigroupBasis.Generated.Order6FactorIntersectionPeriodTwoFromThreeMultipleBlock.Part00
import SemigroupBasis.Generated.Order6FactorIntersectionPeriodTwoFromThreeMultipleBlock.Part01
import SemigroupBasis.Generated.Order6FactorIntersectionResidual59.Part00
import SemigroupBasis.Generated.Order6FactorPairResidualV3.S6_2885_A47f45831945d_Part01
import SemigroupBasis.Generated.Order6FactorPairS2S5196Targets
import SemigroupBasis.Generated.Order6FactorPairSharedFamilies
import SemigroupBasis.Generated.Order6GenericCASRootWrappers.S6_2851
import SemigroupBasis.Generated.Order6GenericCASRootWrappers.S6_2867
import SemigroupBasis.Generated.Order6GenericCASRootWrappers.S6_2870
import SemigroupBasis.Generated.Order6GenericCASRootWrappers.S6_2879
import SemigroupBasis.Generated.Order6GenericCASRootWrappers.S6_2888
import SemigroupBasis.Generated.Order6GenericCASRootWrappers.S6_2889
import SemigroupBasis.Generated.Order6GenericCASRootWrappers.S6_2898
import SemigroupBasis.Generated.Order6GenericCASRootWrappers.S6_2899
import SemigroupBasis.Generated.Order6GenericCASRootWrappers.S6_2903
import SemigroupBasis.Generated.Order6RouteLocalRootAdapters
import research.formalization.order6.extension.order6_extension_2026_06_12_l5_extension_v11.Order6ExtensionTransfersPart01
import research.formalization.order6.extension.order6_extension_2026_06_12_l5_extension_v14.Order6ExtensionTransfersPart01
import research.formalization.order6.extension.order6_extension_2026_06_12_l5_extension_v2.Order6ExtensionTransfersPart01
import research.formalization.order6.extension.order6_extension_2026_06_12_l5_extension_v6.Order6ExtensionTransfersPart01

/-!
# Census shard 020: classes `[6, 2851]` to `[6, 3000]`

For each class, the claim `Classified` from one endpoint theorem of the
development. The first alternative that checks is used: the endpoint for the
semigroup with the catalogue table, or for its opposite (the transposed table).
Generated by `scripts/generate_census.py`.
-/

set_option maxRecDepth 8192

namespace SemiBase.Census

theorem S6_2851 : Classified Catalogue.Order6.S6_2851 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6GenericCASRootWrappers.S6_2851.opposite_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6GenericCASRootWrappers.S6_2851.opposite_basis)) (by decide +kernel)

theorem S6_2852 : Classified Catalogue.Order6.S6_2852 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day7.S2_2.Rank008.CyclicRecordedSplice.s6_2852_representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day7.S2_2.Rank008.CyclicRecordedSplice.s6_2852_representative_basis)) (by decide +kernel)

theorem S6_2853 : Classified Catalogue.Order6.S6_2853 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2853.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2853.representative_basis)) (by decide +kernel)

theorem S6_2854 : Classified Catalogue.Order6.S6_2854 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day7.S2_2.Rank009.CyclicRecordedSplice.s6_2854_representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day7.S2_2.Rank009.CyclicRecordedSplice.s6_2854_representative_basis)) (by decide +kernel)

theorem S6_2855 : Classified Catalogue.Order6.S6_2855 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3Sources.S6_2855.basis_complete) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3Sources.S6_2855.basis_complete)) (by decide +kernel)

theorem S6_2856 : Classified Catalogue.Order6.S6_2856 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FactorIntersectionPeriodTwoFromThreeMultipleBlock.S6_2856.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FactorIntersectionPeriodTwoFromThreeMultipleBlock.S6_2856.representative_basis)) (by decide +kernel)

theorem S6_2857 : Classified Catalogue.Order6.S6_2857 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2857.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2857.representative_basis)) (by decide +kernel)

theorem S6_2858 : Classified Catalogue.Order6.S6_2858 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FactorIntersectionPeriodTwoFromThreeMultipleBlock.S6_2858.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FactorIntersectionPeriodTwoFromThreeMultipleBlock.S6_2858.representative_basis)) (by decide +kernel)

theorem S6_2859 : Classified Catalogue.Order6.S6_2859 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2859.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2859.representative_basis)) (by decide +kernel)

theorem S6_2860 : Classified Catalogue.Order6.S6_2860 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6RouteLocalRootAdapters.S6_2860.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6RouteLocalRootAdapters.S6_2860.representative_basis)) (by decide +kernel)

theorem S6_2861 : Classified Catalogue.Order6.S6_2861 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2861.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2861.representative_basis)) (by decide +kernel)

theorem S6_2862 : Classified Catalogue.Order6.S6_2862 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6GenericCASSubdirectS6_2862.basisFor) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6GenericCASSubdirectS6_2862.basisFor)) (by decide +kernel)

theorem S6_2863 : Classified Catalogue.Order6.S6_2863 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6GenericCASMonoidPower.S6_2863_oppositeBasisFor) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6GenericCASMonoidPower.S6_2863_oppositeBasisFor)) (by decide +kernel)

theorem S6_2864 : Classified Catalogue.Order6.S6_2864 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2864.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2864.representative_basis)) (by decide +kernel)

theorem S6_2865 : Classified Catalogue.Order6.S6_2865 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FactorIntersectionResidual59.S6_2865.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FactorIntersectionResidual59.S6_2865.representative_basis)) (by decide +kernel)

theorem S6_2866 : Classified Catalogue.Order6.S6_2866 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2866.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2866.representative_basis)) (by decide +kernel)

theorem S6_2867 : Classified Catalogue.Order6.S6_2867 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6GenericCASRootWrappers.S6_2867.opposite_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6GenericCASRootWrappers.S6_2867.opposite_basis)) (by decide +kernel)

theorem S6_2868 : Classified Catalogue.Order6.S6_2868 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2868.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2868.representative_basis)) (by decide +kernel)

theorem S6_2869 : Classified Catalogue.Order6.S6_2869 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FactorPairS2S5196Targets.S6_2869.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FactorPairS2S5196Targets.S6_2869.representative_basis)) (by decide +kernel)

theorem S6_2870 : Classified Catalogue.Order6.S6_2870 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6GenericCASRootWrappers.S6_2870.opposite_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6GenericCASRootWrappers.S6_2870.opposite_basis)) (by decide +kernel)

theorem S6_2871 : Classified Catalogue.Order6.S6_2871 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2871.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2871.representative_basis)) (by decide +kernel)

theorem S6_2872 : Classified Catalogue.Order6.S6_2872 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FactorIntersectionPeriodTwoFromThreeMultipleBlock.S6_2872.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FactorIntersectionPeriodTwoFromThreeMultipleBlock.S6_2872.representative_basis)) (by decide +kernel)

theorem S6_2873 : Classified Catalogue.Order6.S6_2873 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2873.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2873.representative_basis)) (by decide +kernel)

theorem S6_2874 : Classified Catalogue.Order6.S6_2874 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FactorIntersectionPeriodTwoFromThreeMultipleBlock.S6_2874.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FactorIntersectionPeriodTwoFromThreeMultipleBlock.S6_2874.representative_basis)) (by decide +kernel)

theorem S6_2875 : Classified Catalogue.Order6.S6_2875 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2875.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2875.representative_basis)) (by decide +kernel)

theorem S6_2876 : Classified Catalogue.Order6.S6_2876 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2876.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2876.representative_basis)) (by decide +kernel)

theorem S6_2877 : Classified Catalogue.Order6.S6_2877 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2877.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2877.representative_basis)) (by decide +kernel)

theorem S6_2878 : Classified Catalogue.Order6.S6_2878 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FactorPairS2S5196Targets.S6_2878.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FactorPairS2S5196Targets.S6_2878.representative_basis)) (by decide +kernel)

theorem S6_2879 : Classified Catalogue.Order6.S6_2879 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6GenericCASRootWrappers.S6_2879.opposite_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6GenericCASRootWrappers.S6_2879.opposite_basis)) (by decide +kernel)

theorem S6_2880 : Classified Catalogue.Order6.S6_2880 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2880.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2880.representative_basis)) (by decide +kernel)

theorem S6_2881 : Classified Catalogue.Order6.S6_2881 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FactorIntersectionPeriodTwoFromThreeMultipleBlock.S6_2881.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FactorIntersectionPeriodTwoFromThreeMultipleBlock.S6_2881.representative_basis)) (by decide +kernel)

theorem S6_2882 : Classified Catalogue.Order6.S6_2882 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2882.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2882.representative_basis)) (by decide +kernel)

theorem S6_2883 : Classified Catalogue.Order6.S6_2883 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2883.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2883.representative_basis)) (by decide +kernel)

theorem S6_2884 : Classified Catalogue.Order6.S6_2884 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2884.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2884.representative_basis)) (by decide +kernel)

theorem S6_2885 : Classified Catalogue.Order6.S6_2885 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FactorPairS2S5196Targets.S6_2885.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FactorPairS2S5196Targets.S6_2885.representative_basis)) (by decide +kernel)

theorem S6_2886 : Classified Catalogue.Order6.S6_2886 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FactorPairResidualV3.S6_2885_A47f45831945d_Part01.S6_2886.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FactorPairResidualV3.S6_2885_A47f45831945d_Part01.S6_2886.representative_basis)) (by decide +kernel)

theorem S6_2887 : Classified Catalogue.Order6.S6_2887 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FactorIntersectionIdentification.S6_2887.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FactorIntersectionIdentification.S6_2887.representative_basis)) (by decide +kernel)

theorem S6_2888 : Classified Catalogue.Order6.S6_2888 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6GenericCASRootWrappers.S6_2888.opposite_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6GenericCASRootWrappers.S6_2888.opposite_basis)) (by decide +kernel)

theorem S6_2889 : Classified Catalogue.Order6.S6_2889 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6GenericCASRootWrappers.S6_2889.opposite_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6GenericCASRootWrappers.S6_2889.opposite_basis)) (by decide +kernel)

theorem S6_2890 : Classified Catalogue.Order6.S6_2890 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day7.S2_2.Rank008.CyclicRecordedSplice.s6_2890_representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day7.S2_2.Rank008.CyclicRecordedSplice.s6_2890_representative_basis)) (by decide +kernel)

theorem S6_2891 : Classified Catalogue.Order6.S6_2891 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2891.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2891.representative_basis)) (by decide +kernel)

theorem S6_2892 : Classified Catalogue.Order6.S6_2892 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day7.S2_2.Rank009.CyclicRecordedSplice.s6_2892_representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day7.S2_2.Rank009.CyclicRecordedSplice.s6_2892_representative_basis)) (by decide +kernel)

theorem S6_2893 : Classified Catalogue.Order6.S6_2893 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2893.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2893.representative_basis)) (by decide +kernel)

theorem S6_2894 : Classified Catalogue.Order6.S6_2894 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FactorIntersectionPeriodTwoFromThreeMultipleBlock.S6_2894.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FactorIntersectionPeriodTwoFromThreeMultipleBlock.S6_2894.representative_basis)) (by decide +kernel)

theorem S6_2895 : Classified Catalogue.Order6.S6_2895 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2895.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2895.representative_basis)) (by decide +kernel)

theorem S6_2896 : Classified Catalogue.Order6.S6_2896 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6RouteLocalRootAdapters.S6_2896.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6RouteLocalRootAdapters.S6_2896.representative_basis)) (by decide +kernel)

theorem S6_2897 : Classified Catalogue.Order6.S6_2897 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2897.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2897.representative_basis)) (by decide +kernel)

theorem S6_2898 : Classified Catalogue.Order6.S6_2898 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6GenericCASRootWrappers.S6_2898.opposite_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6GenericCASRootWrappers.S6_2898.opposite_basis)) (by decide +kernel)

theorem S6_2899 : Classified Catalogue.Order6.S6_2899 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6GenericCASRootWrappers.S6_2899.opposite_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6GenericCASRootWrappers.S6_2899.opposite_basis)) (by decide +kernel)

theorem S6_2900 : Classified Catalogue.Order6.S6_2900 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2900.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2900.representative_basis)) (by decide +kernel)

theorem S6_2901 : Classified Catalogue.Order6.S6_2901 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FactorIntersectionResidual59.S6_2901.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FactorIntersectionResidual59.S6_2901.representative_basis)) (by decide +kernel)

theorem S6_2902 : Classified Catalogue.Order6.S6_2902 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2902.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2902.representative_basis)) (by decide +kernel)

theorem S6_2903 : Classified Catalogue.Order6.S6_2903 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6GenericCASRootWrappers.S6_2903.opposite_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6GenericCASRootWrappers.S6_2903.opposite_basis)) (by decide +kernel)

theorem S6_2904 : Classified Catalogue.Order6.S6_2904 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_2904.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_2904.representative_basis)) (by decide +kernel)

theorem S6_2905 : Classified Catalogue.Order6.S6_2905 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2905.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2905.representative_basis)) (by decide +kernel)

theorem S6_2906 : Classified Catalogue.Order6.S6_2906 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2906.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2906.representative_basis)) (by decide +kernel)

theorem S6_2907 : Classified Catalogue.Order6.S6_2907 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_2907.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_2907.representative_basis)) (by decide +kernel)

theorem S6_2908 : Classified Catalogue.Order6.S6_2908 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_2908.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_2908.representative_basis)) (by decide +kernel)

theorem S6_2909 : Classified Catalogue.Order6.S6_2909 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FactorIntersectionIdentification.S6_2909.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FactorIntersectionIdentification.S6_2909.representative_basis)) (by decide +kernel)

theorem S6_2910 : Classified Catalogue.Order6.S6_2910 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV11.S6_2910.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV11.S6_2910.representative_basis)) (by decide +kernel)

theorem S6_2911 : Classified Catalogue.Order6.S6_2911 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_2911.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_2911.representative_basis)) (by decide +kernel)

theorem S6_2912 : Classified Catalogue.Order6.S6_2912 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV11.S6_2912.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV11.S6_2912.representative_basis)) (by decide +kernel)

theorem S6_2913 : Classified Catalogue.Order6.S6_2913 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_2913.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_2913.representative_basis)) (by decide +kernel)

theorem S6_2914 : Classified Catalogue.Order6.S6_2914 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV11.S6_2914.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV11.S6_2914.representative_basis)) (by decide +kernel)

theorem S6_2915 : Classified Catalogue.Order6.S6_2915 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV11.S6_2915.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV11.S6_2915.representative_basis)) (by decide +kernel)

theorem S6_2916 : Classified Catalogue.Order6.S6_2916 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_2916.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_2916.representative_basis)) (by decide +kernel)

theorem S6_2917 : Classified Catalogue.Order6.S6_2917 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FactorIntersectionResidual59.S6_2917.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FactorIntersectionResidual59.S6_2917.representative_basis)) (by decide +kernel)

theorem S6_2918 : Classified Catalogue.Order6.S6_2918 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV11.S6_2918.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV11.S6_2918.representative_basis)) (by decide +kernel)

theorem S6_2919 : Classified Catalogue.Order6.S6_2919 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_2919.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_2919.representative_basis)) (by decide +kernel)

theorem S6_2920 : Classified Catalogue.Order6.S6_2920 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV11.S6_2920.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV11.S6_2920.representative_basis)) (by decide +kernel)

theorem S6_2921 : Classified Catalogue.Order6.S6_2921 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV11.S6_2921.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV11.S6_2921.representative_basis)) (by decide +kernel)

theorem S6_2922 : Classified Catalogue.Order6.S6_2922 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_2922.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_2922.representative_basis)) (by decide +kernel)

theorem S6_2923 : Classified Catalogue.Order6.S6_2923 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV11.S6_2923.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV11.S6_2923.representative_basis)) (by decide +kernel)

theorem S6_2924 : Classified Catalogue.Order6.S6_2924 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV11.S6_2924.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV11.S6_2924.representative_basis)) (by decide +kernel)

theorem S6_2925 : Classified Catalogue.Order6.S6_2925 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_2925.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_2925.representative_basis)) (by decide +kernel)

theorem S6_2926 : Classified Catalogue.Order6.S6_2926 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2926.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2926.representative_basis)) (by decide +kernel)

theorem S6_2927 : Classified Catalogue.Order6.S6_2927 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2927.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2927.representative_basis)) (by decide +kernel)

theorem S6_2928 : Classified Catalogue.Order6.S6_2928 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2928.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2928.representative_basis)) (by decide +kernel)

theorem S6_2929 : Classified Catalogue.Order6.S6_2929 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2929.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2929.representative_basis)) (by decide +kernel)

theorem S6_2930 : Classified Catalogue.Order6.S6_2930 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FactorIntersectionIdentification.S6_2930.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FactorIntersectionIdentification.S6_2930.representative_basis)) (by decide +kernel)

theorem S6_2931 : Classified Catalogue.Order6.S6_2931 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FactorIntersectionIdentification.S6_2931.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FactorIntersectionIdentification.S6_2931.representative_basis)) (by decide +kernel)

theorem S6_2932 : Classified Catalogue.Order6.S6_2932 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FactorIntersectionIdentification.S6_2932.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FactorIntersectionIdentification.S6_2932.representative_basis)) (by decide +kernel)

theorem S6_2933 : Classified Catalogue.Order6.S6_2933 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2933.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2933.representative_basis)) (by decide +kernel)

theorem S6_2934 : Classified Catalogue.Order6.S6_2934 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2934.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2934.representative_basis)) (by decide +kernel)

theorem S6_2935 : Classified Catalogue.Order6.S6_2935 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2935.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2935.representative_basis)) (by decide +kernel)

theorem S6_2936 : Classified Catalogue.Order6.S6_2936 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2936.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2936.representative_basis)) (by decide +kernel)

theorem S6_2937 : Classified Catalogue.Order6.S6_2937 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_2937.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_2937.representative_basis)) (by decide +kernel)

theorem S6_2938 : Classified Catalogue.Order6.S6_2938 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FactorIntersection.LongCommutativeCap.S6_2938.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FactorIntersection.LongCommutativeCap.S6_2938.representative_basis)) (by decide +kernel)

theorem S6_2939 : Classified Catalogue.Order6.S6_2939 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2939.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2939.representative_basis)) (by decide +kernel)

theorem S6_2940 : Classified Catalogue.Order6.S6_2940 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV14.S6_2940.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV14.S6_2940.representative_basis)) (by decide +kernel)

theorem S6_2941 : Classified Catalogue.Order6.S6_2941 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2941.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2941.representative_basis)) (by decide +kernel)

theorem S6_2942 : Classified Catalogue.Order6.S6_2942 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV6.S6_2942.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV6.S6_2942.representative_basis)) (by decide +kernel)

theorem S6_2943 : Classified Catalogue.Order6.S6_2943 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2943.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2943.representative_basis)) (by decide +kernel)

theorem S6_2944 : Classified Catalogue.Order6.S6_2944 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV14.S6_2944.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV14.S6_2944.representative_basis)) (by decide +kernel)

theorem S6_2945 : Classified Catalogue.Order6.S6_2945 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2945.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2945.representative_basis)) (by decide +kernel)

theorem S6_2946 : Classified Catalogue.Order6.S6_2946 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV6.S6_2946.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV6.S6_2946.representative_basis)) (by decide +kernel)

theorem S6_2947 : Classified Catalogue.Order6.S6_2947 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2947.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2947.representative_basis)) (by decide +kernel)

theorem S6_2948 : Classified Catalogue.Order6.S6_2948 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV14.S6_2948.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV14.S6_2948.representative_basis)) (by decide +kernel)

theorem S6_2949 : Classified Catalogue.Order6.S6_2949 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2949.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2949.representative_basis)) (by decide +kernel)

theorem S6_2950 : Classified Catalogue.Order6.S6_2950 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2950.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2950.representative_basis)) (by decide +kernel)

theorem S6_2951 : Classified Catalogue.Order6.S6_2951 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV6.S6_2951.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV6.S6_2951.representative_basis)) (by decide +kernel)

theorem S6_2952 : Classified Catalogue.Order6.S6_2952 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2952.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2952.representative_basis)) (by decide +kernel)

theorem S6_2953 : Classified Catalogue.Order6.S6_2953 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2953.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2953.representative_basis)) (by decide +kernel)

theorem S6_2954 : Classified Catalogue.Order6.S6_2954 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2954.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2954.representative_basis)) (by decide +kernel)

theorem S6_2955 : Classified Catalogue.Order6.S6_2955 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2955.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2955.representative_basis)) (by decide +kernel)

theorem S6_2956 : Classified Catalogue.Order6.S6_2956 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2956.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2956.representative_basis)) (by decide +kernel)

theorem S6_2957 : Classified Catalogue.Order6.S6_2957 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2957.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2957.representative_basis)) (by decide +kernel)

theorem S6_2958 : Classified Catalogue.Order6.S6_2958 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_1236_Ace8e9bf02c46_Part01.S6_2958.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_1236_Ace8e9bf02c46_Part01.S6_2958.representative_basis)) (by decide +kernel)

theorem S6_2959 : Classified Catalogue.Order6.S6_2959 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2959.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2959.representative_basis)) (by decide +kernel)

theorem S6_2960 : Classified Catalogue.Order6.S6_2960 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FactorPairSharedFamilies.S6_2960.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FactorPairSharedFamilies.S6_2960.representative_basis)) (by decide +kernel)

theorem S6_2961 : Classified Catalogue.Order6.S6_2961 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2961.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2961.representative_basis)) (by decide +kernel)

theorem S6_2962 : Classified Catalogue.Order6.S6_2962 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FactorPairSharedFamilies.S6_2962.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FactorPairSharedFamilies.S6_2962.representative_basis)) (by decide +kernel)

theorem S6_2963 : Classified Catalogue.Order6.S6_2963 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2963.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2963.representative_basis)) (by decide +kernel)

theorem S6_2964 : Classified Catalogue.Order6.S6_2964 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2964.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2964.representative_basis)) (by decide +kernel)

theorem S6_2965 : Classified Catalogue.Order6.S6_2965 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2965.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2965.representative_basis)) (by decide +kernel)

theorem S6_2966 : Classified Catalogue.Order6.S6_2966 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2966.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2966.representative_basis)) (by decide +kernel)

theorem S6_2967 : Classified Catalogue.Order6.S6_2967 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2967.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2967.representative_basis)) (by decide +kernel)

theorem S6_2968 : Classified Catalogue.Order6.S6_2968 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2968.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2968.representative_basis)) (by decide +kernel)

theorem S6_2969 : Classified Catalogue.Order6.S6_2969 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2969.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2969.representative_basis)) (by decide +kernel)

theorem S6_2970 : Classified Catalogue.Order6.S6_2970 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV14.S6_2970.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV14.S6_2970.representative_basis)) (by decide +kernel)

theorem S6_2971 : Classified Catalogue.Order6.S6_2971 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2971.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2971.representative_basis)) (by decide +kernel)

theorem S6_2972 : Classified Catalogue.Order6.S6_2972 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV6.S6_2972.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV6.S6_2972.representative_basis)) (by decide +kernel)

theorem S6_2973 : Classified Catalogue.Order6.S6_2973 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2973.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2973.representative_basis)) (by decide +kernel)

theorem S6_2974 : Classified Catalogue.Order6.S6_2974 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2974.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2974.representative_basis)) (by decide +kernel)

theorem S6_2975 : Classified Catalogue.Order6.S6_2975 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2975.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2975.representative_basis)) (by decide +kernel)

theorem S6_2976 : Classified Catalogue.Order6.S6_2976 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2976.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2976.representative_basis)) (by decide +kernel)

theorem S6_2977 : Classified Catalogue.Order6.S6_2977 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2977.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2977.representative_basis)) (by decide +kernel)

theorem S6_2978 : Classified Catalogue.Order6.S6_2978 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_2978.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_2978.representative_basis)) (by decide +kernel)

theorem S6_2979 : Classified Catalogue.Order6.S6_2979 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day10.S3_6op.Rank071SigmaPlusClassEndpoints.S6_2979.basisFor) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day10.S3_6op.Rank071SigmaPlusClassEndpoints.S6_2979.basisFor)) (by decide +kernel)

theorem S6_2980 : Classified Catalogue.Order6.S6_2980 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerUnlockedV3Sources.S6_2980.basis_complete) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerUnlockedV3Sources.S6_2980.basis_complete)) (by decide +kernel)

theorem S6_2981 : Classified Catalogue.Order6.S6_2981 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2981.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2981.representative_basis)) (by decide +kernel)

theorem S6_2982 : Classified Catalogue.Order6.S6_2982 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2982.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2982.representative_basis)) (by decide +kernel)

theorem S6_2983 : Classified Catalogue.Order6.S6_2983 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2983.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2983.representative_basis)) (by decide +kernel)

theorem S6_2984 : Classified Catalogue.Order6.S6_2984 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2984.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2984.representative_basis)) (by decide +kernel)

theorem S6_2985 : Classified Catalogue.Order6.S6_2985 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2985.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2985.representative_basis)) (by decide +kernel)

theorem S6_2986 : Classified Catalogue.Order6.S6_2986 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerUnlockedV3.S6_2980_A6d23d4993dd8_Part01.S6_2986.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerUnlockedV3.S6_2980_A6d23d4993dd8_Part01.S6_2986.representative_basis)) (by decide +kernel)

theorem S6_2987 : Classified Catalogue.Order6.S6_2987 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_2987.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_2987.representative_basis)) (by decide +kernel)

theorem S6_2988 : Classified Catalogue.Order6.S6_2988 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2988.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2988.representative_basis)) (by decide +kernel)

theorem S6_2989 : Classified Catalogue.Order6.S6_2989 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2989.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2989.representative_basis)) (by decide +kernel)

theorem S6_2990 : Classified Catalogue.Order6.S6_2990 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2990.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2990.representative_basis)) (by decide +kernel)

theorem S6_2991 : Classified Catalogue.Order6.S6_2991 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV14.S6_2991.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV14.S6_2991.representative_basis)) (by decide +kernel)

theorem S6_2992 : Classified Catalogue.Order6.S6_2992 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2992.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2992.representative_basis)) (by decide +kernel)

theorem S6_2993 : Classified Catalogue.Order6.S6_2993 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV6.S6_2993.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV6.S6_2993.representative_basis)) (by decide +kernel)

theorem S6_2994 : Classified Catalogue.Order6.S6_2994 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2994.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2994.representative_basis)) (by decide +kernel)

theorem S6_2995 : Classified Catalogue.Order6.S6_2995 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV6.S6_2995.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV6.S6_2995.representative_basis)) (by decide +kernel)

theorem S6_2996 : Classified Catalogue.Order6.S6_2996 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2996.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2996.representative_basis)) (by decide +kernel)

theorem S6_2997 : Classified Catalogue.Order6.S6_2997 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_2997.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_2997.representative_basis)) (by decide +kernel)

theorem S6_2998 : Classified Catalogue.Order6.S6_2998 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2998.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2998.representative_basis)) (by decide +kernel)

theorem S6_2999 : Classified Catalogue.Order6.S6_2999 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2999.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_2999.representative_basis)) (by decide +kernel)

theorem S6_3000 : Classified Catalogue.Order6.S6_3000 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_3000.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_3000.representative_basis)) (by decide +kernel)

/-- Every class of part 020 of the catalogue is classified. -/
theorem shard020 : AllClassified Catalogue.Order6.part020 :=
  AllClassified.cons S6_2851 <|
  AllClassified.cons S6_2852 <|
  AllClassified.cons S6_2853 <|
  AllClassified.cons S6_2854 <|
  AllClassified.cons S6_2855 <|
  AllClassified.cons S6_2856 <|
  AllClassified.cons S6_2857 <|
  AllClassified.cons S6_2858 <|
  AllClassified.cons S6_2859 <|
  AllClassified.cons S6_2860 <|
  AllClassified.cons S6_2861 <|
  AllClassified.cons S6_2862 <|
  AllClassified.cons S6_2863 <|
  AllClassified.cons S6_2864 <|
  AllClassified.cons S6_2865 <|
  AllClassified.cons S6_2866 <|
  AllClassified.cons S6_2867 <|
  AllClassified.cons S6_2868 <|
  AllClassified.cons S6_2869 <|
  AllClassified.cons S6_2870 <|
  AllClassified.cons S6_2871 <|
  AllClassified.cons S6_2872 <|
  AllClassified.cons S6_2873 <|
  AllClassified.cons S6_2874 <|
  AllClassified.cons S6_2875 <|
  AllClassified.cons S6_2876 <|
  AllClassified.cons S6_2877 <|
  AllClassified.cons S6_2878 <|
  AllClassified.cons S6_2879 <|
  AllClassified.cons S6_2880 <|
  AllClassified.cons S6_2881 <|
  AllClassified.cons S6_2882 <|
  AllClassified.cons S6_2883 <|
  AllClassified.cons S6_2884 <|
  AllClassified.cons S6_2885 <|
  AllClassified.cons S6_2886 <|
  AllClassified.cons S6_2887 <|
  AllClassified.cons S6_2888 <|
  AllClassified.cons S6_2889 <|
  AllClassified.cons S6_2890 <|
  AllClassified.cons S6_2891 <|
  AllClassified.cons S6_2892 <|
  AllClassified.cons S6_2893 <|
  AllClassified.cons S6_2894 <|
  AllClassified.cons S6_2895 <|
  AllClassified.cons S6_2896 <|
  AllClassified.cons S6_2897 <|
  AllClassified.cons S6_2898 <|
  AllClassified.cons S6_2899 <|
  AllClassified.cons S6_2900 <|
  AllClassified.cons S6_2901 <|
  AllClassified.cons S6_2902 <|
  AllClassified.cons S6_2903 <|
  AllClassified.cons S6_2904 <|
  AllClassified.cons S6_2905 <|
  AllClassified.cons S6_2906 <|
  AllClassified.cons S6_2907 <|
  AllClassified.cons S6_2908 <|
  AllClassified.cons S6_2909 <|
  AllClassified.cons S6_2910 <|
  AllClassified.cons S6_2911 <|
  AllClassified.cons S6_2912 <|
  AllClassified.cons S6_2913 <|
  AllClassified.cons S6_2914 <|
  AllClassified.cons S6_2915 <|
  AllClassified.cons S6_2916 <|
  AllClassified.cons S6_2917 <|
  AllClassified.cons S6_2918 <|
  AllClassified.cons S6_2919 <|
  AllClassified.cons S6_2920 <|
  AllClassified.cons S6_2921 <|
  AllClassified.cons S6_2922 <|
  AllClassified.cons S6_2923 <|
  AllClassified.cons S6_2924 <|
  AllClassified.cons S6_2925 <|
  AllClassified.cons S6_2926 <|
  AllClassified.cons S6_2927 <|
  AllClassified.cons S6_2928 <|
  AllClassified.cons S6_2929 <|
  AllClassified.cons S6_2930 <|
  AllClassified.cons S6_2931 <|
  AllClassified.cons S6_2932 <|
  AllClassified.cons S6_2933 <|
  AllClassified.cons S6_2934 <|
  AllClassified.cons S6_2935 <|
  AllClassified.cons S6_2936 <|
  AllClassified.cons S6_2937 <|
  AllClassified.cons S6_2938 <|
  AllClassified.cons S6_2939 <|
  AllClassified.cons S6_2940 <|
  AllClassified.cons S6_2941 <|
  AllClassified.cons S6_2942 <|
  AllClassified.cons S6_2943 <|
  AllClassified.cons S6_2944 <|
  AllClassified.cons S6_2945 <|
  AllClassified.cons S6_2946 <|
  AllClassified.cons S6_2947 <|
  AllClassified.cons S6_2948 <|
  AllClassified.cons S6_2949 <|
  AllClassified.cons S6_2950 <|
  AllClassified.cons S6_2951 <|
  AllClassified.cons S6_2952 <|
  AllClassified.cons S6_2953 <|
  AllClassified.cons S6_2954 <|
  AllClassified.cons S6_2955 <|
  AllClassified.cons S6_2956 <|
  AllClassified.cons S6_2957 <|
  AllClassified.cons S6_2958 <|
  AllClassified.cons S6_2959 <|
  AllClassified.cons S6_2960 <|
  AllClassified.cons S6_2961 <|
  AllClassified.cons S6_2962 <|
  AllClassified.cons S6_2963 <|
  AllClassified.cons S6_2964 <|
  AllClassified.cons S6_2965 <|
  AllClassified.cons S6_2966 <|
  AllClassified.cons S6_2967 <|
  AllClassified.cons S6_2968 <|
  AllClassified.cons S6_2969 <|
  AllClassified.cons S6_2970 <|
  AllClassified.cons S6_2971 <|
  AllClassified.cons S6_2972 <|
  AllClassified.cons S6_2973 <|
  AllClassified.cons S6_2974 <|
  AllClassified.cons S6_2975 <|
  AllClassified.cons S6_2976 <|
  AllClassified.cons S6_2977 <|
  AllClassified.cons S6_2978 <|
  AllClassified.cons S6_2979 <|
  AllClassified.cons S6_2980 <|
  AllClassified.cons S6_2981 <|
  AllClassified.cons S6_2982 <|
  AllClassified.cons S6_2983 <|
  AllClassified.cons S6_2984 <|
  AllClassified.cons S6_2985 <|
  AllClassified.cons S6_2986 <|
  AllClassified.cons S6_2987 <|
  AllClassified.cons S6_2988 <|
  AllClassified.cons S6_2989 <|
  AllClassified.cons S6_2990 <|
  AllClassified.cons S6_2991 <|
  AllClassified.cons S6_2992 <|
  AllClassified.cons S6_2993 <|
  AllClassified.cons S6_2994 <|
  AllClassified.cons S6_2995 <|
  AllClassified.cons S6_2996 <|
  AllClassified.cons S6_2997 <|
  AllClassified.cons S6_2998 <|
  AllClassified.cons S6_2999 <|
  AllClassified.cons S6_3000 <|
  AllClassified.nil

end SemiBase.Census
