import SemiBase.Statement
import SemiBase.Catalogue.Order6.Part044
import Order6FinalL5TransferV3.Part150
import Order6FinalL5TransferV3.Part151
import Order6FinalL5TransferV3.Part152
import Order6FinalL5TransferV3.Part153
import Order6FinalL5TransferV3.Part154
import Order6FinalL5TransferV3.Part155
import SemigroupBasis.CoRoots.Order6Day7.LeeZhang.Msg0456FordNilCompleteness
import SemigroupBasis.CoRoots.Order6Day7.S2_4.SeedS5_240Opposite
import SemigroupBasis.CoRoots.Order6Day7.S3_16.SeedS5_240Opposite
import SemigroupBasis.CoRoots.Order6Day9.S3_6.Rank014ClassEndpoints
import SemigroupBasis.CoRoots.Order6Sunday.Msg0456S6598Completeness
import SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_1088_Ad4b303415746_Part01
import SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_1242_Ad4b303415746_Part01
import SemigroupBasis.Generated.Order6DivisorTransfersPart32
import SemigroupBasis.Generated.Order6EmbeddingTransfersPart06
import SemigroupBasis.Generated.Order6FactorPairS3_11Targets
import SemigroupBasis.Generated.Order6FinalL5SourceInterfacesV3
import SemigroupBasis.Generated.Order6L3RootS4_23S4_90Targets
import SemigroupBasis.Generated.Order6OneLocalExisting15
import SemigroupBasis.Generated.Order6RouteLocalRootAdapters
import SemigroupBasis.Generated.Order6S6_6524FromS6_6385
import research.formalization.order6.extension.order6_extension_2026_06_12_l5_extension_v1.Order6ExtensionTransfersPart06
import research.formalization.order6.extension.order6_extension_2026_06_12_l5_extension_v2.Order6ExtensionTransfersPart03
import research.formalization.order6.extension.order6_extension_2026_06_12_l5_extension_v3.Order6ExtensionTransfersPart02
import research.formalization.order6.extension.order6_extension_2026_06_12_l5_extension_v4.Order6ExtensionTransfersPart02
import research.formalization.order6.extension.order6_extension_2026_06_12_l5_extension_v5.Order6ExtensionTransfersPart02
import research.formalization.order6.extension.order6_extension_2026_06_12_l5_extension_v5.Order6ExtensionTransfersPart03
import research.formalization.order6.extension.order6_extension_2026_06_12_l5_extension_v6.Order6ExtensionTransfersPart03
import research.formalization.order6.extension.order6_extension_2026_06_12_l5_extension_v7.Order6ExtensionTransfersPart02

/-!
# Census shard 044: classes `[6, 6451]` to `[6, 6600]`

For each class, the claim `Classified` from one endpoint theorem of the
development. The first alternative that checks is used: the endpoint for the
semigroup with the catalogue table, or for its opposite (the transposed table).
Generated by `scripts/generate_census.py`.
-/

set_option maxRecDepth 8192

namespace SemiBase.Census

theorem S6_6451 : Classified Catalogue.Order6.S6_6451 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_6451.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_6451.representative_basis)) (by decide +kernel)

theorem S6_6452 : Classified Catalogue.Order6.S6_6452 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_6452.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_6452.representative_basis)) (by decide +kernel)

theorem S6_6453 : Classified Catalogue.Order6.S6_6453 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV4.S6_6453.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV4.S6_6453.representative_basis)) (by decide +kernel)

theorem S6_6454 : Classified Catalogue.Order6.S6_6454 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6454.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6454.representative_basis)) (by decide +kernel)

theorem S6_6455 : Classified Catalogue.Order6.S6_6455 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6455.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6455.representative_basis)) (by decide +kernel)

theorem S6_6456 : Classified Catalogue.Order6.S6_6456 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6456.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6456.representative_basis)) (by decide +kernel)

theorem S6_6457 : Classified Catalogue.Order6.S6_6457 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6457.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6457.representative_basis)) (by decide +kernel)

theorem S6_6458 : Classified Catalogue.Order6.S6_6458 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6458.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6458.representative_basis)) (by decide +kernel)

theorem S6_6459 : Classified Catalogue.Order6.S6_6459 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6459.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6459.representative_basis)) (by decide +kernel)

theorem S6_6460 : Classified Catalogue.Order6.S6_6460 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6460.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6460.representative_basis)) (by decide +kernel)

theorem S6_6461 : Classified Catalogue.Order6.S6_6461 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6461.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6461.representative_basis)) (by decide +kernel)

theorem S6_6462 : Classified Catalogue.Order6.S6_6462 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6OneLocalExisting15.S6_6462.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6OneLocalExisting15.S6_6462.representative_basis)) (by decide +kernel)

theorem S6_6463 : Classified Catalogue.Order6.S6_6463 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6RouteLocalRootAdapters.S6_6463.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6RouteLocalRootAdapters.S6_6463.representative_basis)) (by decide +kernel)

theorem S6_6464 : Classified Catalogue.Order6.S6_6464 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_6464.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_6464.representative_basis)) (by decide +kernel)

theorem S6_6465 : Classified Catalogue.Order6.S6_6465 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV6.S6_6465.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV6.S6_6465.representative_basis)) (by decide +kernel)

theorem S6_6466 : Classified Catalogue.Order6.S6_6466 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_6466.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_6466.representative_basis)) (by decide +kernel)

theorem S6_6467 : Classified Catalogue.Order6.S6_6467 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV4.S6_6467.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV4.S6_6467.representative_basis)) (by decide +kernel)

theorem S6_6468 : Classified Catalogue.Order6.S6_6468 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6468.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6468.representative_basis)) (by decide +kernel)

theorem S6_6469 : Classified Catalogue.Order6.S6_6469 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6469.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6469.representative_basis)) (by decide +kernel)

theorem S6_6470 : Classified Catalogue.Order6.S6_6470 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6470.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6470.representative_basis)) (by decide +kernel)

theorem S6_6471 : Classified Catalogue.Order6.S6_6471 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FactorPairS3_11Targets.S6_6471.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FactorPairS3_11Targets.S6_6471.representative_basis)) (by decide +kernel)

theorem S6_6472 : Classified Catalogue.Order6.S6_6472 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV5.S6_6472.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV5.S6_6472.representative_basis)) (by decide +kernel)

theorem S6_6473 : Classified Catalogue.Order6.S6_6473 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV5.S6_6473.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV5.S6_6473.representative_basis)) (by decide +kernel)

theorem S6_6474 : Classified Catalogue.Order6.S6_6474 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6474.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6474.representative_basis)) (by decide +kernel)

theorem S6_6475 : Classified Catalogue.Order6.S6_6475 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV5.S6_6475.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV5.S6_6475.representative_basis)) (by decide +kernel)

theorem S6_6476 : Classified Catalogue.Order6.S6_6476 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6476.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6476.representative_basis)) (by decide +kernel)

theorem S6_6477 : Classified Catalogue.Order6.S6_6477 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6477.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6477.representative_basis)) (by decide +kernel)

theorem S6_6478 : Classified Catalogue.Order6.S6_6478 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6478.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6478.representative_basis)) (by decide +kernel)

theorem S6_6479 : Classified Catalogue.Order6.S6_6479 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6479.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6479.representative_basis)) (by decide +kernel)

theorem S6_6480 : Classified Catalogue.Order6.S6_6480 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_6480.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_6480.representative_basis)) (by decide +kernel)

theorem S6_6481 : Classified Catalogue.Order6.S6_6481 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_6481.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_6481.representative_basis)) (by decide +kernel)

theorem S6_6482 : Classified Catalogue.Order6.S6_6482 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6482.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6482.representative_basis)) (by decide +kernel)

theorem S6_6483 : Classified Catalogue.Order6.S6_6483 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Order6SourceRelease.FinalL5.S6_6483.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Order6SourceRelease.FinalL5.S6_6483.representative_basis)) (by decide +kernel)

theorem S6_6484 : Classified Catalogue.Order6.S6_6484 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6484.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6484.representative_basis)) (by decide +kernel)

theorem S6_6485 : Classified Catalogue.Order6.S6_6485 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_6485.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_6485.representative_basis)) (by decide +kernel)

theorem S6_6486 : Classified Catalogue.Order6.S6_6486 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_6486.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_6486.representative_basis)) (by decide +kernel)

theorem S6_6487 : Classified Catalogue.Order6.S6_6487 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_6487.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_6487.representative_basis)) (by decide +kernel)

theorem S6_6488 : Classified Catalogue.Order6.S6_6488 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV5.S6_6488.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV5.S6_6488.representative_basis)) (by decide +kernel)

theorem S6_6489 : Classified Catalogue.Order6.S6_6489 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_6489.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_6489.representative_basis)) (by decide +kernel)

theorem S6_6490 : Classified Catalogue.Order6.S6_6490 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6490.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6490.representative_basis)) (by decide +kernel)

theorem S6_6491 : Classified Catalogue.Order6.S6_6491 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6491.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6491.representative_basis)) (by decide +kernel)

theorem S6_6492 : Classified Catalogue.Order6.S6_6492 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6492.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6492.representative_basis)) (by decide +kernel)

theorem S6_6493 : Classified Catalogue.Order6.S6_6493 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6493.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6493.representative_basis)) (by decide +kernel)

theorem S6_6494 : Classified Catalogue.Order6.S6_6494 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Order6SourceRelease.FinalL5.S6_6494.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Order6SourceRelease.FinalL5.S6_6494.representative_basis)) (by decide +kernel)

theorem S6_6495 : Classified Catalogue.Order6.S6_6495 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6495.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6495.representative_basis)) (by decide +kernel)

theorem S6_6496 : Classified Catalogue.Order6.S6_6496 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6496.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6496.representative_basis)) (by decide +kernel)

theorem S6_6497 : Classified Catalogue.Order6.S6_6497 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6497.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6497.representative_basis)) (by decide +kernel)

theorem S6_6498 : Classified Catalogue.Order6.S6_6498 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV5.S6_6498.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV5.S6_6498.representative_basis)) (by decide +kernel)

theorem S6_6499 : Classified Catalogue.Order6.S6_6499 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV5.S6_6499.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV5.S6_6499.representative_basis)) (by decide +kernel)

theorem S6_6500 : Classified Catalogue.Order6.S6_6500 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6500.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6500.representative_basis)) (by decide +kernel)

theorem S6_6501 : Classified Catalogue.Order6.S6_6501 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6501.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6501.representative_basis)) (by decide +kernel)

theorem S6_6502 : Classified Catalogue.Order6.S6_6502 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6L3RootS4_23S4_90Targets.S6_6502.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6L3RootS4_23S4_90Targets.S6_6502.representative_basis)) (by decide +kernel)

theorem S6_6503 : Classified Catalogue.Order6.S6_6503 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6503.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6503.representative_basis)) (by decide +kernel)

theorem S6_6504 : Classified Catalogue.Order6.S6_6504 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6504.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6504.representative_basis)) (by decide +kernel)

theorem S6_6505 : Classified Catalogue.Order6.S6_6505 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6505.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6505.representative_basis)) (by decide +kernel)

theorem S6_6506 : Classified Catalogue.Order6.S6_6506 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day9.S3_6.Rank014ClassEndpoints.S6_6506.basisFor) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day9.S3_6.Rank014ClassEndpoints.S6_6506.basisFor)) (by decide +kernel)

theorem S6_6507 : Classified Catalogue.Order6.S6_6507 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV3.S6_6507.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV3.S6_6507.representative_basis)) (by decide +kernel)

theorem S6_6508 : Classified Catalogue.Order6.S6_6508 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6508.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6508.representative_basis)) (by decide +kernel)

theorem S6_6509 : Classified Catalogue.Order6.S6_6509 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_6509.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_6509.representative_basis)) (by decide +kernel)

theorem S6_6510 : Classified Catalogue.Order6.S6_6510 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day7.S2_4.Rank051.Seed.s6_6510_representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day7.S2_4.Rank051.Seed.s6_6510_representative_basis)) (by decide +kernel)

theorem S6_6511 : Classified Catalogue.Order6.S6_6511 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_6511.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_6511.representative_basis)) (by decide +kernel)

theorem S6_6512 : Classified Catalogue.Order6.S6_6512 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day7.S3_16.Rank088.Seed.s6_6512_representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day7.S3_16.Rank088.Seed.s6_6512_representative_basis)) (by decide +kernel)

theorem S6_6513 : Classified Catalogue.Order6.S6_6513 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6513.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6513.representative_basis)) (by decide +kernel)

theorem S6_6514 : Classified Catalogue.Order6.S6_6514 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6514.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6514.representative_basis)) (by decide +kernel)

theorem S6_6515 : Classified Catalogue.Order6.S6_6515 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6515.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6515.representative_basis)) (by decide +kernel)

theorem S6_6516 : Classified Catalogue.Order6.S6_6516 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_6516.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_6516.representative_basis)) (by decide +kernel)

theorem S6_6517 : Classified Catalogue.Order6.S6_6517 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_6517.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_6517.representative_basis)) (by decide +kernel)

theorem S6_6518 : Classified Catalogue.Order6.S6_6518 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6518.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6518.representative_basis)) (by decide +kernel)

theorem S6_6519 : Classified Catalogue.Order6.S6_6519 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6519.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6519.representative_basis)) (by decide +kernel)

theorem S6_6520 : Classified Catalogue.Order6.S6_6520 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_6520.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_6520.representative_basis)) (by decide +kernel)

theorem S6_6521 : Classified Catalogue.Order6.S6_6521 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6521.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6521.representative_basis)) (by decide +kernel)

theorem S6_6522 : Classified Catalogue.Order6.S6_6522 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_6522.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_6522.representative_basis)) (by decide +kernel)

theorem S6_6523 : Classified Catalogue.Order6.S6_6523 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6523.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6523.representative_basis)) (by decide +kernel)

theorem S6_6524 : Classified Catalogue.Order6.S6_6524 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6S6_6524FromS6_6385.S6_6524.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6S6_6524FromS6_6385.S6_6524.representative_basis)) (by decide +kernel)

theorem S6_6525 : Classified Catalogue.Order6.S6_6525 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6525.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6525.representative_basis)) (by decide +kernel)

theorem S6_6526 : Classified Catalogue.Order6.S6_6526 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_6526.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_6526.representative_basis)) (by decide +kernel)

theorem S6_6527 : Classified Catalogue.Order6.S6_6527 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_6527.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_6527.representative_basis)) (by decide +kernel)

theorem S6_6528 : Classified Catalogue.Order6.S6_6528 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_6528.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_6528.representative_basis)) (by decide +kernel)

theorem S6_6529 : Classified Catalogue.Order6.S6_6529 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV5.S6_6529.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV5.S6_6529.representative_basis)) (by decide +kernel)

theorem S6_6530 : Classified Catalogue.Order6.S6_6530 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV5.S6_6530.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV5.S6_6530.representative_basis)) (by decide +kernel)

theorem S6_6531 : Classified Catalogue.Order6.S6_6531 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV5.S6_6531.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV5.S6_6531.representative_basis)) (by decide +kernel)

theorem S6_6532 : Classified Catalogue.Order6.S6_6532 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_6532.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_6532.representative_basis)) (by decide +kernel)

theorem S6_6533 : Classified Catalogue.Order6.S6_6533 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6533.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6533.representative_basis)) (by decide +kernel)

theorem S6_6534 : Classified Catalogue.Order6.S6_6534 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6534.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6534.representative_basis)) (by decide +kernel)

theorem S6_6535 : Classified Catalogue.Order6.S6_6535 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6535.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6535.representative_basis)) (by decide +kernel)

theorem S6_6536 : Classified Catalogue.Order6.S6_6536 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6RouteLocalRootAdapters.S6_6536.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6RouteLocalRootAdapters.S6_6536.representative_basis)) (by decide +kernel)

theorem S6_6537 : Classified Catalogue.Order6.S6_6537 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6537.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6537.representative_basis)) (by decide +kernel)

theorem S6_6538 : Classified Catalogue.Order6.S6_6538 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6538.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6538.representative_basis)) (by decide +kernel)

theorem S6_6539 : Classified Catalogue.Order6.S6_6539 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6539.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6539.representative_basis)) (by decide +kernel)

theorem S6_6540 : Classified Catalogue.Order6.S6_6540 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6540.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6540.representative_basis)) (by decide +kernel)

theorem S6_6541 : Classified Catalogue.Order6.S6_6541 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6541.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6541.representative_basis)) (by decide +kernel)

theorem S6_6542 : Classified Catalogue.Order6.S6_6542 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6542.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6542.representative_basis)) (by decide +kernel)

theorem S6_6543 : Classified Catalogue.Order6.S6_6543 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day7.LeeZhang.FordNil.representative_basis6543) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day7.LeeZhang.FordNil.representative_basis6543)) (by decide +kernel)

theorem S6_6544 : Classified Catalogue.Order6.S6_6544 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV3.S6_6544.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV3.S6_6544.representative_basis)) (by decide +kernel)

theorem S6_6545 : Classified Catalogue.Order6.S6_6545 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6545.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6545.representative_basis)) (by decide +kernel)

theorem S6_6546 : Classified Catalogue.Order6.S6_6546 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_6546.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_6546.representative_basis)) (by decide +kernel)

theorem S6_6547 : Classified Catalogue.Order6.S6_6547 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6547.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6547.representative_basis)) (by decide +kernel)

theorem S6_6548 : Classified Catalogue.Order6.S6_6548 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV5.S6_6548.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV5.S6_6548.representative_basis)) (by decide +kernel)

theorem S6_6549 : Classified Catalogue.Order6.S6_6549 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6549.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6549.representative_basis)) (by decide +kernel)

theorem S6_6550 : Classified Catalogue.Order6.S6_6550 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6OneLocalExisting15.S6_6550.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6OneLocalExisting15.S6_6550.representative_basis)) (by decide +kernel)

theorem S6_6551 : Classified Catalogue.Order6.S6_6551 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6551.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6551.representative_basis)) (by decide +kernel)

theorem S6_6552 : Classified Catalogue.Order6.S6_6552 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6552.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6552.representative_basis)) (by decide +kernel)

theorem S6_6553 : Classified Catalogue.Order6.S6_6553 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_6553.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_6553.representative_basis)) (by decide +kernel)

theorem S6_6554 : Classified Catalogue.Order6.S6_6554 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV7.S6_6554.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV7.S6_6554.representative_basis)) (by decide +kernel)

theorem S6_6555 : Classified Catalogue.Order6.S6_6555 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_6555.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_6555.representative_basis)) (by decide +kernel)

theorem S6_6556 : Classified Catalogue.Order6.S6_6556 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6556.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6556.representative_basis)) (by decide +kernel)

theorem S6_6557 : Classified Catalogue.Order6.S6_6557 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV7.S6_6557.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV7.S6_6557.representative_basis)) (by decide +kernel)

theorem S6_6558 : Classified Catalogue.Order6.S6_6558 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_6558.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_6558.representative_basis)) (by decide +kernel)

theorem S6_6559 : Classified Catalogue.Order6.S6_6559 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_1088_Ad4b303415746_Part01.S6_6559.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_1088_Ad4b303415746_Part01.S6_6559.representative_basis)) (by decide +kernel)

theorem S6_6560 : Classified Catalogue.Order6.S6_6560 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV6.S6_6560.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV6.S6_6560.representative_basis)) (by decide +kernel)

theorem S6_6561 : Classified Catalogue.Order6.S6_6561 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_6561.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_6561.representative_basis)) (by decide +kernel)

theorem S6_6562 : Classified Catalogue.Order6.S6_6562 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6562.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6562.representative_basis)) (by decide +kernel)

theorem S6_6563 : Classified Catalogue.Order6.S6_6563 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_1242_Ad4b303415746_Part01.S6_6563.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_1242_Ad4b303415746_Part01.S6_6563.representative_basis)) (by decide +kernel)

theorem S6_6564 : Classified Catalogue.Order6.S6_6564 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6564.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6564.representative_basis)) (by decide +kernel)

theorem S6_6565 : Classified Catalogue.Order6.S6_6565 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6565.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6565.representative_basis)) (by decide +kernel)

theorem S6_6566 : Classified Catalogue.Order6.S6_6566 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV7.S6_6566.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV7.S6_6566.representative_basis)) (by decide +kernel)

theorem S6_6567 : Classified Catalogue.Order6.S6_6567 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6567.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6567.representative_basis)) (by decide +kernel)

theorem S6_6568 : Classified Catalogue.Order6.S6_6568 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_1088_Ad4b303415746_Part01.S6_6568.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_1088_Ad4b303415746_Part01.S6_6568.representative_basis)) (by decide +kernel)

theorem S6_6569 : Classified Catalogue.Order6.S6_6569 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV7.S6_6569.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV7.S6_6569.representative_basis)) (by decide +kernel)

theorem S6_6570 : Classified Catalogue.Order6.S6_6570 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6570.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6570.representative_basis)) (by decide +kernel)

theorem S6_6571 : Classified Catalogue.Order6.S6_6571 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_6571.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_6571.representative_basis)) (by decide +kernel)

theorem S6_6572 : Classified Catalogue.Order6.S6_6572 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6572.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6572.representative_basis)) (by decide +kernel)

theorem S6_6573 : Classified Catalogue.Order6.S6_6573 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6573.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6573.representative_basis)) (by decide +kernel)

theorem S6_6574 : Classified Catalogue.Order6.S6_6574 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6574.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6574.representative_basis)) (by decide +kernel)

theorem S6_6575 : Classified Catalogue.Order6.S6_6575 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6575.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6575.representative_basis)) (by decide +kernel)

theorem S6_6576 : Classified Catalogue.Order6.S6_6576 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_6576.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_6576.representative_basis)) (by decide +kernel)

theorem S6_6577 : Classified Catalogue.Order6.S6_6577 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV6.S6_6577.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV6.S6_6577.representative_basis)) (by decide +kernel)

theorem S6_6578 : Classified Catalogue.Order6.S6_6578 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_6578.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_6578.representative_basis)) (by decide +kernel)

theorem S6_6579 : Classified Catalogue.Order6.S6_6579 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV4.S6_6579.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV4.S6_6579.representative_basis)) (by decide +kernel)

theorem S6_6580 : Classified Catalogue.Order6.S6_6580 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV5.S6_6580.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV5.S6_6580.representative_basis)) (by decide +kernel)

theorem S6_6581 : Classified Catalogue.Order6.S6_6581 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV5.S6_6581.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV5.S6_6581.representative_basis)) (by decide +kernel)

theorem S6_6582 : Classified Catalogue.Order6.S6_6582 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6582.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6582.representative_basis)) (by decide +kernel)

theorem S6_6583 : Classified Catalogue.Order6.S6_6583 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV5.S6_6583.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV5.S6_6583.representative_basis)) (by decide +kernel)

theorem S6_6584 : Classified Catalogue.Order6.S6_6584 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6584.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6584.representative_basis)) (by decide +kernel)

theorem S6_6585 : Classified Catalogue.Order6.S6_6585 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_6585.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_6585.representative_basis)) (by decide +kernel)

theorem S6_6586 : Classified Catalogue.Order6.S6_6586 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV5.S6_6586.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV5.S6_6586.representative_basis)) (by decide +kernel)

theorem S6_6587 : Classified Catalogue.Order6.S6_6587 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6587.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6587.representative_basis)) (by decide +kernel)

theorem S6_6588 : Classified Catalogue.Order6.S6_6588 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6588.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6588.representative_basis)) (by decide +kernel)

theorem S6_6589 : Classified Catalogue.Order6.S6_6589 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_6589.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_6589.representative_basis)) (by decide +kernel)

theorem S6_6590 : Classified Catalogue.Order6.S6_6590 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_6590.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_6590.representative_basis)) (by decide +kernel)

theorem S6_6591 : Classified Catalogue.Order6.S6_6591 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV7.S6_6591.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV7.S6_6591.representative_basis)) (by decide +kernel)

theorem S6_6592 : Classified Catalogue.Order6.S6_6592 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_6592.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_6592.representative_basis)) (by decide +kernel)

theorem S6_6593 : Classified Catalogue.Order6.S6_6593 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_6593.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_6593.representative_basis)) (by decide +kernel)

theorem S6_6594 : Classified Catalogue.Order6.S6_6594 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_6594.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_6594.representative_basis)) (by decide +kernel)

theorem S6_6595 : Classified Catalogue.Order6.S6_6595 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6595.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6595.representative_basis)) (by decide +kernel)

theorem S6_6596 : Classified Catalogue.Order6.S6_6596 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6596.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6596.representative_basis)) (by decide +kernel)

theorem S6_6597 : Classified Catalogue.Order6.S6_6597 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6597.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6597.representative_basis)) (by decide +kernel)

theorem S6_6598 : Classified Catalogue.Order6.S6_6598 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Sunday.Msg0456S6598Completeness.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Sunday.Msg0456S6598Completeness.representative_basis)) (by decide +kernel)

theorem S6_6599 : Classified Catalogue.Order6.S6_6599 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6599.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6599.representative_basis)) (by decide +kernel)

theorem S6_6600 : Classified Catalogue.Order6.S6_6600 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6600.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_6600.representative_basis)) (by decide +kernel)

/-- Every class of part 044 of the catalogue is classified. -/
theorem shard044 : AllClassified Catalogue.Order6.part044 :=
  AllClassified.cons S6_6451 <|
  AllClassified.cons S6_6452 <|
  AllClassified.cons S6_6453 <|
  AllClassified.cons S6_6454 <|
  AllClassified.cons S6_6455 <|
  AllClassified.cons S6_6456 <|
  AllClassified.cons S6_6457 <|
  AllClassified.cons S6_6458 <|
  AllClassified.cons S6_6459 <|
  AllClassified.cons S6_6460 <|
  AllClassified.cons S6_6461 <|
  AllClassified.cons S6_6462 <|
  AllClassified.cons S6_6463 <|
  AllClassified.cons S6_6464 <|
  AllClassified.cons S6_6465 <|
  AllClassified.cons S6_6466 <|
  AllClassified.cons S6_6467 <|
  AllClassified.cons S6_6468 <|
  AllClassified.cons S6_6469 <|
  AllClassified.cons S6_6470 <|
  AllClassified.cons S6_6471 <|
  AllClassified.cons S6_6472 <|
  AllClassified.cons S6_6473 <|
  AllClassified.cons S6_6474 <|
  AllClassified.cons S6_6475 <|
  AllClassified.cons S6_6476 <|
  AllClassified.cons S6_6477 <|
  AllClassified.cons S6_6478 <|
  AllClassified.cons S6_6479 <|
  AllClassified.cons S6_6480 <|
  AllClassified.cons S6_6481 <|
  AllClassified.cons S6_6482 <|
  AllClassified.cons S6_6483 <|
  AllClassified.cons S6_6484 <|
  AllClassified.cons S6_6485 <|
  AllClassified.cons S6_6486 <|
  AllClassified.cons S6_6487 <|
  AllClassified.cons S6_6488 <|
  AllClassified.cons S6_6489 <|
  AllClassified.cons S6_6490 <|
  AllClassified.cons S6_6491 <|
  AllClassified.cons S6_6492 <|
  AllClassified.cons S6_6493 <|
  AllClassified.cons S6_6494 <|
  AllClassified.cons S6_6495 <|
  AllClassified.cons S6_6496 <|
  AllClassified.cons S6_6497 <|
  AllClassified.cons S6_6498 <|
  AllClassified.cons S6_6499 <|
  AllClassified.cons S6_6500 <|
  AllClassified.cons S6_6501 <|
  AllClassified.cons S6_6502 <|
  AllClassified.cons S6_6503 <|
  AllClassified.cons S6_6504 <|
  AllClassified.cons S6_6505 <|
  AllClassified.cons S6_6506 <|
  AllClassified.cons S6_6507 <|
  AllClassified.cons S6_6508 <|
  AllClassified.cons S6_6509 <|
  AllClassified.cons S6_6510 <|
  AllClassified.cons S6_6511 <|
  AllClassified.cons S6_6512 <|
  AllClassified.cons S6_6513 <|
  AllClassified.cons S6_6514 <|
  AllClassified.cons S6_6515 <|
  AllClassified.cons S6_6516 <|
  AllClassified.cons S6_6517 <|
  AllClassified.cons S6_6518 <|
  AllClassified.cons S6_6519 <|
  AllClassified.cons S6_6520 <|
  AllClassified.cons S6_6521 <|
  AllClassified.cons S6_6522 <|
  AllClassified.cons S6_6523 <|
  AllClassified.cons S6_6524 <|
  AllClassified.cons S6_6525 <|
  AllClassified.cons S6_6526 <|
  AllClassified.cons S6_6527 <|
  AllClassified.cons S6_6528 <|
  AllClassified.cons S6_6529 <|
  AllClassified.cons S6_6530 <|
  AllClassified.cons S6_6531 <|
  AllClassified.cons S6_6532 <|
  AllClassified.cons S6_6533 <|
  AllClassified.cons S6_6534 <|
  AllClassified.cons S6_6535 <|
  AllClassified.cons S6_6536 <|
  AllClassified.cons S6_6537 <|
  AllClassified.cons S6_6538 <|
  AllClassified.cons S6_6539 <|
  AllClassified.cons S6_6540 <|
  AllClassified.cons S6_6541 <|
  AllClassified.cons S6_6542 <|
  AllClassified.cons S6_6543 <|
  AllClassified.cons S6_6544 <|
  AllClassified.cons S6_6545 <|
  AllClassified.cons S6_6546 <|
  AllClassified.cons S6_6547 <|
  AllClassified.cons S6_6548 <|
  AllClassified.cons S6_6549 <|
  AllClassified.cons S6_6550 <|
  AllClassified.cons S6_6551 <|
  AllClassified.cons S6_6552 <|
  AllClassified.cons S6_6553 <|
  AllClassified.cons S6_6554 <|
  AllClassified.cons S6_6555 <|
  AllClassified.cons S6_6556 <|
  AllClassified.cons S6_6557 <|
  AllClassified.cons S6_6558 <|
  AllClassified.cons S6_6559 <|
  AllClassified.cons S6_6560 <|
  AllClassified.cons S6_6561 <|
  AllClassified.cons S6_6562 <|
  AllClassified.cons S6_6563 <|
  AllClassified.cons S6_6564 <|
  AllClassified.cons S6_6565 <|
  AllClassified.cons S6_6566 <|
  AllClassified.cons S6_6567 <|
  AllClassified.cons S6_6568 <|
  AllClassified.cons S6_6569 <|
  AllClassified.cons S6_6570 <|
  AllClassified.cons S6_6571 <|
  AllClassified.cons S6_6572 <|
  AllClassified.cons S6_6573 <|
  AllClassified.cons S6_6574 <|
  AllClassified.cons S6_6575 <|
  AllClassified.cons S6_6576 <|
  AllClassified.cons S6_6577 <|
  AllClassified.cons S6_6578 <|
  AllClassified.cons S6_6579 <|
  AllClassified.cons S6_6580 <|
  AllClassified.cons S6_6581 <|
  AllClassified.cons S6_6582 <|
  AllClassified.cons S6_6583 <|
  AllClassified.cons S6_6584 <|
  AllClassified.cons S6_6585 <|
  AllClassified.cons S6_6586 <|
  AllClassified.cons S6_6587 <|
  AllClassified.cons S6_6588 <|
  AllClassified.cons S6_6589 <|
  AllClassified.cons S6_6590 <|
  AllClassified.cons S6_6591 <|
  AllClassified.cons S6_6592 <|
  AllClassified.cons S6_6593 <|
  AllClassified.cons S6_6594 <|
  AllClassified.cons S6_6595 <|
  AllClassified.cons S6_6596 <|
  AllClassified.cons S6_6597 <|
  AllClassified.cons S6_6598 <|
  AllClassified.cons S6_6599 <|
  AllClassified.cons S6_6600 <|
  AllClassified.nil

end SemiBase.Census
