import SemiBase.Statement
import SemiBase.Catalogue.Order6.Part066
import Order6FinalL5TransferV3.Part236
import Order6FinalL5TransferV3.Part237
import Order6FinalL5TransferV3.Part238
import Order6FinalL5TransferV3.Part239
import Order6FinalL5TransferV3.Part240
import SemigroupBasis.CoRoots.Order6Day10.S3_15.Rank104ClassEndpoints
import SemigroupBasis.CoRoots.Order6Day10.SharedLevel3Section04.Section04ClassEndpoints
import SemigroupBasis.CoRoots.Order6Day15.B33.B33Catalogue
import SemigroupBasis.CoRoots.Order6Day7.S2_4.SeedS5_245
import SemigroupBasis.CoRoots.Order6Day9.S3_6.Rank014ClassEndpoints
import SemigroupBasis.CoRoots.Order6GenericCASMonoidPower
import SemigroupBasis.CoRoots.Order6GenericCASSubdirectS6_9800
import SemigroupBasis.CoRoots.Order6LeeLiP2G1Members
import SemigroupBasis.CoRoots.Order6Sunday.HeadLast.S9776Completeness
import SemigroupBasis.CoRoots.S6_9766EndpointCollapse
import SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_1230_Ad4b303415746_Part05
import SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_1231_Ad4b303415746_Part01
import SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_4016_Ad4b303415746_Part01
import SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_4022_Ad4b303415746_Part02
import SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_4024_Ad4b303415746_Part01
import SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_5612_Ad4b303415746_Part01
import SemigroupBasis.Generated.Order6DivisorTransfersPart35
import SemigroupBasis.Generated.Order6EmbeddingTransfersPart10
import SemigroupBasis.Generated.Order6GenericCASRootWrappers.S6_9802
import SemigroupBasis.Generated.Order6GenericCASRootWrappers.S6_9803
import SemigroupBasis.Generated.Order6GenericCASRootWrappers.S6_9804
import SemigroupBasis.Generated.Order6GenericCASRootWrappers.S6_9805
import SemigroupBasis.Generated.Order6RouteLocalRootAdapters
import research.formalization.order6.extension.order6_extension_2026_06_12_l5_extension_v1.Order6ExtensionTransfersPart10
import research.formalization.order6.extension.order6_extension_2026_06_12_l5_extension_v11.Order6ExtensionTransfersPart01
import research.formalization.order6.extension.order6_extension_2026_06_12_l5_extension_v14.Order6ExtensionTransfersPart02
import research.formalization.order6.extension.order6_extension_2026_06_12_l5_extension_v2.Order6ExtensionTransfersPart07
import research.formalization.order6.extension.order6_extension_2026_06_12_l5_extension_v3.Order6ExtensionTransfersPart03
import research.formalization.order6.extension.order6_extension_2026_06_12_l5_extension_v4.Order6ExtensionTransfersPart03
import research.formalization.order6.extension.order6_extension_2026_06_12_l5_extension_v6.Order6ExtensionTransfersPart05
import research.formalization.order6.extension.order6_extension_2026_06_12_l5_extension_v7.Order6ExtensionTransfersPart03
import research.formalization.order6.extension.order6_extension_2026_06_12_l5_extension_v8.Order6ExtensionTransfersPart01

/-!
# Census shard 066: classes `[6, 9751]` to `[6, 9900]`

For each class, the claim `Classified` from one endpoint theorem of the
development. The first alternative that checks is used: the endpoint for the
semigroup with the catalogue table, or for its opposite (the transposed table).
Generated by `scripts/generate_census.py`.
-/

set_option maxRecDepth 8192

namespace SemiBase.Census

theorem S6_9751 : Classified Catalogue.Order6.S6_9751 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9751.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9751.representative_basis)) (by decide +kernel)

theorem S6_9752 : Classified Catalogue.Order6.S6_9752 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9752.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9752.representative_basis)) (by decide +kernel)

theorem S6_9753 : Classified Catalogue.Order6.S6_9753 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day10.SharedLevel3Section04.Section04ClassEndpoints.S6_9753.basisFor) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day10.SharedLevel3Section04.Section04ClassEndpoints.S6_9753.basisFor)) (by decide +kernel)

theorem S6_9754 : Classified Catalogue.Order6.S6_9754 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV4.S6_9754.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV4.S6_9754.representative_basis)) (by decide +kernel)

theorem S6_9755 : Classified Catalogue.Order6.S6_9755 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV4.S6_9755.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV4.S6_9755.representative_basis)) (by decide +kernel)

theorem S6_9756 : Classified Catalogue.Order6.S6_9756 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9756.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9756.representative_basis)) (by decide +kernel)

theorem S6_9757 : Classified Catalogue.Order6.S6_9757 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9757.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9757.representative_basis)) (by decide +kernel)

theorem S6_9758 : Classified Catalogue.Order6.S6_9758 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV4.S6_9758.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV4.S6_9758.representative_basis)) (by decide +kernel)

theorem S6_9759 : Classified Catalogue.Order6.S6_9759 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9759.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9759.representative_basis)) (by decide +kernel)

theorem S6_9760 : Classified Catalogue.Order6.S6_9760 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_9760.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_9760.representative_basis)) (by decide +kernel)

theorem S6_9761 : Classified Catalogue.Order6.S6_9761 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9761.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9761.representative_basis)) (by decide +kernel)

theorem S6_9762 : Classified Catalogue.Order6.S6_9762 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_9762.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_9762.representative_basis)) (by decide +kernel)

theorem S6_9763 : Classified Catalogue.Order6.S6_9763 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9763.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9763.representative_basis)) (by decide +kernel)

theorem S6_9764 : Classified Catalogue.Order6.S6_9764 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9764.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9764.representative_basis)) (by decide +kernel)

theorem S6_9765 : Classified Catalogue.Order6.S6_9765 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9765.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9765.representative_basis)) (by decide +kernel)

theorem S6_9766 : Classified Catalogue.Order6.S6_9766 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.S6_9766EndpointCollapse.basis_complete) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.S6_9766EndpointCollapse.basis_complete)) (by decide +kernel)

theorem S6_9767 : Classified Catalogue.Order6.S6_9767 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9767.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9767.representative_basis)) (by decide +kernel)

theorem S6_9768 : Classified Catalogue.Order6.S6_9768 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV4.S6_9768.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV4.S6_9768.representative_basis)) (by decide +kernel)

theorem S6_9769 : Classified Catalogue.Order6.S6_9769 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9769.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9769.representative_basis)) (by decide +kernel)

theorem S6_9770 : Classified Catalogue.Order6.S6_9770 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV4.S6_9770.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV4.S6_9770.representative_basis)) (by decide +kernel)

theorem S6_9771 : Classified Catalogue.Order6.S6_9771 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9771.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9771.representative_basis)) (by decide +kernel)

theorem S6_9772 : Classified Catalogue.Order6.S6_9772 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_9772.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_9772.representative_basis)) (by decide +kernel)

theorem S6_9773 : Classified Catalogue.Order6.S6_9773 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9773.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9773.representative_basis)) (by decide +kernel)

theorem S6_9774 : Classified Catalogue.Order6.S6_9774 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9774.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9774.representative_basis)) (by decide +kernel)

theorem S6_9775 : Classified Catalogue.Order6.S6_9775 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9775.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9775.representative_basis)) (by decide +kernel)

theorem S6_9776 : Classified Catalogue.Order6.S6_9776 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Sunday.HeadLast.S9776.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Sunday.HeadLast.S9776.representative_basis)) (by decide +kernel)

theorem S6_9777 : Classified Catalogue.Order6.S6_9777 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day10.S3_15.Rank104ClassEndpoints.S6_9777.basisFor) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day10.S3_15.Rank104ClassEndpoints.S6_9777.basisFor)) (by decide +kernel)

theorem S6_9778 : Classified Catalogue.Order6.S6_9778 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV4.S6_9778.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV4.S6_9778.representative_basis)) (by decide +kernel)

theorem S6_9779 : Classified Catalogue.Order6.S6_9779 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_5612_Ad4b303415746_Part01.S6_9779.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_5612_Ad4b303415746_Part01.S6_9779.representative_basis)) (by decide +kernel)

theorem S6_9780 : Classified Catalogue.Order6.S6_9780 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_9780.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_9780.representative_basis)) (by decide +kernel)

theorem S6_9781 : Classified Catalogue.Order6.S6_9781 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9781.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9781.representative_basis)) (by decide +kernel)

theorem S6_9782 : Classified Catalogue.Order6.S6_9782 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_9782.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_9782.representative_basis)) (by decide +kernel)

theorem S6_9783 : Classified Catalogue.Order6.S6_9783 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9783.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9783.representative_basis)) (by decide +kernel)

theorem S6_9784 : Classified Catalogue.Order6.S6_9784 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9784.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9784.representative_basis)) (by decide +kernel)

theorem S6_9785 : Classified Catalogue.Order6.S6_9785 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9785.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9785.representative_basis)) (by decide +kernel)

theorem S6_9786 : Classified Catalogue.Order6.S6_9786 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9786.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9786.representative_basis)) (by decide +kernel)

theorem S6_9787 : Classified Catalogue.Order6.S6_9787 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day10.SharedLevel3Section04.Section04ClassEndpoints.S6_9787.basisFor) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day10.SharedLevel3Section04.Section04ClassEndpoints.S6_9787.basisFor)) (by decide +kernel)

theorem S6_9788 : Classified Catalogue.Order6.S6_9788 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_9788.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_9788.representative_basis)) (by decide +kernel)

theorem S6_9789 : Classified Catalogue.Order6.S6_9789 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9789.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9789.representative_basis)) (by decide +kernel)

theorem S6_9790 : Classified Catalogue.Order6.S6_9790 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9790.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9790.representative_basis)) (by decide +kernel)

theorem S6_9791 : Classified Catalogue.Order6.S6_9791 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9791.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9791.representative_basis)) (by decide +kernel)

theorem S6_9792 : Classified Catalogue.Order6.S6_9792 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_9792.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_9792.representative_basis)) (by decide +kernel)

theorem S6_9793 : Classified Catalogue.Order6.S6_9793 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9793.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9793.representative_basis)) (by decide +kernel)

theorem S6_9794 : Classified Catalogue.Order6.S6_9794 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_9794.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_9794.representative_basis)) (by decide +kernel)

theorem S6_9795 : Classified Catalogue.Order6.S6_9795 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9795.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9795.representative_basis)) (by decide +kernel)

theorem S6_9796 : Classified Catalogue.Order6.S6_9796 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_9796.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_9796.representative_basis)) (by decide +kernel)

theorem S6_9797 : Classified Catalogue.Order6.S6_9797 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9797.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9797.representative_basis)) (by decide +kernel)

theorem S6_9798 : Classified Catalogue.Order6.S6_9798 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9798.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9798.representative_basis)) (by decide +kernel)

theorem S6_9799 : Classified Catalogue.Order6.S6_9799 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9799.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9799.representative_basis)) (by decide +kernel)

theorem S6_9800 : Classified Catalogue.Order6.S6_9800 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6GenericCASSubdirectS6_9800.basisFor) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6GenericCASSubdirectS6_9800.basisFor)) (by decide +kernel)

theorem S6_9801 : Classified Catalogue.Order6.S6_9801 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6GenericCASMonoidPower.S6_9801_oppositeBasisFor) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6GenericCASMonoidPower.S6_9801_oppositeBasisFor)) (by decide +kernel)

theorem S6_9802 : Classified Catalogue.Order6.S6_9802 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6GenericCASRootWrappers.S6_9802.opposite_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6GenericCASRootWrappers.S6_9802.opposite_basis)) (by decide +kernel)

theorem S6_9803 : Classified Catalogue.Order6.S6_9803 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6GenericCASRootWrappers.S6_9803.opposite_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6GenericCASRootWrappers.S6_9803.opposite_basis)) (by decide +kernel)

theorem S6_9804 : Classified Catalogue.Order6.S6_9804 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6GenericCASRootWrappers.S6_9804.opposite_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6GenericCASRootWrappers.S6_9804.opposite_basis)) (by decide +kernel)

theorem S6_9805 : Classified Catalogue.Order6.S6_9805 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6GenericCASRootWrappers.S6_9805.opposite_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6GenericCASRootWrappers.S6_9805.opposite_basis)) (by decide +kernel)

theorem S6_9806 : Classified Catalogue.Order6.S6_9806 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9806.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9806.representative_basis)) (by decide +kernel)

theorem S6_9807 : Classified Catalogue.Order6.S6_9807 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_9807.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_9807.representative_basis)) (by decide +kernel)

theorem S6_9808 : Classified Catalogue.Order6.S6_9808 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9808.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9808.representative_basis)) (by decide +kernel)

theorem S6_9809 : Classified Catalogue.Order6.S6_9809 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_9809.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_9809.representative_basis)) (by decide +kernel)

theorem S6_9810 : Classified Catalogue.Order6.S6_9810 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_9810.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_9810.representative_basis)) (by decide +kernel)

theorem S6_9811 : Classified Catalogue.Order6.S6_9811 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV11.S6_9811.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV11.S6_9811.representative_basis)) (by decide +kernel)

theorem S6_9812 : Classified Catalogue.Order6.S6_9812 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_9812.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_9812.representative_basis)) (by decide +kernel)

theorem S6_9813 : Classified Catalogue.Order6.S6_9813 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV11.S6_9813.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV11.S6_9813.representative_basis)) (by decide +kernel)

theorem S6_9814 : Classified Catalogue.Order6.S6_9814 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_9814.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_9814.representative_basis)) (by decide +kernel)

theorem S6_9815 : Classified Catalogue.Order6.S6_9815 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV3.S6_9815.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV3.S6_9815.representative_basis)) (by decide +kernel)

theorem S6_9816 : Classified Catalogue.Order6.S6_9816 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9816.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9816.representative_basis)) (by decide +kernel)

theorem S6_9817 : Classified Catalogue.Order6.S6_9817 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6RouteLocalRootAdapters.S6_9817.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6RouteLocalRootAdapters.S6_9817.representative_basis)) (by decide +kernel)

theorem S6_9818 : Classified Catalogue.Order6.S6_9818 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_9818.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_9818.representative_basis)) (by decide +kernel)

theorem S6_9819 : Classified Catalogue.Order6.S6_9819 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_9819.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_9819.representative_basis)) (by decide +kernel)

theorem S6_9820 : Classified Catalogue.Order6.S6_9820 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_9820.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_9820.representative_basis)) (by decide +kernel)

theorem S6_9821 : Classified Catalogue.Order6.S6_9821 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV11.S6_9821.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV11.S6_9821.representative_basis)) (by decide +kernel)

theorem S6_9822 : Classified Catalogue.Order6.S6_9822 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_9822.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_9822.representative_basis)) (by decide +kernel)

theorem S6_9823 : Classified Catalogue.Order6.S6_9823 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_9823.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_9823.representative_basis)) (by decide +kernel)

theorem S6_9824 : Classified Catalogue.Order6.S6_9824 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV11.S6_9824.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV11.S6_9824.representative_basis)) (by decide +kernel)

theorem S6_9825 : Classified Catalogue.Order6.S6_9825 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_9825.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_9825.representative_basis)) (by decide +kernel)

theorem S6_9826 : Classified Catalogue.Order6.S6_9826 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV11.S6_9826.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV11.S6_9826.representative_basis)) (by decide +kernel)

theorem S6_9827 : Classified Catalogue.Order6.S6_9827 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_9827.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_9827.representative_basis)) (by decide +kernel)

theorem S6_9828 : Classified Catalogue.Order6.S6_9828 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9828.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9828.representative_basis)) (by decide +kernel)

theorem S6_9829 : Classified Catalogue.Order6.S6_9829 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV14.S6_9829.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV14.S6_9829.representative_basis)) (by decide +kernel)

theorem S6_9830 : Classified Catalogue.Order6.S6_9830 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9830.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9830.representative_basis)) (by decide +kernel)

theorem S6_9831 : Classified Catalogue.Order6.S6_9831 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV6.S6_9831.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV6.S6_9831.representative_basis)) (by decide +kernel)

theorem S6_9832 : Classified Catalogue.Order6.S6_9832 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9832.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9832.representative_basis)) (by decide +kernel)

theorem S6_9833 : Classified Catalogue.Order6.S6_9833 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_9833.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_9833.representative_basis)) (by decide +kernel)

theorem S6_9834 : Classified Catalogue.Order6.S6_9834 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_9834.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_9834.representative_basis)) (by decide +kernel)

theorem S6_9835 : Classified Catalogue.Order6.S6_9835 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_9835.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_9835.representative_basis)) (by decide +kernel)

theorem S6_9836 : Classified Catalogue.Order6.S6_9836 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_9836.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_9836.representative_basis)) (by decide +kernel)

theorem S6_9837 : Classified Catalogue.Order6.S6_9837 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_9837.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_9837.representative_basis)) (by decide +kernel)

theorem S6_9838 : Classified Catalogue.Order6.S6_9838 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_9838.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_9838.representative_basis)) (by decide +kernel)

theorem S6_9839 : Classified Catalogue.Order6.S6_9839 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV7.S6_9839.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV7.S6_9839.representative_basis)) (by decide +kernel)

theorem S6_9840 : Classified Catalogue.Order6.S6_9840 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV7.S6_9840.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV7.S6_9840.representative_basis)) (by decide +kernel)

theorem S6_9841 : Classified Catalogue.Order6.S6_9841 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9841.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9841.representative_basis)) (by decide +kernel)

theorem S6_9842 : Classified Catalogue.Order6.S6_9842 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9842.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9842.representative_basis)) (by decide +kernel)

theorem S6_9843 : Classified Catalogue.Order6.S6_9843 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_9843.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_9843.representative_basis)) (by decide +kernel)

theorem S6_9844 : Classified Catalogue.Order6.S6_9844 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV7.S6_9844.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV7.S6_9844.representative_basis)) (by decide +kernel)

theorem S6_9845 : Classified Catalogue.Order6.S6_9845 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV7.S6_9845.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV7.S6_9845.representative_basis)) (by decide +kernel)

theorem S6_9846 : Classified Catalogue.Order6.S6_9846 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_9846.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_9846.representative_basis)) (by decide +kernel)

theorem S6_9847 : Classified Catalogue.Order6.S6_9847 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_4016_Ad4b303415746_Part01.S6_9847.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_4016_Ad4b303415746_Part01.S6_9847.representative_basis)) (by decide +kernel)

theorem S6_9848 : Classified Catalogue.Order6.S6_9848 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV7.S6_9848.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV7.S6_9848.representative_basis)) (by decide +kernel)

theorem S6_9849 : Classified Catalogue.Order6.S6_9849 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9849.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9849.representative_basis)) (by decide +kernel)

theorem S6_9850 : Classified Catalogue.Order6.S6_9850 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9850.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9850.representative_basis)) (by decide +kernel)

theorem S6_9851 : Classified Catalogue.Order6.S6_9851 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9851.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9851.representative_basis)) (by decide +kernel)

theorem S6_9852 : Classified Catalogue.Order6.S6_9852 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9852.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9852.representative_basis)) (by decide +kernel)

theorem S6_9853 : Classified Catalogue.Order6.S6_9853 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9853.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9853.representative_basis)) (by decide +kernel)

theorem S6_9854 : Classified Catalogue.Order6.S6_9854 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9854.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9854.representative_basis)) (by decide +kernel)

theorem S6_9855 : Classified Catalogue.Order6.S6_9855 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV8.S6_9855.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV8.S6_9855.representative_basis)) (by decide +kernel)

theorem S6_9856 : Classified Catalogue.Order6.S6_9856 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9856.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9856.representative_basis)) (by decide +kernel)

theorem S6_9857 : Classified Catalogue.Order6.S6_9857 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV8.S6_9857.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV8.S6_9857.representative_basis)) (by decide +kernel)

theorem S6_9858 : Classified Catalogue.Order6.S6_9858 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_9858.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_9858.representative_basis)) (by decide +kernel)

theorem S6_9859 : Classified Catalogue.Order6.S6_9859 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV11.S6_9859.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV11.S6_9859.representative_basis)) (by decide +kernel)

theorem S6_9860 : Classified Catalogue.Order6.S6_9860 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_9860.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_9860.representative_basis)) (by decide +kernel)

theorem S6_9861 : Classified Catalogue.Order6.S6_9861 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV11.S6_9861.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV11.S6_9861.representative_basis)) (by decide +kernel)

theorem S6_9862 : Classified Catalogue.Order6.S6_9862 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9862.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9862.representative_basis)) (by decide +kernel)

theorem S6_9863 : Classified Catalogue.Order6.S6_9863 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV14.S6_9863.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV14.S6_9863.representative_basis)) (by decide +kernel)

theorem S6_9864 : Classified Catalogue.Order6.S6_9864 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_1230_Ad4b303415746_Part05.S6_9864.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_1230_Ad4b303415746_Part05.S6_9864.representative_basis)) (by decide +kernel)

theorem S6_9865 : Classified Catalogue.Order6.S6_9865 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV7.S6_9865.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV7.S6_9865.representative_basis)) (by decide +kernel)

theorem S6_9866 : Classified Catalogue.Order6.S6_9866 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_1231_Ad4b303415746_Part01.S6_9866.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_1231_Ad4b303415746_Part01.S6_9866.representative_basis)) (by decide +kernel)

theorem S6_9867 : Classified Catalogue.Order6.S6_9867 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9867.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9867.representative_basis)) (by decide +kernel)

theorem S6_9868 : Classified Catalogue.Order6.S6_9868 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9868.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9868.representative_basis)) (by decide +kernel)

theorem S6_9869 : Classified Catalogue.Order6.S6_9869 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV11.S6_9869.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV11.S6_9869.representative_basis)) (by decide +kernel)

theorem S6_9870 : Classified Catalogue.Order6.S6_9870 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_9870.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_9870.representative_basis)) (by decide +kernel)

theorem S6_9871 : Classified Catalogue.Order6.S6_9871 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9871.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9871.representative_basis)) (by decide +kernel)

theorem S6_9872 : Classified Catalogue.Order6.S6_9872 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9872.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9872.representative_basis)) (by decide +kernel)

theorem S6_9873 : Classified Catalogue.Order6.S6_9873 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day7.S2_4.Rank049.Seed.s6_9873_representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day7.S2_4.Rank049.Seed.s6_9873_representative_basis)) (by decide +kernel)

theorem S6_9874 : Classified Catalogue.Order6.S6_9874 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9874.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9874.representative_basis)) (by decide +kernel)

theorem S6_9875 : Classified Catalogue.Order6.S6_9875 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV11.S6_9875.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV11.S6_9875.representative_basis)) (by decide +kernel)

theorem S6_9876 : Classified Catalogue.Order6.S6_9876 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV11.S6_9876.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV11.S6_9876.representative_basis)) (by decide +kernel)

theorem S6_9877 : Classified Catalogue.Order6.S6_9877 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_4022_Ad4b303415746_Part02.S6_9877.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_4022_Ad4b303415746_Part02.S6_9877.representative_basis)) (by decide +kernel)

theorem S6_9878 : Classified Catalogue.Order6.S6_9878 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day15.B33.Catalogue.basisFor9878) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day15.B33.Catalogue.basisFor9878)) (by decide +kernel)

theorem S6_9879 : Classified Catalogue.Order6.S6_9879 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9879.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9879.representative_basis)) (by decide +kernel)

theorem S6_9880 : Classified Catalogue.Order6.S6_9880 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day9.S3_6.Rank014ClassEndpoints.S6_9880.basisFor) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6Day9.S3_6.Rank014ClassEndpoints.S6_9880.basisFor)) (by decide +kernel)

theorem S6_9881 : Classified Catalogue.Order6.S6_9881 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_4024_Ad4b303415746_Part01.S6_9881.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_4024_Ad4b303415746_Part01.S6_9881.representative_basis)) (by decide +kernel)

theorem S6_9882 : Classified Catalogue.Order6.S6_9882 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6RouteLocalRootAdapters.S6_9882.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6RouteLocalRootAdapters.S6_9882.representative_basis)) (by decide +kernel)

theorem S6_9883 : Classified Catalogue.Order6.S6_9883 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9883.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9883.representative_basis)) (by decide +kernel)

theorem S6_9884 : Classified Catalogue.Order6.S6_9884 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6LeeLiP2G1.Members.S6_9884.basisFor) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.CoRoots.Order6LeeLiP2G1.Members.S6_9884.basisFor)) (by decide +kernel)

theorem S6_9885 : Classified Catalogue.Order6.S6_9885 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_9885.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_9885.representative_basis)) (by decide +kernel)

theorem S6_9886 : Classified Catalogue.Order6.S6_9886 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_9886.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_9886.representative_basis)) (by decide +kernel)

theorem S6_9887 : Classified Catalogue.Order6.S6_9887 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9887.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9887.representative_basis)) (by decide +kernel)

theorem S6_9888 : Classified Catalogue.Order6.S6_9888 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_9888.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_9888.representative_basis)) (by decide +kernel)

theorem S6_9889 : Classified Catalogue.Order6.S6_9889 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9889.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9889.representative_basis)) (by decide +kernel)

theorem S6_9890 : Classified Catalogue.Order6.S6_9890 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9890.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9890.representative_basis)) (by decide +kernel)

theorem S6_9891 : Classified Catalogue.Order6.S6_9891 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_9891.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_9891.representative_basis)) (by decide +kernel)

theorem S6_9892 : Classified Catalogue.Order6.S6_9892 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9892.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9892.representative_basis)) (by decide +kernel)

theorem S6_9893 : Classified Catalogue.Order6.S6_9893 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_9893.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_9893.representative_basis)) (by decide +kernel)

theorem S6_9894 : Classified Catalogue.Order6.S6_9894 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9894.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9894.representative_basis)) (by decide +kernel)

theorem S6_9895 : Classified Catalogue.Order6.S6_9895 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_9895.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_9895.representative_basis)) (by decide +kernel)

theorem S6_9896 : Classified Catalogue.Order6.S6_9896 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9896.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9896.representative_basis)) (by decide +kernel)

theorem S6_9897 : Classified Catalogue.Order6.S6_9897 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV6.S6_9897.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV6.S6_9897.representative_basis)) (by decide +kernel)

theorem S6_9898 : Classified Catalogue.Order6.S6_9898 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9898.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9898.representative_basis)) (by decide +kernel)

theorem S6_9899 : Classified Catalogue.Order6.S6_9899 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_9899.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_9899.representative_basis)) (by decide +kernel)

theorem S6_9900 : Classified Catalogue.Order6.S6_9900 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9900.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_9900.representative_basis)) (by decide +kernel)

/-- Every class of part 066 of the catalogue is classified. -/
theorem shard066 : AllClassified Catalogue.Order6.part066 :=
  AllClassified.cons S6_9751 <|
  AllClassified.cons S6_9752 <|
  AllClassified.cons S6_9753 <|
  AllClassified.cons S6_9754 <|
  AllClassified.cons S6_9755 <|
  AllClassified.cons S6_9756 <|
  AllClassified.cons S6_9757 <|
  AllClassified.cons S6_9758 <|
  AllClassified.cons S6_9759 <|
  AllClassified.cons S6_9760 <|
  AllClassified.cons S6_9761 <|
  AllClassified.cons S6_9762 <|
  AllClassified.cons S6_9763 <|
  AllClassified.cons S6_9764 <|
  AllClassified.cons S6_9765 <|
  AllClassified.cons S6_9766 <|
  AllClassified.cons S6_9767 <|
  AllClassified.cons S6_9768 <|
  AllClassified.cons S6_9769 <|
  AllClassified.cons S6_9770 <|
  AllClassified.cons S6_9771 <|
  AllClassified.cons S6_9772 <|
  AllClassified.cons S6_9773 <|
  AllClassified.cons S6_9774 <|
  AllClassified.cons S6_9775 <|
  AllClassified.cons S6_9776 <|
  AllClassified.cons S6_9777 <|
  AllClassified.cons S6_9778 <|
  AllClassified.cons S6_9779 <|
  AllClassified.cons S6_9780 <|
  AllClassified.cons S6_9781 <|
  AllClassified.cons S6_9782 <|
  AllClassified.cons S6_9783 <|
  AllClassified.cons S6_9784 <|
  AllClassified.cons S6_9785 <|
  AllClassified.cons S6_9786 <|
  AllClassified.cons S6_9787 <|
  AllClassified.cons S6_9788 <|
  AllClassified.cons S6_9789 <|
  AllClassified.cons S6_9790 <|
  AllClassified.cons S6_9791 <|
  AllClassified.cons S6_9792 <|
  AllClassified.cons S6_9793 <|
  AllClassified.cons S6_9794 <|
  AllClassified.cons S6_9795 <|
  AllClassified.cons S6_9796 <|
  AllClassified.cons S6_9797 <|
  AllClassified.cons S6_9798 <|
  AllClassified.cons S6_9799 <|
  AllClassified.cons S6_9800 <|
  AllClassified.cons S6_9801 <|
  AllClassified.cons S6_9802 <|
  AllClassified.cons S6_9803 <|
  AllClassified.cons S6_9804 <|
  AllClassified.cons S6_9805 <|
  AllClassified.cons S6_9806 <|
  AllClassified.cons S6_9807 <|
  AllClassified.cons S6_9808 <|
  AllClassified.cons S6_9809 <|
  AllClassified.cons S6_9810 <|
  AllClassified.cons S6_9811 <|
  AllClassified.cons S6_9812 <|
  AllClassified.cons S6_9813 <|
  AllClassified.cons S6_9814 <|
  AllClassified.cons S6_9815 <|
  AllClassified.cons S6_9816 <|
  AllClassified.cons S6_9817 <|
  AllClassified.cons S6_9818 <|
  AllClassified.cons S6_9819 <|
  AllClassified.cons S6_9820 <|
  AllClassified.cons S6_9821 <|
  AllClassified.cons S6_9822 <|
  AllClassified.cons S6_9823 <|
  AllClassified.cons S6_9824 <|
  AllClassified.cons S6_9825 <|
  AllClassified.cons S6_9826 <|
  AllClassified.cons S6_9827 <|
  AllClassified.cons S6_9828 <|
  AllClassified.cons S6_9829 <|
  AllClassified.cons S6_9830 <|
  AllClassified.cons S6_9831 <|
  AllClassified.cons S6_9832 <|
  AllClassified.cons S6_9833 <|
  AllClassified.cons S6_9834 <|
  AllClassified.cons S6_9835 <|
  AllClassified.cons S6_9836 <|
  AllClassified.cons S6_9837 <|
  AllClassified.cons S6_9838 <|
  AllClassified.cons S6_9839 <|
  AllClassified.cons S6_9840 <|
  AllClassified.cons S6_9841 <|
  AllClassified.cons S6_9842 <|
  AllClassified.cons S6_9843 <|
  AllClassified.cons S6_9844 <|
  AllClassified.cons S6_9845 <|
  AllClassified.cons S6_9846 <|
  AllClassified.cons S6_9847 <|
  AllClassified.cons S6_9848 <|
  AllClassified.cons S6_9849 <|
  AllClassified.cons S6_9850 <|
  AllClassified.cons S6_9851 <|
  AllClassified.cons S6_9852 <|
  AllClassified.cons S6_9853 <|
  AllClassified.cons S6_9854 <|
  AllClassified.cons S6_9855 <|
  AllClassified.cons S6_9856 <|
  AllClassified.cons S6_9857 <|
  AllClassified.cons S6_9858 <|
  AllClassified.cons S6_9859 <|
  AllClassified.cons S6_9860 <|
  AllClassified.cons S6_9861 <|
  AllClassified.cons S6_9862 <|
  AllClassified.cons S6_9863 <|
  AllClassified.cons S6_9864 <|
  AllClassified.cons S6_9865 <|
  AllClassified.cons S6_9866 <|
  AllClassified.cons S6_9867 <|
  AllClassified.cons S6_9868 <|
  AllClassified.cons S6_9869 <|
  AllClassified.cons S6_9870 <|
  AllClassified.cons S6_9871 <|
  AllClassified.cons S6_9872 <|
  AllClassified.cons S6_9873 <|
  AllClassified.cons S6_9874 <|
  AllClassified.cons S6_9875 <|
  AllClassified.cons S6_9876 <|
  AllClassified.cons S6_9877 <|
  AllClassified.cons S6_9878 <|
  AllClassified.cons S6_9879 <|
  AllClassified.cons S6_9880 <|
  AllClassified.cons S6_9881 <|
  AllClassified.cons S6_9882 <|
  AllClassified.cons S6_9883 <|
  AllClassified.cons S6_9884 <|
  AllClassified.cons S6_9885 <|
  AllClassified.cons S6_9886 <|
  AllClassified.cons S6_9887 <|
  AllClassified.cons S6_9888 <|
  AllClassified.cons S6_9889 <|
  AllClassified.cons S6_9890 <|
  AllClassified.cons S6_9891 <|
  AllClassified.cons S6_9892 <|
  AllClassified.cons S6_9893 <|
  AllClassified.cons S6_9894 <|
  AllClassified.cons S6_9895 <|
  AllClassified.cons S6_9896 <|
  AllClassified.cons S6_9897 <|
  AllClassified.cons S6_9898 <|
  AllClassified.cons S6_9899 <|
  AllClassified.cons S6_9900 <|
  AllClassified.nil

end SemiBase.Census
