import SemiBase.Statement
import SemiBase.Catalogue.Order6.Part072
import Order6FinalL5TransferV3.Part254
import Order6FinalL5TransferV3.Part255
import Order6FinalL5TransferV3.Part256
import Order6FinalL5TransferV3.Part257
import SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_3306_Ad4b303415746_Part01
import SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_3307_Ad4b303415746_Part02
import SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_3308_Ad4b303415746_Part03
import SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_4117_Ad4b303415746_Part01
import SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_5954_Ad4b303415746_Part02
import SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_5959_Ad4b303415746_Part01
import SemigroupBasis.Generated.Order6DivisorTransfersPart36
import SemigroupBasis.Generated.Order6EmbeddingTransfersPart11
import SemigroupBasis.Generated.Order6EmbeddingTransfersPart12
import research.formalization.order6.extension.order6_extension_2026_06_12_l5_extension_v1.Order6ExtensionTransfersPart11
import research.formalization.order6.extension.order6_extension_2026_06_12_l5_extension_v2.Order6ExtensionTransfersPart09
import research.formalization.order6.extension.order6_extension_2026_06_12_l5_extension_v3.Order6ExtensionTransfersPart03
import research.formalization.order6.extension.order6_extension_2026_06_12_l5_extension_v5.Order6ExtensionTransfersPart04
import research.formalization.order6.extension.order6_extension_2026_06_12_l5_extension_v5.Order6ExtensionTransfersPart05
import research.formalization.order6.extension.order6_extension_2026_06_12_l5_extension_v6.Order6ExtensionTransfersPart05
import research.formalization.order6.extension.order6_extension_2026_06_12_l5_extension_v7.Order6ExtensionTransfersPart04
import research.formalization.order6.extension.order6_extension_2026_06_12_l5_extension_v8.Order6ExtensionTransfersPart02

/-!
# Census shard 072: classes `[6, 10651]` to `[6, 10800]`

For each class, the claim `Classified` from one endpoint theorem of the
development. The first alternative that checks is used: the endpoint for the
semigroup with the catalogue table, or for its opposite (the transposed table).
Generated by `scripts/generate_census.py`.
-/

set_option maxRecDepth 8192

namespace SemiBase.Census

theorem S6_10651 : Classified Catalogue.Order6.S6_10651 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_10651.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_10651.representative_basis)) (by decide +kernel)

theorem S6_10652 : Classified Catalogue.Order6.S6_10652 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_10652.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_10652.representative_basis)) (by decide +kernel)

theorem S6_10653 : Classified Catalogue.Order6.S6_10653 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_10653.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_10653.representative_basis)) (by decide +kernel)

theorem S6_10654 : Classified Catalogue.Order6.S6_10654 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_10654.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_10654.representative_basis)) (by decide +kernel)

theorem S6_10655 : Classified Catalogue.Order6.S6_10655 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV8.S6_10655.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV8.S6_10655.representative_basis)) (by decide +kernel)

theorem S6_10656 : Classified Catalogue.Order6.S6_10656 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_10656.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_10656.representative_basis)) (by decide +kernel)

theorem S6_10657 : Classified Catalogue.Order6.S6_10657 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_10657.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_10657.representative_basis)) (by decide +kernel)

theorem S6_10658 : Classified Catalogue.Order6.S6_10658 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_10658.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_10658.representative_basis)) (by decide +kernel)

theorem S6_10659 : Classified Catalogue.Order6.S6_10659 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10659.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10659.representative_basis)) (by decide +kernel)

theorem S6_10660 : Classified Catalogue.Order6.S6_10660 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10660.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10660.representative_basis)) (by decide +kernel)

theorem S6_10661 : Classified Catalogue.Order6.S6_10661 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_10661.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_10661.representative_basis)) (by decide +kernel)

theorem S6_10662 : Classified Catalogue.Order6.S6_10662 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_10662.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_10662.representative_basis)) (by decide +kernel)

theorem S6_10663 : Classified Catalogue.Order6.S6_10663 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10663.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10663.representative_basis)) (by decide +kernel)

theorem S6_10664 : Classified Catalogue.Order6.S6_10664 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_10664.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_10664.representative_basis)) (by decide +kernel)

theorem S6_10665 : Classified Catalogue.Order6.S6_10665 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_10665.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_10665.representative_basis)) (by decide +kernel)

theorem S6_10666 : Classified Catalogue.Order6.S6_10666 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV8.S6_10666.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV8.S6_10666.representative_basis)) (by decide +kernel)

theorem S6_10667 : Classified Catalogue.Order6.S6_10667 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV8.S6_10667.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV8.S6_10667.representative_basis)) (by decide +kernel)

theorem S6_10668 : Classified Catalogue.Order6.S6_10668 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_10668.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_10668.representative_basis)) (by decide +kernel)

theorem S6_10669 : Classified Catalogue.Order6.S6_10669 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_10669.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_10669.representative_basis)) (by decide +kernel)

theorem S6_10670 : Classified Catalogue.Order6.S6_10670 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_10670.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_10670.representative_basis)) (by decide +kernel)

theorem S6_10671 : Classified Catalogue.Order6.S6_10671 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10671.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10671.representative_basis)) (by decide +kernel)

theorem S6_10672 : Classified Catalogue.Order6.S6_10672 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10672.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10672.representative_basis)) (by decide +kernel)

theorem S6_10673 : Classified Catalogue.Order6.S6_10673 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_10673.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_10673.representative_basis)) (by decide +kernel)

theorem S6_10674 : Classified Catalogue.Order6.S6_10674 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_10674.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_10674.representative_basis)) (by decide +kernel)

theorem S6_10675 : Classified Catalogue.Order6.S6_10675 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_4117_Ad4b303415746_Part01.S6_10675.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_4117_Ad4b303415746_Part01.S6_10675.representative_basis)) (by decide +kernel)

theorem S6_10676 : Classified Catalogue.Order6.S6_10676 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_5959_Ad4b303415746_Part01.S6_10676.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_5959_Ad4b303415746_Part01.S6_10676.representative_basis)) (by decide +kernel)

theorem S6_10677 : Classified Catalogue.Order6.S6_10677 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10677.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10677.representative_basis)) (by decide +kernel)

theorem S6_10678 : Classified Catalogue.Order6.S6_10678 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10678.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10678.representative_basis)) (by decide +kernel)

theorem S6_10679 : Classified Catalogue.Order6.S6_10679 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_4117_Ad4b303415746_Part01.S6_10679.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_4117_Ad4b303415746_Part01.S6_10679.representative_basis)) (by decide +kernel)

theorem S6_10680 : Classified Catalogue.Order6.S6_10680 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_5954_Ad4b303415746_Part02.S6_10680.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_5954_Ad4b303415746_Part02.S6_10680.representative_basis)) (by decide +kernel)

theorem S6_10681 : Classified Catalogue.Order6.S6_10681 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_5959_Ad4b303415746_Part01.S6_10681.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_5959_Ad4b303415746_Part01.S6_10681.representative_basis)) (by decide +kernel)

theorem S6_10682 : Classified Catalogue.Order6.S6_10682 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10682.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10682.representative_basis)) (by decide +kernel)

theorem S6_10683 : Classified Catalogue.Order6.S6_10683 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10683.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10683.representative_basis)) (by decide +kernel)

theorem S6_10684 : Classified Catalogue.Order6.S6_10684 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10684.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10684.representative_basis)) (by decide +kernel)

theorem S6_10685 : Classified Catalogue.Order6.S6_10685 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10685.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10685.representative_basis)) (by decide +kernel)

theorem S6_10686 : Classified Catalogue.Order6.S6_10686 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10686.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10686.representative_basis)) (by decide +kernel)

theorem S6_10687 : Classified Catalogue.Order6.S6_10687 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_10687.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_10687.representative_basis)) (by decide +kernel)

theorem S6_10688 : Classified Catalogue.Order6.S6_10688 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_10688.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_10688.representative_basis)) (by decide +kernel)

theorem S6_10689 : Classified Catalogue.Order6.S6_10689 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10689.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10689.representative_basis)) (by decide +kernel)

theorem S6_10690 : Classified Catalogue.Order6.S6_10690 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10690.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10690.representative_basis)) (by decide +kernel)

theorem S6_10691 : Classified Catalogue.Order6.S6_10691 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV5.S6_10691.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV5.S6_10691.representative_basis)) (by decide +kernel)

theorem S6_10692 : Classified Catalogue.Order6.S6_10692 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_10692.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_10692.representative_basis)) (by decide +kernel)

theorem S6_10693 : Classified Catalogue.Order6.S6_10693 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_10693.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_10693.representative_basis)) (by decide +kernel)

theorem S6_10694 : Classified Catalogue.Order6.S6_10694 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_10694.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_10694.representative_basis)) (by decide +kernel)

theorem S6_10695 : Classified Catalogue.Order6.S6_10695 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_10695.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_10695.representative_basis)) (by decide +kernel)

theorem S6_10696 : Classified Catalogue.Order6.S6_10696 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV3.S6_10696.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV3.S6_10696.representative_basis)) (by decide +kernel)

theorem S6_10697 : Classified Catalogue.Order6.S6_10697 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_10697.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_10697.representative_basis)) (by decide +kernel)

theorem S6_10698 : Classified Catalogue.Order6.S6_10698 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_10698.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_10698.representative_basis)) (by decide +kernel)

theorem S6_10699 : Classified Catalogue.Order6.S6_10699 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10699.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10699.representative_basis)) (by decide +kernel)

theorem S6_10700 : Classified Catalogue.Order6.S6_10700 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10700.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10700.representative_basis)) (by decide +kernel)

theorem S6_10701 : Classified Catalogue.Order6.S6_10701 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV5.S6_10701.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV5.S6_10701.representative_basis)) (by decide +kernel)

theorem S6_10702 : Classified Catalogue.Order6.S6_10702 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_10702.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_10702.representative_basis)) (by decide +kernel)

theorem S6_10703 : Classified Catalogue.Order6.S6_10703 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_10703.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_10703.representative_basis)) (by decide +kernel)

theorem S6_10704 : Classified Catalogue.Order6.S6_10704 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_10704.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_10704.representative_basis)) (by decide +kernel)

theorem S6_10705 : Classified Catalogue.Order6.S6_10705 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_10705.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_10705.representative_basis)) (by decide +kernel)

theorem S6_10706 : Classified Catalogue.Order6.S6_10706 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV3.S6_10706.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV3.S6_10706.representative_basis)) (by decide +kernel)

theorem S6_10707 : Classified Catalogue.Order6.S6_10707 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_10707.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_10707.representative_basis)) (by decide +kernel)

theorem S6_10708 : Classified Catalogue.Order6.S6_10708 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV6.S6_10708.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV6.S6_10708.representative_basis)) (by decide +kernel)

theorem S6_10709 : Classified Catalogue.Order6.S6_10709 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_10709.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_10709.representative_basis)) (by decide +kernel)

theorem S6_10710 : Classified Catalogue.Order6.S6_10710 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV6.S6_10710.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV6.S6_10710.representative_basis)) (by decide +kernel)

theorem S6_10711 : Classified Catalogue.Order6.S6_10711 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10711.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10711.representative_basis)) (by decide +kernel)

theorem S6_10712 : Classified Catalogue.Order6.S6_10712 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10712.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10712.representative_basis)) (by decide +kernel)

theorem S6_10713 : Classified Catalogue.Order6.S6_10713 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10713.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10713.representative_basis)) (by decide +kernel)

theorem S6_10714 : Classified Catalogue.Order6.S6_10714 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10714.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10714.representative_basis)) (by decide +kernel)

theorem S6_10715 : Classified Catalogue.Order6.S6_10715 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV5.S6_10715.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV5.S6_10715.representative_basis)) (by decide +kernel)

theorem S6_10716 : Classified Catalogue.Order6.S6_10716 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV5.S6_10716.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV5.S6_10716.representative_basis)) (by decide +kernel)

theorem S6_10717 : Classified Catalogue.Order6.S6_10717 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_10717.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_10717.representative_basis)) (by decide +kernel)

theorem S6_10718 : Classified Catalogue.Order6.S6_10718 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_10718.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_10718.representative_basis)) (by decide +kernel)

theorem S6_10719 : Classified Catalogue.Order6.S6_10719 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10719.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10719.representative_basis)) (by decide +kernel)

theorem S6_10720 : Classified Catalogue.Order6.S6_10720 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10720.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10720.representative_basis)) (by decide +kernel)

theorem S6_10721 : Classified Catalogue.Order6.S6_10721 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_10721.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_10721.representative_basis)) (by decide +kernel)

theorem S6_10722 : Classified Catalogue.Order6.S6_10722 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_10722.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_10722.representative_basis)) (by decide +kernel)

theorem S6_10723 : Classified Catalogue.Order6.S6_10723 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10723.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10723.representative_basis)) (by decide +kernel)

theorem S6_10724 : Classified Catalogue.Order6.S6_10724 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10724.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10724.representative_basis)) (by decide +kernel)

theorem S6_10725 : Classified Catalogue.Order6.S6_10725 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_10725.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_10725.representative_basis)) (by decide +kernel)

theorem S6_10726 : Classified Catalogue.Order6.S6_10726 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_10726.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_10726.representative_basis)) (by decide +kernel)

theorem S6_10727 : Classified Catalogue.Order6.S6_10727 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10727.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10727.representative_basis)) (by decide +kernel)

theorem S6_10728 : Classified Catalogue.Order6.S6_10728 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10728.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10728.representative_basis)) (by decide +kernel)

theorem S6_10729 : Classified Catalogue.Order6.S6_10729 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10729.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10729.representative_basis)) (by decide +kernel)

theorem S6_10730 : Classified Catalogue.Order6.S6_10730 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10730.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10730.representative_basis)) (by decide +kernel)

theorem S6_10731 : Classified Catalogue.Order6.S6_10731 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10731.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10731.representative_basis)) (by decide +kernel)

theorem S6_10732 : Classified Catalogue.Order6.S6_10732 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV5.S6_10732.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV5.S6_10732.representative_basis)) (by decide +kernel)

theorem S6_10733 : Classified Catalogue.Order6.S6_10733 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10733.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10733.representative_basis)) (by decide +kernel)

theorem S6_10734 : Classified Catalogue.Order6.S6_10734 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10734.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10734.representative_basis)) (by decide +kernel)

theorem S6_10735 : Classified Catalogue.Order6.S6_10735 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV5.S6_10735.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV5.S6_10735.representative_basis)) (by decide +kernel)

theorem S6_10736 : Classified Catalogue.Order6.S6_10736 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_10736.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_10736.representative_basis)) (by decide +kernel)

theorem S6_10737 : Classified Catalogue.Order6.S6_10737 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_10737.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_10737.representative_basis)) (by decide +kernel)

theorem S6_10738 : Classified Catalogue.Order6.S6_10738 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_10738.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_10738.representative_basis)) (by decide +kernel)

theorem S6_10739 : Classified Catalogue.Order6.S6_10739 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_10739.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_10739.representative_basis)) (by decide +kernel)

theorem S6_10740 : Classified Catalogue.Order6.S6_10740 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_10740.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_10740.representative_basis)) (by decide +kernel)

theorem S6_10741 : Classified Catalogue.Order6.S6_10741 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_10741.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_10741.representative_basis)) (by decide +kernel)

theorem S6_10742 : Classified Catalogue.Order6.S6_10742 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_10742.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_10742.representative_basis)) (by decide +kernel)

theorem S6_10743 : Classified Catalogue.Order6.S6_10743 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_10743.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_10743.representative_basis)) (by decide +kernel)

theorem S6_10744 : Classified Catalogue.Order6.S6_10744 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_10744.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_10744.representative_basis)) (by decide +kernel)

theorem S6_10745 : Classified Catalogue.Order6.S6_10745 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV7.S6_10745.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV7.S6_10745.representative_basis)) (by decide +kernel)

theorem S6_10746 : Classified Catalogue.Order6.S6_10746 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_10746.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_10746.representative_basis)) (by decide +kernel)

theorem S6_10747 : Classified Catalogue.Order6.S6_10747 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_10747.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_10747.representative_basis)) (by decide +kernel)

theorem S6_10748 : Classified Catalogue.Order6.S6_10748 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_10748.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_10748.representative_basis)) (by decide +kernel)

theorem S6_10749 : Classified Catalogue.Order6.S6_10749 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_10749.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_10749.representative_basis)) (by decide +kernel)

theorem S6_10750 : Classified Catalogue.Order6.S6_10750 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_10750.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_10750.representative_basis)) (by decide +kernel)

theorem S6_10751 : Classified Catalogue.Order6.S6_10751 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV6.S6_10751.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV6.S6_10751.representative_basis)) (by decide +kernel)

theorem S6_10752 : Classified Catalogue.Order6.S6_10752 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_10752.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_10752.representative_basis)) (by decide +kernel)

theorem S6_10753 : Classified Catalogue.Order6.S6_10753 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV6.S6_10753.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV6.S6_10753.representative_basis)) (by decide +kernel)

theorem S6_10754 : Classified Catalogue.Order6.S6_10754 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV7.S6_10754.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV7.S6_10754.representative_basis)) (by decide +kernel)

theorem S6_10755 : Classified Catalogue.Order6.S6_10755 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV6.S6_10755.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV6.S6_10755.representative_basis)) (by decide +kernel)

theorem S6_10756 : Classified Catalogue.Order6.S6_10756 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_10756.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_10756.representative_basis)) (by decide +kernel)

theorem S6_10757 : Classified Catalogue.Order6.S6_10757 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_10757.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_10757.representative_basis)) (by decide +kernel)

theorem S6_10758 : Classified Catalogue.Order6.S6_10758 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_3307_Ad4b303415746_Part02.S6_10758.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_3307_Ad4b303415746_Part02.S6_10758.representative_basis)) (by decide +kernel)

theorem S6_10759 : Classified Catalogue.Order6.S6_10759 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_3308_Ad4b303415746_Part03.S6_10759.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_3308_Ad4b303415746_Part03.S6_10759.representative_basis)) (by decide +kernel)

theorem S6_10760 : Classified Catalogue.Order6.S6_10760 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_10760.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_10760.representative_basis)) (by decide +kernel)

theorem S6_10761 : Classified Catalogue.Order6.S6_10761 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10761.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10761.representative_basis)) (by decide +kernel)

theorem S6_10762 : Classified Catalogue.Order6.S6_10762 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10762.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10762.representative_basis)) (by decide +kernel)

theorem S6_10763 : Classified Catalogue.Order6.S6_10763 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV5.S6_10763.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV5.S6_10763.representative_basis)) (by decide +kernel)

theorem S6_10764 : Classified Catalogue.Order6.S6_10764 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV5.S6_10764.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV5.S6_10764.representative_basis)) (by decide +kernel)

theorem S6_10765 : Classified Catalogue.Order6.S6_10765 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10765.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10765.representative_basis)) (by decide +kernel)

theorem S6_10766 : Classified Catalogue.Order6.S6_10766 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV5.S6_10766.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV5.S6_10766.representative_basis)) (by decide +kernel)

theorem S6_10767 : Classified Catalogue.Order6.S6_10767 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_10767.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_10767.representative_basis)) (by decide +kernel)

theorem S6_10768 : Classified Catalogue.Order6.S6_10768 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_10768.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_10768.representative_basis)) (by decide +kernel)

theorem S6_10769 : Classified Catalogue.Order6.S6_10769 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10769.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10769.representative_basis)) (by decide +kernel)

theorem S6_10770 : Classified Catalogue.Order6.S6_10770 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10770.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10770.representative_basis)) (by decide +kernel)

theorem S6_10771 : Classified Catalogue.Order6.S6_10771 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV5.S6_10771.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV5.S6_10771.representative_basis)) (by decide +kernel)

theorem S6_10772 : Classified Catalogue.Order6.S6_10772 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_10772.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_10772.representative_basis)) (by decide +kernel)

theorem S6_10773 : Classified Catalogue.Order6.S6_10773 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_10773.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_10773.representative_basis)) (by decide +kernel)

theorem S6_10774 : Classified Catalogue.Order6.S6_10774 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_10774.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_10774.representative_basis)) (by decide +kernel)

theorem S6_10775 : Classified Catalogue.Order6.S6_10775 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_10775.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_10775.representative_basis)) (by decide +kernel)

theorem S6_10776 : Classified Catalogue.Order6.S6_10776 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_10776.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_10776.representative_basis)) (by decide +kernel)

theorem S6_10777 : Classified Catalogue.Order6.S6_10777 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10777.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10777.representative_basis)) (by decide +kernel)

theorem S6_10778 : Classified Catalogue.Order6.S6_10778 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10778.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10778.representative_basis)) (by decide +kernel)

theorem S6_10779 : Classified Catalogue.Order6.S6_10779 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV5.S6_10779.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV5.S6_10779.representative_basis)) (by decide +kernel)

theorem S6_10780 : Classified Catalogue.Order6.S6_10780 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10780.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10780.representative_basis)) (by decide +kernel)

theorem S6_10781 : Classified Catalogue.Order6.S6_10781 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10781.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10781.representative_basis)) (by decide +kernel)

theorem S6_10782 : Classified Catalogue.Order6.S6_10782 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV5.S6_10782.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV5.S6_10782.representative_basis)) (by decide +kernel)

theorem S6_10783 : Classified Catalogue.Order6.S6_10783 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_10783.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_10783.representative_basis)) (by decide +kernel)

theorem S6_10784 : Classified Catalogue.Order6.S6_10784 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10784.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10784.representative_basis)) (by decide +kernel)

theorem S6_10785 : Classified Catalogue.Order6.S6_10785 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10785.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10785.representative_basis)) (by decide +kernel)

theorem S6_10786 : Classified Catalogue.Order6.S6_10786 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_10786.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_10786.representative_basis)) (by decide +kernel)

theorem S6_10787 : Classified Catalogue.Order6.S6_10787 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10787.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10787.representative_basis)) (by decide +kernel)

theorem S6_10788 : Classified Catalogue.Order6.S6_10788 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10788.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6FinalL5TransferV3.S6_10788.representative_basis)) (by decide +kernel)

theorem S6_10789 : Classified Catalogue.Order6.S6_10789 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV5.S6_10789.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV5.S6_10789.representative_basis)) (by decide +kernel)

theorem S6_10790 : Classified Catalogue.Order6.S6_10790 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_10790.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_10790.representative_basis)) (by decide +kernel)

theorem S6_10791 : Classified Catalogue.Order6.S6_10791 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_10791.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_10791.representative_basis)) (by decide +kernel)

theorem S6_10792 : Classified Catalogue.Order6.S6_10792 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_10792.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_10792.representative_basis)) (by decide +kernel)

theorem S6_10793 : Classified Catalogue.Order6.S6_10793 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_10793.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_10793.representative_basis)) (by decide +kernel)

theorem S6_10794 : Classified Catalogue.Order6.S6_10794 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_10794.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_10794.representative_basis)) (by decide +kernel)

theorem S6_10795 : Classified Catalogue.Order6.S6_10795 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_10795.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV1.S6_10795.representative_basis)) (by decide +kernel)

theorem S6_10796 : Classified Catalogue.Order6.S6_10796 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_10796.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6EmbeddingTransfers.S6_10796.representative_basis)) (by decide +kernel)

theorem S6_10797 : Classified Catalogue.Order6.S6_10797 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV6.S6_10797.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV6.S6_10797.representative_basis)) (by decide +kernel)

theorem S6_10798 : Classified Catalogue.Order6.S6_10798 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_10798.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6ExtensionTransfersV2.S6_10798.representative_basis)) (by decide +kernel)

theorem S6_10799 : Classified Catalogue.Order6.S6_10799 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_3306_Ad4b303415746_Part01.S6_10799.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DirectPowerAvailableV3.S6_3306_Ad4b303415746_Part01.S6_10799.representative_basis)) (by decide +kernel)

theorem S6_10800 : Classified Catalogue.Order6.S6_10800 := by
  first
  | exact classified_of_finitelyBased (by decide +kernel) (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_10800.representative_basis) (by decide +kernel)
  | exact classified_of_finitelyBased (by decide +kernel) (finitelyBased_opposite (SemigroupBasis.BasisFor.finitelyBased SemigroupBasis.Generated.Order6DivisorTransfers.S6_10800.representative_basis)) (by decide +kernel)

/-- Every class of part 072 of the catalogue is classified. -/
theorem shard072 : AllClassified Catalogue.Order6.part072 :=
  AllClassified.cons S6_10651 <|
  AllClassified.cons S6_10652 <|
  AllClassified.cons S6_10653 <|
  AllClassified.cons S6_10654 <|
  AllClassified.cons S6_10655 <|
  AllClassified.cons S6_10656 <|
  AllClassified.cons S6_10657 <|
  AllClassified.cons S6_10658 <|
  AllClassified.cons S6_10659 <|
  AllClassified.cons S6_10660 <|
  AllClassified.cons S6_10661 <|
  AllClassified.cons S6_10662 <|
  AllClassified.cons S6_10663 <|
  AllClassified.cons S6_10664 <|
  AllClassified.cons S6_10665 <|
  AllClassified.cons S6_10666 <|
  AllClassified.cons S6_10667 <|
  AllClassified.cons S6_10668 <|
  AllClassified.cons S6_10669 <|
  AllClassified.cons S6_10670 <|
  AllClassified.cons S6_10671 <|
  AllClassified.cons S6_10672 <|
  AllClassified.cons S6_10673 <|
  AllClassified.cons S6_10674 <|
  AllClassified.cons S6_10675 <|
  AllClassified.cons S6_10676 <|
  AllClassified.cons S6_10677 <|
  AllClassified.cons S6_10678 <|
  AllClassified.cons S6_10679 <|
  AllClassified.cons S6_10680 <|
  AllClassified.cons S6_10681 <|
  AllClassified.cons S6_10682 <|
  AllClassified.cons S6_10683 <|
  AllClassified.cons S6_10684 <|
  AllClassified.cons S6_10685 <|
  AllClassified.cons S6_10686 <|
  AllClassified.cons S6_10687 <|
  AllClassified.cons S6_10688 <|
  AllClassified.cons S6_10689 <|
  AllClassified.cons S6_10690 <|
  AllClassified.cons S6_10691 <|
  AllClassified.cons S6_10692 <|
  AllClassified.cons S6_10693 <|
  AllClassified.cons S6_10694 <|
  AllClassified.cons S6_10695 <|
  AllClassified.cons S6_10696 <|
  AllClassified.cons S6_10697 <|
  AllClassified.cons S6_10698 <|
  AllClassified.cons S6_10699 <|
  AllClassified.cons S6_10700 <|
  AllClassified.cons S6_10701 <|
  AllClassified.cons S6_10702 <|
  AllClassified.cons S6_10703 <|
  AllClassified.cons S6_10704 <|
  AllClassified.cons S6_10705 <|
  AllClassified.cons S6_10706 <|
  AllClassified.cons S6_10707 <|
  AllClassified.cons S6_10708 <|
  AllClassified.cons S6_10709 <|
  AllClassified.cons S6_10710 <|
  AllClassified.cons S6_10711 <|
  AllClassified.cons S6_10712 <|
  AllClassified.cons S6_10713 <|
  AllClassified.cons S6_10714 <|
  AllClassified.cons S6_10715 <|
  AllClassified.cons S6_10716 <|
  AllClassified.cons S6_10717 <|
  AllClassified.cons S6_10718 <|
  AllClassified.cons S6_10719 <|
  AllClassified.cons S6_10720 <|
  AllClassified.cons S6_10721 <|
  AllClassified.cons S6_10722 <|
  AllClassified.cons S6_10723 <|
  AllClassified.cons S6_10724 <|
  AllClassified.cons S6_10725 <|
  AllClassified.cons S6_10726 <|
  AllClassified.cons S6_10727 <|
  AllClassified.cons S6_10728 <|
  AllClassified.cons S6_10729 <|
  AllClassified.cons S6_10730 <|
  AllClassified.cons S6_10731 <|
  AllClassified.cons S6_10732 <|
  AllClassified.cons S6_10733 <|
  AllClassified.cons S6_10734 <|
  AllClassified.cons S6_10735 <|
  AllClassified.cons S6_10736 <|
  AllClassified.cons S6_10737 <|
  AllClassified.cons S6_10738 <|
  AllClassified.cons S6_10739 <|
  AllClassified.cons S6_10740 <|
  AllClassified.cons S6_10741 <|
  AllClassified.cons S6_10742 <|
  AllClassified.cons S6_10743 <|
  AllClassified.cons S6_10744 <|
  AllClassified.cons S6_10745 <|
  AllClassified.cons S6_10746 <|
  AllClassified.cons S6_10747 <|
  AllClassified.cons S6_10748 <|
  AllClassified.cons S6_10749 <|
  AllClassified.cons S6_10750 <|
  AllClassified.cons S6_10751 <|
  AllClassified.cons S6_10752 <|
  AllClassified.cons S6_10753 <|
  AllClassified.cons S6_10754 <|
  AllClassified.cons S6_10755 <|
  AllClassified.cons S6_10756 <|
  AllClassified.cons S6_10757 <|
  AllClassified.cons S6_10758 <|
  AllClassified.cons S6_10759 <|
  AllClassified.cons S6_10760 <|
  AllClassified.cons S6_10761 <|
  AllClassified.cons S6_10762 <|
  AllClassified.cons S6_10763 <|
  AllClassified.cons S6_10764 <|
  AllClassified.cons S6_10765 <|
  AllClassified.cons S6_10766 <|
  AllClassified.cons S6_10767 <|
  AllClassified.cons S6_10768 <|
  AllClassified.cons S6_10769 <|
  AllClassified.cons S6_10770 <|
  AllClassified.cons S6_10771 <|
  AllClassified.cons S6_10772 <|
  AllClassified.cons S6_10773 <|
  AllClassified.cons S6_10774 <|
  AllClassified.cons S6_10775 <|
  AllClassified.cons S6_10776 <|
  AllClassified.cons S6_10777 <|
  AllClassified.cons S6_10778 <|
  AllClassified.cons S6_10779 <|
  AllClassified.cons S6_10780 <|
  AllClassified.cons S6_10781 <|
  AllClassified.cons S6_10782 <|
  AllClassified.cons S6_10783 <|
  AllClassified.cons S6_10784 <|
  AllClassified.cons S6_10785 <|
  AllClassified.cons S6_10786 <|
  AllClassified.cons S6_10787 <|
  AllClassified.cons S6_10788 <|
  AllClassified.cons S6_10789 <|
  AllClassified.cons S6_10790 <|
  AllClassified.cons S6_10791 <|
  AllClassified.cons S6_10792 <|
  AllClassified.cons S6_10793 <|
  AllClassified.cons S6_10794 <|
  AllClassified.cons S6_10795 <|
  AllClassified.cons S6_10796 <|
  AllClassified.cons S6_10797 <|
  AllClassified.cons S6_10798 <|
  AllClassified.cons S6_10799 <|
  AllClassified.cons S6_10800 <|
  AllClassified.nil

end SemiBase.Census
