import SemigroupBasis.CoRoots.S5_415HeadNormalization

namespace SemigroupBasis.CoRoots.S5_415

open SemigroupBasis

/-! ## Endpoint constraint connectivity -/

/-- Each variable contributes an incoming and an outgoing matrix-unit
coordinate to the Brandt compatibility graph. -/
inductive BrandtEndpointSide where
  | incoming
  | outgoing
deriving Repr, DecidableEq

structure BrandtEndpoint where
  letter : Nat
  side : BrandtEndpointSide
deriving Repr, DecidableEq

namespace BrandtEndpoint

def incoming (letter : Nat) : BrandtEndpoint :=
  ⟨letter, BrandtEndpointSide.incoming⟩

def outgoing (letter : Nat) : BrandtEndpoint :=
  ⟨letter, BrandtEndpointSide.outgoing⟩

end BrandtEndpoint

def brandtEndpointValue
    (assignment : EndpointAssignment) (endpoint : BrandtEndpoint) : Fin 2 :=
  match endpoint.side with
  | BrandtEndpointSide.incoming => (assignment endpoint.letter).1
  | BrandtEndpointSide.outgoing => (assignment endpoint.letter).2

def endpointAssignmentOfColor
    (color : BrandtEndpoint → Fin 2) : EndpointAssignment :=
  fun letter =>
    (color (BrandtEndpoint.incoming letter),
      color (BrandtEndpoint.outgoing letter))

@[simp]
theorem brandtEndpointValue_endpointAssignmentOfColor
    (color : BrandtEndpoint → Fin 2) (endpoint : BrandtEndpoint) :
    brandtEndpointValue (endpointAssignmentOfColor color) endpoint =
      color endpoint := by
  cases endpoint with
  | mk letter side =>
      cases side <;> rfl

/-- The equivalence relation generated by the coordinate equation attached
to every adjacent pair in a word. -/
inductive BrandtEndpointConnected (word : Word Nat) :
    BrandtEndpoint → BrandtEndpoint → Prop
  | refl (endpoint : BrandtEndpoint) :
      BrandtEndpointConnected word endpoint endpoint
  | adjacency {source target : Nat}
      (member : (source, target) ∈ word.adjacentPairs) :
      BrandtEndpointConnected word
        (BrandtEndpoint.outgoing source)
        (BrandtEndpoint.incoming target)
  | symm {left right : BrandtEndpoint} :
      BrandtEndpointConnected word left right →
        BrandtEndpointConnected word right left
  | trans {left middle right : BrandtEndpoint} :
      BrandtEndpointConnected word left middle →
        BrandtEndpointConnected word middle right →
          BrandtEndpointConnected word left right

/-- Connected endpoint vertices receive equal values under every compatible
endpoint assignment. -/
theorem brandtEndpointValue_eq_of_connected
    {word : Word Nat} (assignment : EndpointAssignment)
    (compatible : Compatible assignment word)
    {left right : BrandtEndpoint}
    (connected : BrandtEndpointConnected word left right) :
    brandtEndpointValue assignment left =
      brandtEndpointValue assignment right := by
  induction connected with
  | refl endpoint => rfl
  | adjacency member =>
      exact
        (compatible_iff_adjacent_endpoint_eq assignment word).mp
          compatible _ _ member
  | symm connected ih => exact ih.symm
  | trans first second firstIH secondIH =>
      exact firstIH.trans secondIH

/-- Boolean endpoint assignments separate distinct connected components.
Thus semantic equality under all compatible assignments is not an assumed
connectivity fact: it yields a path in the generated endpoint relation. -/
theorem brandtEndpointConnected_of_forced_eq
    {word : Word Nat} {left right : BrandtEndpoint}
    (forced :
      ∀ assignment : EndpointAssignment,
        Compatible assignment word →
          brandtEndpointValue assignment left =
            brandtEndpointValue assignment right) :
    BrandtEndpointConnected word left right := by
  classical
  apply Decidable.byContradiction
  intro separated
  let color : BrandtEndpoint → Fin 2 := fun endpoint =>
    if BrandtEndpointConnected word left endpoint then 0 else 1
  let assignment : EndpointAssignment :=
    endpointAssignmentOfColor color
  have compatible : Compatible assignment word := by
    rw [compatible_iff_adjacent_endpoint_eq]
    intro source target member
    have edge :
        BrandtEndpointConnected word
          (BrandtEndpoint.outgoing source)
          (BrandtEndpoint.incoming target) :=
      BrandtEndpointConnected.adjacency member
    by_cases sourceConnected :
        BrandtEndpointConnected word left
          (BrandtEndpoint.outgoing source)
    · have targetConnected :
          BrandtEndpointConnected word left
            (BrandtEndpoint.incoming target) :=
        BrandtEndpointConnected.trans sourceConnected edge
      change
        color (BrandtEndpoint.outgoing source) =
          color (BrandtEndpoint.incoming target)
      simp [color, sourceConnected, targetConnected]
    · have targetSeparated :
          ¬BrandtEndpointConnected word left
            (BrandtEndpoint.incoming target) := by
        intro targetConnected
        exact sourceConnected <|
          BrandtEndpointConnected.trans targetConnected
            (BrandtEndpointConnected.symm edge)
      change
        color (BrandtEndpoint.outgoing source) =
          color (BrandtEndpoint.incoming target)
      simp [color, sourceConnected, targetSeparated]
  have forcedEquality := forced assignment compatible
  have leftConnected : BrandtEndpointConnected word left left :=
    BrandtEndpointConnected.refl left
  have impossible : (0 : Fin 2) = 1 := by
    simpa [assignment, color, leftConnected, separated] using
      forcedEquality
  exact (by decide : (0 : Fin 2) ≠ 1) impossible

theorem brandtEndpointConnected_iff_forced_eq
    {word : Word Nat} {left right : BrandtEndpoint} :
    BrandtEndpointConnected word left right ↔
      ∀ assignment : EndpointAssignment,
        Compatible assignment word →
          brandtEndpointValue assignment left =
            brandtEndpointValue assignment right := by
  constructor
  · intro connected assignment compatible
    exact brandtEndpointValue_eq_of_connected assignment compatible
      connected
  · exact brandtEndpointConnected_of_forced_eq

/-- Equal Brandt signatures generate exactly the same endpoint-component
relation. -/
theorem brandtEndpointConnected_iff_of_sameBrandtSignature
    {left right : Word Nat}
    (same : SameBrandtSignature left right)
    (first second : BrandtEndpoint) :
    BrandtEndpointConnected left first second ↔
      BrandtEndpointConnected right first second := by
  constructor
  · intro connected
    apply brandtEndpointConnected_of_forced_eq
    intro assignment rightCompatible
    have leftCompatible : Compatible assignment left :=
      ((same.2 assignment).1).mpr rightCompatible
    exact brandtEndpointValue_eq_of_connected assignment
      leftCompatible connected
  · intro connected
    apply brandtEndpointConnected_of_forced_eq
    intro assignment leftCompatible
    have rightCompatible : Compatible assignment right :=
      ((same.2 assignment).1).mp leftCompatible
    exact brandtEndpointValue_eq_of_connected assignment
      rightCompatible connected

theorem incomingHeads_connected_of_sameBrandtSignature
    {left right : Word Nat}
    (same : SameBrandtSignature left right) :
    BrandtEndpointConnected left
      (BrandtEndpoint.incoming left.head)
      (BrandtEndpoint.incoming right.head) := by
  apply brandtEndpointConnected_of_forced_eq
  intro assignment compatible
  exact ((same.2 assignment).2 compatible).1

theorem outgoingFinals_connected_of_sameBrandtSignature
    {left right : Word Nat}
    (same : SameBrandtSignature left right) :
    BrandtEndpointConnected left
      (BrandtEndpoint.outgoing left.final)
      (BrandtEndpoint.outgoing right.final) := by
  apply brandtEndpointConnected_of_forced_eq
  intro assignment compatible
  exact ((same.2 assignment).2 compatible).2

/-- A common endpoint anchor is a genuine vertex shared by the two generated
constraint-component relations. It is weaker than a common literal word
prefix; no derivational retargeting is hidden in this structure. -/
structure BrandtEndpointAlignment (left right : Word Nat) where
  incomingAnchor : BrandtEndpoint
  outgoingAnchor : BrandtEndpoint
  leftIncoming :
    BrandtEndpointConnected left incomingAnchor
      (BrandtEndpoint.incoming left.head)
  rightIncoming :
    BrandtEndpointConnected right incomingAnchor
      (BrandtEndpoint.incoming right.head)
  leftOutgoing :
    BrandtEndpointConnected left outgoingAnchor
      (BrandtEndpoint.outgoing left.final)
  rightOutgoing :
    BrandtEndpointConnected right outgoingAnchor
      (BrandtEndpoint.outgoing right.final)

/-- `SameBrandtSignature` supplies common initial and final endpoint anchors;
the witnesses are chosen from the left word and transferred to the right by
the proved equality of generated component relations. -/
def endpointAlignment_of_sameBrandtSignature
    {left right : Word Nat}
    (same : SameBrandtSignature left right) :
    BrandtEndpointAlignment left right := by
  have incomingLeft :=
    incomingHeads_connected_of_sameBrandtSignature same
  have incomingRight :
      BrandtEndpointConnected right
        (BrandtEndpoint.incoming left.head)
        (BrandtEndpoint.incoming right.head) :=
    (brandtEndpointConnected_iff_of_sameBrandtSignature same _ _).mp
      incomingLeft
  have outgoingLeft :=
    outgoingFinals_connected_of_sameBrandtSignature same
  have outgoingRight :
      BrandtEndpointConnected right
        (BrandtEndpoint.outgoing left.final)
        (BrandtEndpoint.outgoing right.final) :=
    (brandtEndpointConnected_iff_of_sameBrandtSignature same _ _).mp
      outgoingLeft
  exact
    { incomingAnchor := BrandtEndpoint.incoming left.head
      outgoingAnchor := BrandtEndpoint.outgoing left.final
      leftIncoming := BrandtEndpointConnected.refl _
      rightIncoming := incomingRight
      leftOutgoing := BrandtEndpointConnected.refl _
      rightOutgoing := outgoingRight }

/-! ## Interaction with recursive normalization -/

/-- Every formal derivation from Trahtman's three laws preserves the exact
Brandt signature. -/
theorem derives_sameBrandtSignature
    {left right : Word Nat}
    (derivation : Derives basis left right) :
    SameBrandtSignature left right := by
  apply valid_sameBrandtSignature (identity := Identity.mk left right)
  intro valuation
  exact Derives.sound catalogueModels derivation valuation

theorem normalizeBrandtWord_sameBrandtSignature (word : Word Nat) :
    SameBrandtSignature word (normalizeBrandtWord word) :=
  derives_sameBrandtSignature (derivesNormalizeBrandtWord word)

/-- Recursive normalization preserves all support, compatibility-component,
and marked endpoint data on both sides of a valid Brandt identity. -/
theorem normalizedWords_sameBrandtSignature
    {left right : Word Nat}
    (same : SameBrandtSignature left right) :
    SameBrandtSignature
      (normalizeBrandtWord left) (normalizeBrandtWord right) := by
  apply valid_sameBrandtSignature
    (identity := Identity.mk
      (normalizeBrandtWord left) (normalizeBrandtWord right))
  intro valuation
  have normalizeLeft :=
    Derives.sound catalogueModels
      (derivesNormalizeBrandtWord left) valuation
  have middle :=
    valid_of_sameBrandtSignature
      (identity := Identity.mk left right) same valuation
  have normalizeRight :=
    Derives.sound catalogueModels
      (derivesNormalizeBrandtWord right) valuation
  exact normalizeLeft.symm.trans <| middle.trans normalizeRight

def normalizedWords_endpointAlignment
    {left right : Word Nat}
    (same : SameBrandtSignature left right) :
    BrandtEndpointAlignment
      (normalizeBrandtWord left) (normalizeBrandtWord right) :=
  endpointAlignment_of_sameBrandtSignature
    (normalizedWords_sameBrandtSignature same)

theorem normalizedWords_endpointConnected_iff
    {left right : Word Nat}
    (same : SameBrandtSignature left right)
    (first second : BrandtEndpoint) :
    BrandtEndpointConnected (normalizeBrandtWord left) first second ↔
      BrandtEndpointConnected (normalizeBrandtWord right) first second :=
  brandtEndpointConnected_iff_of_sameBrandtSignature
    (normalizedWords_sameBrandtSignature same) first second

theorem normalizedIncomingHeads_connected
    {left right : Word Nat}
    (same : SameBrandtSignature left right) :
    BrandtEndpointConnected (normalizeBrandtWord left)
      (BrandtEndpoint.incoming left.head)
      (BrandtEndpoint.incoming right.head) := by
  simpa using
    incomingHeads_connected_of_sameBrandtSignature
      (normalizedWords_sameBrandtSignature same)

theorem normalizedWords_support_iff
    {left right : Word Nat}
    (same : SameBrandtSignature left right) (letter : Nat) :
    letter ∈ (normalizeBrandtWord left).toList ↔
      letter ∈ (normalizeBrandtWord right).toList :=
  (normalizedWords_sameBrandtSignature same).1 letter

theorem normalizedWords_compatible_iff
    {left right : Word Nat}
    (same : SameBrandtSignature left right)
    (assignment : EndpointAssignment) :
    Compatible assignment (normalizeBrandtWord left) ↔
      Compatible assignment (normalizeBrandtWord right) :=
  ((normalizedWords_sameBrandtSignature same).2 assignment).1

end SemigroupBasis.CoRoots.S5_415
