import SemigroupBasis.CoRoots.Order6L3Root3.Macros60

/-!
# Generated `s4_60` fresh-append insertion macros

This file is generated by `tools/order6/l3_root3/generate_insertion_macros.py`
from the accepted inclusive pre-freeze evidence SHA-256
`70d2787133128108a20385269ad7e31412d76f36ac75565d80849699e4f415e2`.  It contains 7 mechanically
rendered labeled-BFS paths and must not be edited by hand.
-/

set_option maxRecDepth 100000

namespace SemigroupBasis.CoRoots.Order6L3Root3

open SemigroupBasis

/-- Generated from accepted inclusive BFS labels: `s4_60/fresh/000`, cap 4, 1 step(s). -/
theorem derives60FreshShape000
    (V0 V1 : Word Nat) :
    Derives basis60
      (V0 ++ (V0 ++ (V0 ++ (V1))))
      (V0 ++ (V0 ++ (V1))) := by
  have step0 : Derives basis60
      (V0 ++ (V0 ++ (V0 ++ (V1))))
      (V0 ++ (V0 ++ (V1))) := by
    simpa [Word.append_assoc] using
      (derives60RightCollapse (V0) (V1))
  exact step0

/-- Generated from accepted inclusive BFS labels: `s4_60/fresh/001`, cap 4, 1 step(s). -/
theorem derives60FreshShape001
    (V0 V1 V2 : Word Nat) :
    Derives basis60
      (V0 ++ (V0 ++ (V1 ++ (V2))))
      (V0 ++ (V1 ++ (V2))) := by
  have step0 : Derives basis60
      (V0 ++ (V0 ++ (V1 ++ (V2))))
      (V0 ++ (V1 ++ (V2))) := by
    simpa [Word.append_assoc] using
      (derives60OpenContraction (V0) (V1) (V2))
  exact step0

/-- Generated from accepted inclusive BFS labels: `s4_60/fresh/002`, cap 4, 1 step(s). -/
theorem derives60FreshShape002
    (V0 V1 V2 : Word Nat) :
    Derives basis60
      (V0 ++ (V1 ++ (V0 ++ (V2))))
      (V0 ++ (V1 ++ (V2))) := by
  have step0 : Derives basis60
      (V0 ++ (V1 ++ (V0 ++ (V2))))
      (V0 ++ (V1 ++ (V2))) := by
    simpa [Word.append_assoc] using
      (derives60AnchoredContraction (V0) (V1) (V2))
  exact step0

/-- Generated from accepted inclusive BFS labels: `s4_60/fresh/003`, cap 4, 2 step(s). -/
theorem derives60FreshShape003
    (V0 V1 V2 : Word Nat) :
    Derives basis60
      (V0 ++ (V1 ++ (V1 ++ (V2))))
      (V0 ++ (V1 ++ (V2))) := by
  have step0 : Derives basis60
      (V0 ++ (V1 ++ (V1 ++ (V2))))
      (V0 ++ (V1 ++ (V0 ++ (V2)))) := by
    simpa [Word.append_assoc] using
      (Derives.appendRight (Derives.symm (derives60FinalDuplicateSwitch (V0) (V1))) (V2))
  have step1 : Derives basis60
      (V0 ++ (V1 ++ (V0 ++ (V2))))
      (V0 ++ (V1 ++ (V2))) := by
    simpa [Word.append_assoc] using
      (derives60AnchoredContraction (V0) (V1) (V2))
  exact Derives.trans (step0) step1

/-- Generated from accepted inclusive BFS labels: `s4_60/fresh/004`, cap 5, 3 step(s). -/
theorem derives60FreshShape004
    (V0 V1 V2 V3 : Word Nat) :
    Derives basis60
      (V0 ++ (V1 ++ (V2 ++ (V3))))
      (V0 ++ (V2 ++ (V1 ++ (V3)))) := by
  have step0 : Derives basis60
      (V0 ++ (V1 ++ (V2 ++ (V3))))
      (V0 ++ (V1 ++ (V2 ++ (V0 ++ (V3))))) := by
    simpa [Word.append_assoc] using
      (Derives.symm (derives60AnchoredContraction (V0) (V1 ++ (V2)) (V3)))
  have step1 : Derives basis60
      (V0 ++ (V1 ++ (V2 ++ (V0 ++ (V3)))))
      (V0 ++ (V2 ++ (V1 ++ (V0 ++ (V3))))) := by
    simpa [Word.append_assoc] using
      (Derives.appendRight (derives60InteriorSwap (V0) (V1) (V2)) (V3))
  have step2 : Derives basis60
      (V0 ++ (V2 ++ (V1 ++ (V0 ++ (V3)))))
      (V0 ++ (V2 ++ (V1 ++ (V3)))) := by
    simpa [Word.append_assoc] using
      (derives60AnchoredContraction (V0) (V2 ++ (V1)) (V3))
  exact Derives.trans (Derives.trans (step0) step1) step2

/-- Generated from accepted inclusive BFS labels: `s4_60/fresh/005`, cap 5, 1 step(s). -/
theorem derives60FreshShape005
    (V0 V1 V2 V3 : Word Nat) :
    Derives basis60
      (V0 ++ (V1 ++ (V2 ++ (V0 ++ (V3)))))
      (V0 ++ (V1 ++ (V2 ++ (V3)))) := by
  have step0 : Derives basis60
      (V0 ++ (V1 ++ (V2 ++ (V0 ++ (V3)))))
      (V0 ++ (V1 ++ (V2 ++ (V3)))) := by
    simpa [Word.append_assoc] using
      (derives60AnchoredContraction (V0) (V1 ++ (V2)) (V3))
  exact step0

/-- Generated from accepted inclusive BFS labels: `s4_60/fresh/006`, cap 5, 1 step(s). -/
theorem derives60FreshShape006
    (V0 V1 V2 V3 : Word Nat) :
    Derives basis60
      (V0 ++ (V1 ++ (V2 ++ (V1 ++ (V3)))))
      (V0 ++ (V1 ++ (V2 ++ (V3)))) := by
  have step0 : Derives basis60
      (V0 ++ (V1 ++ (V2 ++ (V1 ++ (V3)))))
      (V0 ++ (V1 ++ (V2 ++ (V3)))) := by
    simpa [Word.append_assoc] using
      (Derives.prepend (V0) (derives60AnchoredContraction (V1) (V2) (V3)))
  exact step0

theorem generated60FreshShapeCount :
    7 = 7 := by
  decide

end SemigroupBasis.CoRoots.Order6L3Root3
