import SemigroupBasis.CoRoots.Order6L3RootS4_23S4_90.Blocks

/-!
# Generated direct displayed-law macros for the rank-13 light root

Generated by `tools/order6/l3_root_s4_23_s4_90/generate_macros.py` from
immutable evidence SHA-256 `823a6797558a2d4ac0326935bed4de46f86a3ec63f9348e8cb666b632478d3bd`. It must not be edited by hand.
-/

set_option maxRecDepth 100000

namespace SemigroupBasis.CoRoots.Order6L3RootS4_23S4_90

open SemigroupBasis

private def word (head : Nat) (tail : List Nat) : Word Nat :=
  Word.mk head tail

private def instantiateFourWords
    (first second third fourth : Word Nat) : Nat → Word Nat
  | 0 => first
  | 1 => second
  | 2 => third
  | 3 => fourth
  | n + 4 => Word.singleton (n + 4)

/-- Direct substitution instance of displayed law 0. -/
theorem derivesLaw00 (V0 : Word Nat) :
    Derives basis
      (V0 ++ (V0))
      (V0 ++ (V0 ++ (V0 ++ (V0)))) := by
  have base :
      Derives basis (word 0 [0]) (word 0 [0, 0, 0]) :=
    Derives.fromBasis (e := Identity.mk
      (word 0 [0]) (word 0 [0, 0, 0])) (by decide)
  have substituted :=
    Derives.subst base (instantiateFourWords V0 V0 V0 V0)
  simpa [word, instantiateFourWords, Word.bind, Word.append,
    Word.singleton, Word.append_assoc] using substituted

/-- Direct substitution instance of displayed law 1. -/
theorem derivesLaw01 (V0 V1 : Word Nat) :
    Derives basis
      (V0 ++ (V0 ++ (V0 ++ (V1 ++ (V0)))))
      (V0 ++ (V1 ++ (V0))) := by
  have base :
      Derives basis (word 0 [0, 0, 1, 0]) (word 0 [1, 0]) :=
    Derives.fromBasis (e := Identity.mk
      (word 0 [0, 0, 1, 0]) (word 0 [1, 0])) (by decide)
  have substituted :=
    Derives.subst base (instantiateFourWords V0 V1 V1 V1)
  simpa [word, instantiateFourWords, Word.bind, Word.append,
    Word.singleton, Word.append_assoc] using substituted

/-- Direct substitution instance of displayed law 2. -/
theorem derivesLaw02 (V0 V1 : Word Nat) :
    Derives basis
      (V0 ++ (V0 ++ (V1 ++ (V0))))
      (V0 ++ (V1 ++ (V0 ++ (V0)))) := by
  have base :
      Derives basis (word 0 [0, 1, 0]) (word 0 [1, 0, 0]) :=
    Derives.fromBasis (e := Identity.mk
      (word 0 [0, 1, 0]) (word 0 [1, 0, 0])) (by decide)
  have substituted :=
    Derives.subst base (instantiateFourWords V0 V1 V1 V1)
  simpa [word, instantiateFourWords, Word.bind, Word.append,
    Word.singleton, Word.append_assoc] using substituted

/-- Direct substitution instance of displayed law 3. -/
theorem derivesLaw03 (V0 V1 : Word Nat) :
    Derives basis
      (V0 ++ (V0 ++ (V1 ++ (V0 ++ (V0)))))
      (V0 ++ (V1 ++ (V0))) := by
  have base :
      Derives basis (word 0 [0, 1, 0, 0]) (word 0 [1, 0]) :=
    Derives.fromBasis (e := Identity.mk
      (word 0 [0, 1, 0, 0]) (word 0 [1, 0])) (by decide)
  have substituted :=
    Derives.subst base (instantiateFourWords V0 V1 V1 V1)
  simpa [word, instantiateFourWords, Word.bind, Word.append,
    Word.singleton, Word.append_assoc] using substituted

/-- Direct substitution instance of displayed law 4. -/
theorem derivesLaw04 (V0 V1 : Word Nat) :
    Derives basis
      (V0 ++ (V0 ++ (V1 ++ (V1))))
      (V0 ++ (V1 ++ (V0 ++ (V1)))) := by
  have base :
      Derives basis (word 0 [0, 1, 1]) (word 0 [1, 0, 1]) :=
    Derives.fromBasis (e := Identity.mk
      (word 0 [0, 1, 1]) (word 0 [1, 0, 1])) (by decide)
  have substituted :=
    Derives.subst base (instantiateFourWords V0 V1 V1 V1)
  simpa [word, instantiateFourWords, Word.bind, Word.append,
    Word.singleton, Word.append_assoc] using substituted

/-- Direct substitution instance of displayed law 5. -/
theorem derivesLaw05 (V0 V1 : Word Nat) :
    Derives basis
      (V0 ++ (V0 ++ (V1 ++ (V1))))
      (V0 ++ (V1 ++ (V1 ++ (V0)))) := by
  have base :
      Derives basis (word 0 [0, 1, 1]) (word 0 [1, 1, 0]) :=
    Derives.fromBasis (e := Identity.mk
      (word 0 [0, 1, 1]) (word 0 [1, 1, 0])) (by decide)
  have substituted :=
    Derives.subst base (instantiateFourWords V0 V1 V1 V1)
  simpa [word, instantiateFourWords, Word.bind, Word.append,
    Word.singleton, Word.append_assoc] using substituted

/-- Direct substitution instance of displayed law 6. -/
theorem derivesLaw06 (V0 V1 : Word Nat) :
    Derives basis
      (V0 ++ (V0 ++ (V1 ++ (V1 ++ (V1)))))
      (V0 ++ (V1 ++ (V1 ++ (V1 ++ (V0))))) := by
  have base :
      Derives basis (word 0 [0, 1, 1, 1]) (word 0 [1, 1, 1, 0]) :=
    Derives.fromBasis (e := Identity.mk
      (word 0 [0, 1, 1, 1]) (word 0 [1, 1, 1, 0])) (by decide)
  have substituted :=
    Derives.subst base (instantiateFourWords V0 V1 V1 V1)
  simpa [word, instantiateFourWords, Word.bind, Word.append,
    Word.singleton, Word.append_assoc] using substituted

/-- Direct substitution instance of displayed law 7. -/
theorem derivesLaw07 (V0 V1 V2 : Word Nat) :
    Derives basis
      (V0 ++ (V0 ++ (V1 ++ (V2))))
      (V0 ++ (V1 ++ (V0 ++ (V2)))) := by
  have base :
      Derives basis (word 0 [0, 1, 2]) (word 0 [1, 0, 2]) :=
    Derives.fromBasis (e := Identity.mk
      (word 0 [0, 1, 2]) (word 0 [1, 0, 2])) (by decide)
  have substituted :=
    Derives.subst base (instantiateFourWords V0 V1 V2 V2)
  simpa [word, instantiateFourWords, Word.bind, Word.append,
    Word.singleton, Word.append_assoc] using substituted

/-- Direct substitution instance of displayed law 8. -/
theorem derivesLaw08 (V0 V1 V2 : Word Nat) :
    Derives basis
      (V0 ++ (V0 ++ (V1 ++ (V2 ++ (V1)))))
      (V0 ++ (V1 ++ (V1 ++ (V2 ++ (V0))))) := by
  have base :
      Derives basis (word 0 [0, 1, 2, 1]) (word 0 [1, 1, 2, 0]) :=
    Derives.fromBasis (e := Identity.mk
      (word 0 [0, 1, 2, 1]) (word 0 [1, 1, 2, 0])) (by decide)
  have substituted :=
    Derives.subst base (instantiateFourWords V0 V1 V2 V2)
  simpa [word, instantiateFourWords, Word.bind, Word.append,
    Word.singleton, Word.append_assoc] using substituted

/-- Direct substitution instance of displayed law 9. -/
theorem derivesLaw09 (V0 V1 : Word Nat) :
    Derives basis
      (V0 ++ (V1 ++ (V0)))
      (V0 ++ (V1 ++ (V0 ++ (V0 ++ (V0))))) := by
  have base :
      Derives basis (word 0 [1, 0]) (word 0 [1, 0, 0, 0]) :=
    Derives.fromBasis (e := Identity.mk
      (word 0 [1, 0]) (word 0 [1, 0, 0, 0])) (by decide)
  have substituted :=
    Derives.subst base (instantiateFourWords V0 V1 V1 V1)
  simpa [word, instantiateFourWords, Word.bind, Word.append,
    Word.singleton, Word.append_assoc] using substituted

/-- Direct substitution instance of displayed law 10. -/
theorem derivesLaw10 (V0 V1 V2 : Word Nat) :
    Derives basis
      (V0 ++ (V1 ++ (V2 ++ (V0))))
      (V0 ++ (V2 ++ (V1 ++ (V0)))) := by
  have base :
      Derives basis (word 0 [1, 2, 0]) (word 0 [2, 1, 0]) :=
    Derives.fromBasis (e := Identity.mk
      (word 0 [1, 2, 0]) (word 0 [2, 1, 0])) (by decide)
  have substituted :=
    Derives.subst base (instantiateFourWords V0 V1 V2 V2)
  simpa [word, instantiateFourWords, Word.bind, Word.append,
    Word.singleton, Word.append_assoc] using substituted

/-- Direct substitution instance of displayed law 11. -/
theorem derivesLaw11 (V0 V1 V2 : Word Nat) :
    Derives basis
      (V0 ++ (V1 ++ (V2 ++ (V1))))
      (V0 ++ (V2 ++ (V1 ++ (V1)))) := by
  have base :
      Derives basis (word 0 [1, 2, 1]) (word 0 [2, 1, 1]) :=
    Derives.fromBasis (e := Identity.mk
      (word 0 [1, 2, 1]) (word 0 [2, 1, 1])) (by decide)
  have substituted :=
    Derives.subst base (instantiateFourWords V0 V1 V2 V2)
  simpa [word, instantiateFourWords, Word.bind, Word.append,
    Word.singleton, Word.append_assoc] using substituted

/-- Direct substitution instance of displayed law 12. -/
theorem derivesLaw12 (V0 V1 V2 V3 : Word Nat) :
    Derives basis
      (V0 ++ (V2 ++ (V1 ++ (V3))))
      (V0 ++ (V1 ++ (V2 ++ (V3)))) := by
  have base :
      Derives basis (word 0 [2, 1, 3]) (word 0 [1, 2, 3]) :=
    Derives.fromBasis (e := Identity.mk
      (word 0 [2, 1, 3]) (word 0 [1, 2, 3])) (by decide)
  have substituted :=
    Derives.subst base (instantiateFourWords V0 V1 V2 V3)
  simpa [word, instantiateFourWords, Word.bind, Word.append,
    Word.singleton, Word.append_assoc] using substituted

theorem generatedDirectLawCount : 13 = 13 := by
  decide

end SemigroupBasis.CoRoots.Order6L3RootS4_23S4_90
